'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');const C=require('../runtime/common.cjs'),P=C.POLICY,I=require('../runtime/identity.cjs'),E=require('../runtime/evidence.cjs');
const ROOT=path.resolve(__dirname,'..'),BRANCH='refactor/empire-treasury-rearchitecture',MESSAGE='evidence(compat): sanctioned recovery I for XII retry I';
function git(repo,args){try{return cp.execFileSync('git',['-c','core.autocrlf=false','-c','core.eol=lf','-C',repo,...args],{encoding:'utf8',timeout:120000,maxBuffer:20*1048576,stdio:['ignore','pipe','pipe']});}catch{C.fail('GIT_OPERATION_FAILED');}}
const text=(repo,args)=>git(repo,args).trim();
function clean(repo){if(git(repo,['status','--porcelain=v1','-z']).length)C.fail('REPOSITORY_NOT_CLEAN');}
function scope(repo,args){const names=git(repo,[...args,'--name-only','-z']).split('\0').filter(Boolean);if(!names.length||names.some(n=>!n.startsWith(P.evidencePath+'/')))C.fail('EVIDENCE_SCOPE_CHANGED');return names;}
function secretScan(b,token){return [token,encodeURIComponent(token),token.slice(0,8),token.slice(0,16),Buffer.from(token).toString('base64'),Buffer.from(token).toString('hex')].some(s=>s.length>=8&&b.includes(Buffer.from(s)));}
function verifyArchive(dir){const m=C.json(path.join(dir,'ARCHIVE-MANIFEST.json'));const names=C.list(dir).filter(n=>n!=='ARCHIVE-MANIFEST.json');if(!C.same(names.sort(),Object.keys(m.files).sort()))C.fail('ARCHIVE_FILE_SET_CHANGED');for(const n of names){const b=C.bytes(path.join(dir,n));if(b.length!==m.files[n].bytes||C.sha(b)!==m.files[n].sha256)C.fail('ARCHIVE_BYTES_CHANGED');}return m;}
function archive(o){const info=C.verifyPackage(),origin=I.loadOrigin(o.run),secret=C.loadSecret(o.secret),root=path.join(origin.run,P.ledgerDirectory);if(fs.existsSync(path.join(origin.run,'action.lock')))C.fail('ACTION_LOCK_PRESENT_NO_PUBLISH');
 const verification=E.verify(root,info.fingerprint),tests=C.json(path.join(o.tests,'result.json'));if(tests.status!=='RECOVERY_OFFLINE_TESTS_VERIFIED'||tests.packageFingerprint!==info.fingerprint||tests.tests!==require('../references/test-contract.json').count||tests.passed!==tests.tests||tests.failed!==0)C.fail('RECOVERY_TEST_GATE_MISSING');
 clean(o.compat);if(text(o.compat,['branch','--show-current'])!=='compat/treasury-read-bridge-i'||text(o.compat,['rev-parse','HEAD'])!==P.compatHead||text(o.compat,['rev-parse','HEAD^{tree}'])!==P.sourceTree)C.fail('COMPAT_SOURCE_CHANGED');
 if(text(o.refactor,['branch','--show-current'])!==BRANCH)C.fail('REFACTOR_BRANCH_CHANGED');const dest=path.join(o.refactor,P.evidencePath),head=text(o.refactor,['rev-parse','HEAD']);
 const files=new Map(),put=(name,b)=>{if(secretScan(b,secret.token))C.fail('SECRET_IN_ARCHIVE');files.set(name,b);};
 for(const n of C.list(root))put('recovery/'+n,C.bytes(path.join(root,n)));
 for(const n of C.list(ROOT))put('task-package/'+n,C.bytes(path.join(ROOT,n)));
 for(const n of ['result.json','tests.tap','tests.stderr'])put('offline-tests/'+n,C.bytes(path.join(o.tests,n)));
 put('FINAL-VERIFICATION.json',Buffer.from(JSON.stringify(verification,null,2)+'\n'));
 put('SOURCE-STATE.json',Buffer.from(JSON.stringify({compatHead:P.compatHead,sourceTree:P.sourceTree,refactorBase:P.refactorHead,sourceModified:false},null,2)+'\n'));
 put('EXECUTION-REPORT.md',Buffer.from('# XII sanctioned recovery I\n\nRecovery: '+verification.status+'\n\nParent observation remains CPU_DIAGNOSTIC_CAPTURE_INCONCLUSIVE. This recovery never adds diagnostic samples.\nOriginal restore attempts: 1; new authorization permits at most 1 additional restore attempt.\nPrivate backup/candidate snapshots, tokens and build artifacts are excluded.\n'));
 const manifest={kind:'sanctioned-recovery-I-archive/v1',refactorBase:P.refactorHead,compatHead:P.compatHead,parentRunId:P.parentRunId,authorizationId:P.authorizationId,packageFingerprint:info.fingerprint,secretScanHits:0,files:Object.fromEntries([...files].sort(([a],[b])=>a<b?-1:a>b?1:0).map(([n,b])=>[n,{bytes:b.length,sha256:C.sha(b)}]))};
 if(head===P.refactorHead){if(!fs.existsSync(dest)){clean(o.refactor);fs.mkdirSync(dest,{recursive:true});for(const[n,b]of files){const f=path.join(dest,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b,{flag:'wx'});}C.durable(path.join(dest,'ARCHIVE-MANIFEST.json'),manifest);}else{const m=verifyArchive(dest);if(!C.same(m,manifest))C.fail('EXISTING_ARCHIVE_DIFFERS');}
  // Reject unrelated working-tree changes before staging, including untracked paths.
  const status=git(o.refactor,['status','--porcelain=v1','-z','--untracked-files=all']);for(const entry of status.split('\0').filter(Boolean))if(!entry.slice(3).startsWith(P.evidencePath+'/'))C.fail('UNRELATED_REFACTOR_CHANGE');
  git(o.refactor,['add','--',P.evidencePath]);scope(o.refactor,['diff','--cached']);git(o.refactor,['diff','--cached','--check']);verifyArchive(dest);const indexed=git(o.refactor,['ls-files','--stage','-z','--',P.evidencePath]).split('\0').filter(Boolean);const names=C.list(dest);if(indexed.length!==names.length)C.fail('STAGED_FILE_SET_CHANGED');for(const line of indexed){const match=line.match(/^100644 ([0-9a-f]{40}) 0\t(.+)$/);if(!match||C.blob(C.bytes(path.join(o.refactor,match[2])))!==match[1])C.fail('STAGED_BYTES_CHANGED');}git(o.refactor,['commit','-m',MESSAGE]);
 }else{clean(o.refactor);if(text(o.refactor,['rev-parse','HEAD^'])!==P.refactorHead||text(o.refactor,['show','-s','--format=%s','HEAD'])!==MESSAGE)C.fail('UNEXPECTED_EVIDENCE_HEAD');scope(o.refactor,['diff',P.refactorHead,'HEAD']);if(!C.same(verifyArchive(dest),manifest))C.fail('EXISTING_ARCHIVE_DIFFERS');}
 clean(o.refactor);const commit=text(o.refactor,['rev-parse','HEAD']);if(text(o.refactor,['rev-parse','HEAD^'])!==P.refactorHead)C.fail('EVIDENCE_PARENT_CHANGED');git(o.refactor,['diff','--check',P.refactorHead,commit]);
 if(o.push){const c=text(o.compat,['ls-remote','--exit-code','origin','refs/heads/compat/treasury-read-bridge-i']).split(/\s/)[0];if(c!==P.compatHead)C.fail('COMPAT_REMOTE_CHANGED');const remote=()=>text(o.refactor,['ls-remote','--exit-code','origin','refs/heads/'+BRANCH]).split(/\s/)[0];const h=remote();if(![P.refactorHead,commit].includes(h))C.fail('REFACTOR_REMOTE_DIVERGED');if(h!==commit)git(o.refactor,['push','origin',`HEAD:refs/heads/${BRANCH}`]);if(remote()!==commit)C.fail('PUSH_READBACK_MISMATCH');}
 const result={status:o.push?'SANCTIONED_RECOVERY_EVIDENCE_PUSHED':'SANCTIONED_RECOVERY_EVIDENCE_COMMITTED',refactorHead:commit,compatHead:P.compatHead,recovery:verification.status,sourceModified:false,additionalRecoveryPostQuota:1};if(o.out)C.durable(o.out,result);return result;
}
module.exports={git,text,clean,scope,secretScan,verifyArchive,archive};
if(require.main===module)C.cli(async()=>{const o=C.options(['run','tests','refactor','compat','secret','out'],['push']);C.requireArgs(o,['run','tests','refactor','compat','secret']);console.log(JSON.stringify(archive(o)));});
