import { TREASURY_T1_LANE } from "@/runtime/treasuryTerminalLane";
import { createTreasuryFirstLiveControl } from "@/runtime/treasuryFirstLiveControl";
export { treasuryT1SerializedBytes } from "@/runtime/treasuryFirstLiveState";
const control = createTreasuryFirstLiveControl(TREASURY_T1_LANE);
export const armTreasuryT1FirstLive = control.arm;
export const heartbeatTreasuryT1FirstLive = control.heartbeat;
export const closeTreasuryT1FirstLive = control.close;
export const normalizeTreasuryT1FirstLiveControl = control.normalize;
export const treasuryT1FirstLiveAllows = control.allows;
export const treasuryT1FirstLiveStatus = control.status;
export const readTreasuryT1FirstLiveControl = control.read;
