'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const C=require('../runtime/common.cjs'),I=require('../runtime/identity.cjs'),T=require('../runtime/transport.cjs'),O=require('../runtime/observer.cjs'),K=require('../runtime/collector.cjs'),P=C.POLICY,{mk,tmp}=require('./helpers.cjs');
const frame=(kind,logs=[])=>JSON.stringify([`user:${P.expected.userId}/${kind}`,kind==='cpu'?{cpu:1}:{shard:'shard1',messages:{log:logs,results:[]}}]);
class WS{constructor(){this.listeners={};setTimeout(()=>this.emit('open',{}),0);}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}emit(k,e){for(const f of this.listeners[k]||[])f(e);}send(text){if(text.startsWith('auth '))setTimeout(()=>this.emit('message',{data:'auth ok'}),0);if(text.endsWith('/console'))this.timer=setInterval(()=>{this.emit('message',{data:frame('console')});this.emit('message',{data:frame('cpu')});},5);}close(){clearInterval(this.timer);}}
test('independent observer physically collects bounded synthetic WS and verifier recomputes',async()=>{const d=tmp();try{await O.observe({out:d,secret:{token:'fixture-not-real',redact:x=>x},invocationId:'fixture',WebSocketClass:WS,durationMs:40,pollMs:2,startupMs:1000,silenceMs:1000});const v=O.verify(d,{durationMs:40,silenceMs:1000});assert.equal(v.status,'RECOVERY_RUNTIME_INDEPENDENTLY_VERIFIED');assert.ok(v.positiveCpuFramesAfterReady>0);assert.ok(v.durationMs>=40);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('independent observer rejects bridge or runtime-error frames',()=>{assert.equal(O.frameKind(frame('console',['treasury-legacy-read-bridge'])).kind,'bad');assert.equal(O.frameKind(JSON.stringify([`user:${P.expected.userId}/console`,{shard:'shard1',error:'fixture',messages:{log:[],results:[]}}])).kind,'bad');});
test('collector emits terminal footer and remains separate from recovery observation',async()=>{const d=tmp(),s={profile:{startTick:200},build:{tag:'fixture'},backupBuild:P.backupBuild};try{const timer=setTimeout(()=>C.durable(path.join(d,'collector-stop.json'),{}),60);const r=await K.collect({dir:d,secret:{token:'fixture-not-real',redact:x=>x},session:s,WebSocketClass:WS,pollMs:3,startupMs:1000});clearTimeout(timer);assert.equal(r.reason,'REQUESTED_STOP');assert.equal(C.jsonl(path.join(d,'console.jsonl')).at(-1).kind,'collector-footer');assert.equal(fs.existsSync(path.join(d,'runtime-console.jsonl')),false);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('actual-sized loopback module GET and lost restore response never resend POST',async()=>{const backup=mk('b'.repeat(40));backup.main+=' '.repeat(4494748-Buffer.byteLength(backup.main));let current=backup,posts=0;const original=structuredClone(P.backupDigest);P.backupDigest=I.digest(backup);const srv=http.createServer((req,res)=>{const chunks=[];req.on('data',b=>chunks.push(b));req.on('end',()=>{if(req.method==='POST'){posts++;const body=JSON.parse(Buffer.concat(chunks));assert.equal(body.branch,'default');assert.deepEqual(body.modules,backup);current=body.modules;req.socket.destroy();}else{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:1,modules:current}));}});});await new Promise(r=>srv.listen(0,'127.0.0.1',r));try{const api=T.client({token:'fixture-not-real'},{testOrigin:`http://127.0.0.1:${srv.address().port}/`});assert.equal(Buffer.byteLength((await api.code(5000)).modules.main),4494748);await assert.rejects(api.restore(backup,5000),/HTTP_/);assert.deepEqual((await api.code(5000)).modules,backup);assert.equal(posts,1);}finally{P.backupDigest=original;await new Promise(r=>srv.close(r));}});
test('transport refuses non-loopback origin and noncanonical restore content',async()=>{assert.throws(()=>T.client({token:'fixture'},{testOrigin:'http://example.com/'}));const api=T.client({token:'fixture'},{testOrigin:'http://127.0.0.1:1/'});await assert.rejects(async()=>api.restore(mk('c'.repeat(40)),10));});
test('identity rejects binary, extra modules, altered embedded hash and duplicate build tags',()=>{assert.throws(()=>I.modules({main:'x',extra:'y'}));assert.throws(()=>I.modules({main:{binary:'AA=='}}));const m=mk('c'.repeat(40));assert.throws(()=>I.candidate({main:'x'+m.main},'c'.repeat(40),'a'.repeat(40)));assert.throws(()=>I.build({main:m.main+'\nconst BUILD_TAG = "again";'}));});
