#!/usr/bin/env node
'use strict';
/** No network/token access, game upload, git reset, branch checkout or commits.
 * Read exact Git objects; write only into an operator-created OLD-base worktree.
 * Vendored runtime code is generated from pinned sources, NOT reimplemented.
 */
const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');
const crypto = require('node:crypto');
const { createRequire } = require('node:module');
const HERE = path.resolve(__dirname, '..');
const PLAN = JSON.parse(fs.readFileSync(path.join(__dirname, 'source-plan.json'), 'utf8'));
const sha256 = b => crypto.createHash('sha256').update(b).digest('hex');
const blob = b => crypto.createHash('sha1').update(Buffer.from(`blob ${Buffer.byteLength(b)}\0`)).update(b).digest('hex');
function git(repo, args) {
  return cp.execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024,
    timeout: 20000, stdio: ['ignore', 'pipe', 'pipe'] });
}
function sourceReader(repo) {
  return file => {
    const content = git(repo, ['show', `${PLAN.sourceCommit}:${file}`]);
    const expected = git(repo, ['rev-parse', `${PLAN.sourceCommit}:${file}`]).trim();
    if (blob(content) !== expected) throw new Error(`source byte identity failed: ${file}`);
    if (PLAN.knownSourceBlobs[file] && PLAN.knownSourceBlobs[file] !== expected) throw new Error(`source lock mismatch: ${file}`);
    return content;
  };
}
function resolveDependency(from, requested) {
  let p;
  if (requested.startsWith('@/')) p = 'src/' + requested.slice(2);
  else if (requested.startsWith('./') || requested.startsWith('../')) p = path.posix.normalize(path.posix.join(path.posix.dirname(from), requested));
  else throw new Error(`external runtime dependency forbidden: ${requested}`);
  if (!p.endsWith('.ts')) p += '.ts';
  if (!PLAN.allowedRuntimeSources.includes(p)) throw new Error(`runtime closure escaped read allowlist: ${p}`);
  return p;
}
function compileClosure(read, ts) {
  const modules = new Map(), visiting = new Set();
  function visit(file) {
    if (modules.has(file) || visiting.has(file)) return;
    if (!PLAN.allowedRuntimeSources.includes(file)) throw new Error(`forbidden root: ${file}`);
    visiting.add(file);
    const text = read(file);
    const transpile = ts.transpileModule(text, { fileName: file, reportDiagnostics: true, compilerOptions: {
      module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, strict: true,
      sourceMap: false, removeComments: false, importHelpers: false, newLine: ts.NewLineKind.LineFeed,
    } });
    const errors = (transpile.diagnostics || []).filter(d => d.category === ts.DiagnosticCategory.Error);
    if (errors.length) throw new Error(`transpile failed: ${file}: ${ts.flattenDiagnosticMessageText(errors[0].messageText, ' ')}`);
    const ast = ts.createSourceFile(file + '.js', transpile.outputText, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    const deps = Object.create(null);
    function walk(n) {
      if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'require') {
        if (n.arguments.length !== 1 || !ts.isStringLiteral(n.arguments[0])) throw new Error(`dynamic require forbidden: ${file}`);
        const spec = n.arguments[0].text;
        deps[spec] = resolveDependency(file, spec);
      }
      if (ts.isCallExpression(n) && n.expression.kind === ts.SyntaxKind.ImportKeyword) throw new Error(`dynamic import forbidden: ${file}`);
      if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'eval') throw new Error(`eval forbidden: ${file}`);
      if (ts.isNewExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'Function') throw new Error(`Function constructor forbidden: ${file}`);
      ts.forEachChild(n, walk);
    }
    walk(ast);
    modules.set(file, { code: transpile.outputText, deps, sourceBlob: blob(text), sourceSha256: sha256(text), sourceBytes: Buffer.byteLength(text) });
    for (const target of Object.values(deps)) visit(target);
    visiting.delete(file);
  }
  PLAN.roots.forEach(visit);
  const ordered = [...modules.keys()].sort();
  const graph = Object.fromEntries(ordered.map(p => [p, modules.get(p).deps]));
  const entries = ordered.map(p => `${JSON.stringify(p)}: function(exports, require) {\n${modules.get(p).code}\n}`).join(',\n');
  const generated = `// @ts-nocheck\n/** GENERATED from pinned Git TS objects; do not edit this file.\n * Original sources are typechecked on the development tree; this is transpiled\n * runtime output, not a replacement authoring surface. Exports only two builders.\n * No facade/kernel/registry/runtimeServices/old resource writer is included.\n * source=${PLAN.sourceCommit}; TypeScript=${ts.version} */\nimport type { CompatReadBuilders } from "./treasuryCompatTypes";\nconst factories = {\n${entries}\n};\nconst dependencies = ${JSON.stringify(graph, null, 2)};\nexport function createCompatibilityReadCore(): CompatReadBuilders {\n  const cache = Object.create(null);\n  function load(id) {\n    if (Object.prototype.hasOwnProperty.call(cache, id)) return cache[id];\n    if (!Object.prototype.hasOwnProperty.call(factories, id)) throw new Error("unlisted read dependency");\n    const exports = Object.create(null);\n    cache[id] = exports;\n    factories[id](exports, spec => {\n      const target = dependencies[id][spec];\n      if (!target) throw new Error("unlisted read import");\n      return load(target);\n    });\n    return exports;\n  }\n  const observation = load("src/runtime/treasury/observation.ts");\n  const commitments = load("src/runtime/treasury/commitments.ts");\n  return Object.freeze({\n    buildObservation: options => observation.buildTreasuryObservation(options),\n    buildCommitments: options => commitments.buildTreasuryCommitmentIndex(options),\n  });\n}\n`;
  return { generated, sourceManifest: ordered.map(p => ({ path: p, ...Object.fromEntries(Object.entries(modules.get(p)).filter(([k]) => k !== 'code')) })) };
}
function replaceOnce(text, search, replacement, label) {
  const first = text.indexOf(search);
  if (first < 0 || text.indexOf(search, first + search.length) >= 0) throw new Error(`unique anchor not found: ${label}`);
  return text.slice(0, first) + replacement + text.slice(first + search.length);
}
function patchOldMain(text) {
  if (/getTreasuryService|treasuryBeginTick|treasuryEndTick|treasuryCompatRead/.test(text)) throw new Error('old main does not match the intended no-Treasury base');
  let result = replaceOnce(text, 'import { runEmpireInventoryShadowCheck } from "@/runtime/empireInventoryShadow";',
    'import { runEmpireInventoryShadowCheck } from "@/runtime/empireInventoryShadow";\nimport { runTreasuryCompatRead } from "@/runtime/treasuryCompatRuntime";', 'old main import');
  result = replaceOnce(result, '  cpuProfiler.measure("empireInventoryShadow", runEmpireInventoryShadowCheck);',
    '  cpuProfiler.measure("empireInventoryShadow", runEmpireInventoryShadowCheck);\n  cpuProfiler.measure("treasuryCompatRead", runTreasuryCompatRead);', 'old final phase');
  return result;
}
function patchOldMainTest(text) {
  let result = replaceOnce(text, '["empireInventoryShadow", "runEmpireInventoryShadowCheck"],',
    '["empireInventoryShadow", "runEmpireInventoryShadowCheck"],\n    ["treasuryCompatRead", "runTreasuryCompatRead"],', 'old main test phase');
  const matches = [...result.matchAll(/expect\(order\)\.toHaveLength\((\d+)\);/g)];
  if (matches.length !== 1) throw new Error('main test phase count anchor missing');
  result = result.replace(matches[0][0], `expect(order).toHaveLength(${Number(matches[0][1]) + 1});`);
  return result;
}
function ensureClean(repo, expected) {
  if (git(repo, ['rev-parse', 'HEAD']).trim() !== expected) throw new Error(`wrong target HEAD; expected ${expected}; no reset/rebase/checkout performed`);
  if (git(repo, ['status', '--porcelain', '--untracked-files=all']).trim()) throw new Error('target worktree is not clean');
}
function execute(sourceRepo, targetRepo, apply) {
  sourceRepo = fs.realpathSync(sourceRepo); targetRepo = fs.realpathSync(targetRepo);
  if (sourceRepo === targetRepo) throw new Error('development and OLD-base candidate must be different worktrees');
  if (git(sourceRepo, ['rev-parse', `${PLAN.sourceCommit}^{commit}`]).trim() !== PLAN.sourceCommit) throw new Error('pinned source commit not available');
  ensureClean(targetRepo, PLAN.productionBase);
  const sourceTs = createRequire(path.join(sourceRepo, 'package.json'))('typescript');
  const targetTs = createRequire(path.join(targetRepo, 'package.json'))('typescript');
  if (sourceTs.version !== '5.9.3' || targetTs.version !== sourceTs.version) throw new Error('assembly requires independently installed locked TypeScript 5.9.3 in BOTH worktrees');
  const main = git(targetRepo, ['show', 'HEAD:src/main.ts']);
  if (blob(main) !== PLAN.productionMainBlob) throw new Error('old production main byte identity mismatch');
  const test = git(targetRepo, ['show', 'HEAD:src/main.test.ts']);
  if (blob(test) !== PLAN.productionMainTestBlob) throw new Error('old main test identity mismatch');
  const { generated, sourceManifest } = compileClosure(sourceReader(sourceRepo), sourceTs);
  const outputs = new Map([
    ['src/main.ts', patchOldMain(main)],
    ['src/main.test.ts', patchOldMainTest(test)],
    ['src/runtime/treasuryCompatReadCore.generated.ts', generated],
  ]);
  for (const name of ['treasuryCompatTypes.ts', 'treasuryCompatConfig.ts', 'treasuryCompatRead.ts', 'treasuryCompatRuntime.ts']) {
    outputs.set('src/runtime/' + name, fs.readFileSync(path.join(HERE, 'templates', name), 'utf8'));
  }
  for (const name of ['bridge.spec.cjs', 'real-readers.spec.cjs', 'helpers.cjs']) {
    outputs.set('test/treasury-compat/' + name, fs.readFileSync(path.join(HERE, 'tests', name), 'utf8'));
  }
  outputs.set('test/treasuryCompatRead.test.ts', fs.readFileSync(path.join(HERE, 'templates', 'treasuryCompatRead.test.ts'), 'utf8'));
  outputs.set('docs/treasury-legacy-read-bridge.md', fs.readFileSync(path.join(HERE, 'templates', 'candidate-doc.md'), 'utf8'));
  const manifest = { ...PLAN, compiler: sourceTs.version, preparedNotDeployed: true, sourceManifest,
    outputs: [...outputs].map(([file, content]) => ({ file, bytes: Buffer.byteLength(content), sha256: sha256(content), gitBlob: blob(content) })) };
  outputs.set('docs/treasury-compat-source-manifest.json', JSON.stringify(manifest, null, 2) + '\n');
  for (const [file] of outputs) {
    const dest = path.join(targetRepo, file);
    if (!['src/main.ts', 'src/main.test.ts'].includes(file) && fs.existsSync(dest)) throw new Error(`new target already exists: ${file}`);
    let parent = path.dirname(dest);
    while (parent !== targetRepo) {
      if (fs.existsSync(parent) && fs.lstatSync(parent).isSymbolicLink()) throw new Error(`symlink parent not allowed: ${file}`);
      parent = path.dirname(parent);
    }
    if (fs.existsSync(dest) && fs.lstatSync(dest).isSymbolicLink()) throw new Error(`symlink target not allowed: ${file}`);
  }
  if (!apply) return { status: 'CHECKED_NOT_APPLIED', files: outputs.size, sourceModules: sourceManifest.length, generatedBytes: Buffer.byteLength(generated) };
  const changed = [];
  try {
    for (const [file, text] of outputs) {
      const dest = path.join(targetRepo, file);
      const before = fs.existsSync(dest) ? fs.readFileSync(dest) : null;
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      changed.push({ dest, before }); fs.writeFileSync(dest, text, 'utf8');
    }
    for (const [file, text] of outputs) if (sha256(fs.readFileSync(path.join(targetRepo, file))) !== sha256(text)) throw new Error(`post-write mismatch: ${file}`);
  } catch (e) {
    for (const { dest, before } of changed.reverse()) { if (before === null) { if (fs.existsSync(dest)) fs.unlinkSync(dest); } else fs.writeFileSync(dest, before); }
    throw e;
  }
  return { status: 'CANDIDATE_WRITTEN_NOT_COMMITTED_NOT_DEPLOYED', files: outputs.size,
    sourceModules: sourceManifest.length, generatedBytes: Buffer.byteLength(generated) };
}
if (require.main === module) {
  try {
    const args = process.argv.slice(2); const values = {};
    for (let i = 0; i < args.length; i++) {
      if (args[i] === '--apply') values.apply = true;
      else if (args[i] === '--check') values.check = true;
      else if (['--source-repo', '--target-repo'].includes(args[i]) && args[i + 1]) { values[args[i]] = args[++i]; }
      else throw new Error('usage: assemble.cjs --source-repo DEV --target-repo OLD_WORKTREE (--check | --apply)');
    }
    if (!values['--source-repo'] || !values['--target-repo'] || (!!values.apply === !!values.check)) throw new Error('explicit check/apply and both worktrees required');
    console.log(JSON.stringify(execute(values['--source-repo'], values['--target-repo'], !!values.apply), null, 2));
  } catch (e) { console.error('ASSEMBLY_REFUSED: ' + e.message); process.exitCode = 1; }
}
module.exports = { compileClosure, patchOldMain, patchOldMainTest, resolveDependency, replaceOnce, blob, sha256, PLAN, execute };
