'use strict';
const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const C=require('../tools/common.cjs'),A=require('../tools/adapt-executor.cjs'),S=require('../tools/source.cjs'),M=require('../tools/analyze.cjs'),F=require('./executor-fixtures.cjs');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'fc1-test-'));
function rawModule(){const m={exports:{}},mock={...C,POLICY:C.P,bytes:C.read};const ctx=vm.createContext({module:m,exports:m.exports,Buffer,require:n=>n==='../runtime/common.cjs'?mock:n==='./repository.cjs'?{git:C.git}:require(n)});new vm.Script(fs.readFileSync(path.join(C.ROOT,'implementation/raw-whitespace.cjs'),'utf8')).runInContext(ctx);return m.exports;}
function repo(fn){const root=tmp();try{C.git(root,['init']);C.git(root,['config','user.name','FC1 Fixture']);C.git(root,['config','user.email','fixture@example.invalid']);fs.writeFileSync(path.join(root,'base.txt'),'base\n');C.git(root,['add','.']);C.git(root,['commit','-m','base']);const e=path.join(root,'evidence');fs.mkdirSync(e);return fn(root,e);}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('FC1 authentic baseline collector sample parser is byte-pinned',()=>{const b=C.read(path.join(C.ROOT,'references/samples.original.cjs'));assert.equal(C.blob(b),'c691674e066d6b3dabbd6c9168215a2985e4ad13');});
test('FC1 task boundary parser remains byte-exact',()=>{assert.equal(C.blob(C.read(path.join(C.ROOT,'references/task-trace.original.cjs'))),'ddb5545ea7297eb299a318a78341ac1d11d05cff');});
test('FC1 full R1 Core fixture remains unchanged',()=>assert.equal(C.sha(C.read(path.join(C.ROOT,'fixtures/core-R1.expected.ts.txt'))),C.P.coreSha256));
test('FC1 historical runtime fixture is the real pre-FC1 Git blob',()=>assert.equal(C.blob(C.read(path.join(C.ROOT,'fixtures/runtime-before-full-cost-fc1.ts.txt'))),C.P.runtimeBeforeBlob));
test('FC1 patch rejects missing or duplicated anchors',()=>{assert.throws(()=>A.once('xx','y','z'));assert.throws(()=>A.once('yy','y','z'));assert.equal(A.once('ayb','y','z'),'azb');});
test('FC1 sample adaptation is not reapplicable',()=>{const b=C.read(path.join(C.ROOT,'references/samples.original.cjs')).toString();assert.throws(()=>A.samples(A.samples(b)));});
test('FC1 generator metadata update is bound to exact old runtime identity',()=>{const s="'src/runtime/treasuryCompatRuntime.ts': { bytes: 956, sha256: '7250f9554baca9c2431d109f14c45ebece7df04de95e79e53146f9996dfffe6c', gitBlob: '13e8e356784da1c606e9c1cc8fccdaaa8d436b0c' }";const b=C.read(path.join(C.ROOT,'implementation/treasuryCompatRuntime.ts')),out=S.generator(s,b);assert.ok(out.includes(C.sha(b)));assert.throws(()=>S.generator(s.replace('956','955'),b));});
test('FC1 native whitespace proof preserves a raw TAP trailing-space failure',()=>repo((r,e)=>{const K=rawModule(),b=Buffer.from('not ok\n  error: |\n    expected  \n');fs.writeFileSync(path.join(e,'failure.stdout'),b);K.createProof(e);C.git(r,['add','--','evidence']);assert.throws(()=>C.git(r,['diff','--cached','--check']));const result=K.checkStaged(r,'evidence');assert.equal(result.exceptions.length,1);assert.ok(C.git(r,['show',':evidence/failure.stdout']).equals(b));}));
test('FC1 raw exceptions do not exempt a source file',()=>repo((r,e)=>{const K=rawModule();fs.writeFileSync(path.join(e,'raw.tap'),'raw  \n');fs.writeFileSync(path.join(e,'source.cjs'),'const x=1;  \n');K.createProof(e);C.git(r,['add','--','evidence']);assert.throws(()=>K.checkStaged(r,'evidence'));}));
test('FC1 staged blob changes invalidate the SHA-bound raw exception',()=>repo((r,e)=>{const K=rawModule();fs.writeFileSync(path.join(e,'raw.stdout'),'original  \n');K.createProof(e);fs.writeFileSync(path.join(e,'raw.stdout'),'modified  \n');C.git(r,['add','--','evidence']);assert.throws(()=>K.checkStaged(r,'evidence'),/RAW_EXCEPTION_BYTES_CHANGED/);}));
test('FC1 whitespace check still catches an unlisted raw log',()=>repo((r,e)=>{const K=rawModule();K.createProof(e);fs.writeFileSync(path.join(e,'late.stdout'),'late  \n');C.git(r,['add','--','evidence']);assert.throws(()=>K.checkStaged(r,'evidence'));}));
test('FC1 evidence-scope check rejects staged unrelated content',()=>repo((r,e)=>{const K=rawModule();K.createProof(e);fs.writeFileSync(path.join(r,'unrelated.txt'),'x\n');C.git(r,['add','.']);assert.throws(()=>K.checkStaged(r,'evidence'),/EVIDENCE_SCOPE_CHANGED/);}));
test('FC1 proof cannot relabel source code as raw output',()=>repo((r,e)=>{const K=rawModule(),b=Buffer.from('x  \n');fs.writeFileSync(path.join(e,'bad.cjs'),b);C.durable(path.join(e,K.PROOF),{kind:'raw-log-preservation/v1',files:[{path:'bad.cjs',bytes:b.length,sha256:C.sha(b),gitBlob:C.blob(b),findings:[{line:1,type:'trailing-whitespace'}]}]});C.git(r,['add','.']);assert.throws(()=>K.checkStaged(r,'evidence'),/RAW_EXCEPTION_PATH_INVALID/);}));
test('FC1 normal native commit keeps exact raw bytes and proof in the committed tree',()=>repo((r,e)=>{const K=rawModule(),b=Buffer.from('not ok  \n');fs.writeFileSync(path.join(e,'raw.tap'),b);K.createProof(e);C.git(r,['add','.']);K.checkStaged(r,'evidence');const tree=C.text(r,['write-tree']);C.git(r,['commit','-m','raw evidence']);assert.equal(C.tree(r),tree);assert.ok(C.git(r,['show','HEAD:evidence/raw.tap']).equals(b));}));
test('FC1 authorization cannot be refreshed by an output directory change',()=>repo((r)=>{S.authorizationUnused(r);const f=path.join(r,'.git/treasury-experiments',C.P.authorizationId+'.json');C.durable(f,{consumed:true});assert.throws(()=>S.authorizationUnused(r),/FC1_AUTHORIZATION_ALREADY_CONSUMED/);}));
test('FC1 package integrity rejects a changed payload',()=>{const root=tmp();try{fs.writeFileSync(path.join(root,'x.txt'),'x');C.seal(root);C.verify(root);fs.writeFileSync(path.join(root,'x.txt'),'y');assert.throws(()=>C.verify(root),/PACKAGE_BYTES_CHANGED/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
function analysisFixture(){const {W}=F.load(),reports=[],costs=[];for(let i=0;i<4;i++){const r=F.report(i,reports.at(-1)),c=F.cost(r,costs.at(-1));reports.push(r);costs.push(c);}const ticks=reports.map(x=>x.tick);return{W,reports,costs,v:{status:'CPU_DIAGNOSTIC_CAPTURE_VERIFIED',captureVerified:true,issues:[],rawReports:4,acceptedReports:4,duplicates:0,expectedTicks:ticks,acceptedTicks:ticks,closure:'RESTORED_BYTES_AND_RUNTIME_VERIFIED',sourceOff:true,uploadOutcomeResolved:true}};}
test('FC1 result above 2 is full measured completion without a performance grade',()=>{const{W,reports,costs,v}=analysisFixture(),a=M.analyze(v,reports,costs,W.complete);assert.equal(a.milestone,'FULL_PATH_COST_MEASURED');assert.equal(a.performanceTargetCpu,null);assert.equal(a.correctAndCompleteSamples,4);assert.equal(a.mainReportTailsObserved.length,4);assert.equal(a.finalReceiptOwnTailObserved,false);assert.equal(a.knownReceiptInclusiveCosts.length,3);});
test('FC1 missing receipts cannot produce a full cost verdict',()=>{const{W,reports,costs,v}=analysisFixture();assert.equal(M.analyze(v,reports,costs.slice(0,3),W.complete).milestone,'COST_MEASUREMENT_INCONCLUSIVE');});
test('FC1 restoration is an independent result, not implied by good samples',()=>{const{W,reports,costs,v}=analysisFixture();v.closure='ONLINE_CLOSE_UNCONFIRMED';assert.equal(M.analyze(v,reports,costs,W.complete).milestone,'RECOVERY_NOT_CLOSED');});
test('FC1 no-deployment state has no fabricated CPU conclusion',()=>{const{W}=F.load(),a=M.analyze({status:'NOT_DEPLOYED'},[],[],W.complete);assert.equal(a.milestone,'NOT_DEPLOYED_NO_COST_CONCLUSION');assert.equal(a.costSummary,undefined);});
test('FC1 native headroom and full original main tail are independent of legacy Memory mismatch',()=>{const{W,reports,costs,v}=analysisFixture();reports[0].endpoints[0].legacyProjection={status:'mismatch',mismatches:['terminalEnergy']};const a=M.analyze(v,reports,costs,W.complete);assert.equal(a.milestone,'FULL_PATH_COST_MEASURED');assert.equal(a.legacyProjectionMismatches.length,1);assert.ok(a.costSummary.mean>2);});
test('FC1 fixed scopes preserve all six planned source paths and do not change Core/preview',()=>{assert.equal(C.P.sourcePaths.length,6);assert.ok(!C.P.sourcePaths.includes(C.P.corePath));assert.ok(!C.P.sourcePaths.includes(C.P.previewPath));});
