'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const H=require('./selection-fixture.cjs');
const read=(f,n)=>f.C.json(path.join(f.dir,'window-selection',n));
function rehash(f){const root=path.join(f.dir,'window-selection'),r=read(f,'result.json');r.files={};for(const n of f.C.list(root).filter(n=>n!=='result.json')){const b=f.C.bytes(path.join(root,n));r.files[n]={bytes:b.length,sha256:f.C.sha(b)};}fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(r,null,2)+'\n');}
function edit(f,n,fn){const p=path.join(f.dir,'window-selection',n),j=f.C.json(p);fn(j);fs.writeFileSync(p,JSON.stringify(j,null,2)+'\n');}
function zero(f){assert.equal(f.writes,0);for(const n of ['binding-intent.json','binding.json','session.json','candidate-attempt.json','restore-attempt.json'])assert.equal(f.C.optional(f.dir,n),null);}

test('a complete read-only selector waits and remeasures before choosing a phase with sufficient slack',async()=>{const f=H.fixture();try{const s=await f.run(),v=f.selector.verifySelection(f.dir);assert.equal(v.outcome,'WINDOW_SELECTED');assert.equal(v.rounds,2);assert.ok(v.rejectedDecisions>0);assert.ok(s.plan.slackMs>=180000);assert.equal(s.profile.endTick-s.profile.startTick,300);assert.equal(s.profile.startTick%100,0);assert.ok(s.profile.startTick-s.currentTick>=150);assert.ok(f.c.now<1800000);zero(f);}finally{f.close();}});
test('all rejected round files remain intact after selection; only selected calibration is promoted',async()=>{const f=H.fixture();try{await f.run();assert.equal(read(f,'round-01/result.json').selectedOrdinal,null);assert.ok(f.C.jsonl(path.join(f.dir,'window-selection/round-01/decisions.jsonl')).length>1);assert.equal(f.C.jsonl(path.join(f.dir,'time-observations.jsonl')).filter(x=>x.purpose==='rate-measurement').length,7);zero(f);}finally{f.close();}});
test('an immediately admissible proposal is used without exploring later better proposals',async()=>{const f=H.fixture({rateMs:4000,startTick:73876200});try{const s=await f.run();assert.equal(s.round,1);assert.equal(read(f,'result.json').reason,'FIRST_ADMISSIBLE_REVALIDATED_PROPOSAL');assert.equal(f.selector.verifySelection(f.dir).decisions,2);zero(f);}finally{f.close();}});
test('a selected proposal receives a new canonical and room revalidation followed by a fresh time read',async()=>{const f=H.fixture({rateMs:4000});try{const s=await f.run();assert.deepEqual(f.calls.slice(-6).map(x=>x.name),['me','branches','code','branches','overview','time']);const ids=f.C.jsonl(path.join(f.dir,'window-selection/round-01/identities.jsonl'));assert.equal(ids.length,1);assert.equal(ids[0].id,s.identityId);zero(f);}finally{f.close();}});
test('persistent slow progress is bounded by the single total read-only deadline, not six new deadlines',async()=>{const f=H.fixture({rateMs:9000});try{await assert.rejects(f.run(),/WINDOW_SELECTION_EXHAUSTED/);const r=read(f,'result.json');assert.equal(r.outcome,'WINDOW_SELECTION_EXHAUSTED');assert.ok(r.elapsedMs<=f.p.selection.maxMs);assert.ok(r.rounds<=6);assert.equal(f.selector.verifySelection(f.dir).outcome,'WINDOW_SELECTION_EXHAUSTED');zero(f);}finally{f.close();}});
test('six unsuccessful short rounds stop at round cap without an unbounded seventh round',async()=>{const f=H.fixture({rateMs:9000,policy:{selection:{probeMaxMs:1}}});try{await assert.rejects(f.run(),/WINDOW_SELECTION_EXHAUSTED/);const r=read(f,'result.json');assert.equal(r.rounds,6);assert.equal(r.reason,'MAXIMUM_ROUNDS');assert.equal(fs.existsSync(path.join(f.dir,'window-selection/round-07')),false);zero(f);}finally{f.close();}});
test('a halted shard cannot get an invented rate or consume a write quota',async()=>{const f=H.fixture({rateMs:1e9});try{await assert.rejects(f.run(),/WINDOW_SELECTION_EXHAUSTED/);assert.equal(read(f,'result.json').elapsedMs,1800000);assert.equal(read(f,'result.json').rounds,6);assert.equal(f.C.optional(f.dir,'timing-measurement.json'),null);zero(f);}finally{f.close();}});
test('transient game-time errors are preserved and may recover during read-only selection',async()=>{let failures=0;const f=H.fixture({hook:({call,C})=>{if(call.name==='time'&&call.index===3){failures++;throw new C.Failure('HTTP_TRANSPORT_ERROR');}}});try{await f.run();const v=f.selector.verifySelection(f.dir);assert.equal(failures,1);assert.equal(v.failedTimeReads,1);zero(f);}finally{f.close();}});
test('invalid game-time response fails closed without another round or any write',async()=>{const f=H.fixture();f.api.time=async()=>({ok:1,time:-1});try{await assert.rejects(f.run(),/GAME_TICK_INVALID/);assert.equal(read(f,'result.json').outcome,'WINDOW_SELECTION_FAILED');assert.equal(read(f,'result.json').rounds,1);zero(f);}finally{f.close();}});
test('a regression inside a calibration is fatal',async()=>{const f=H.fixture();let n=0;f.api.time=async()=>({ok:1,time:++n===3?1:100+n});try{await assert.rejects(f.run(),/GAME_TICK_REGRESSED/);zero(f);}finally{f.close();}});
test('a regression across different calibration rounds is not hidden by separate files',async()=>{let rounds=0;const f=H.fixture({rateMs:9000,policy:{selection:{probeMaxMs:1}},hook:({call,c})=>{if(call.name==='time'&&call.at>180000&&rounds++===0)c.offset+=0;}});const base=f.api.time;let decreased=false;f.api.time=async ms=>{const r=await base(ms);if(fs.existsSync(path.join(f.dir,'window-selection/round-02'))){r.time-=1000;decreased=true;}return r;};try{await assert.rejects(f.run(),/GAME_TICK_REGRESSED/);assert.equal(decreased,true);zero(f);}finally{f.close();}});
test('wall-clock discontinuity is not treated as a transient network error',async()=>{const f=H.fixture({hook:({call,c})=>{if(call.index===4)c.offset+=10000;}});try{await assert.rejects(f.run(),/CLOCK_DISCONTINUITY/);assert.equal(read(f,'result.json').outcome,'WINDOW_SELECTION_FAILED');zero(f);}finally{f.close();}});
test('a backward monotonic clock is rejected',async()=>{const f=H.fixture({hook:({call,c})=>{if(call.index===4)c.now-=50000;}});try{await assert.rejects(f.run(),/TIME_READ_DEADLINE|CLOCK_OR_ORDER|CLOCK_DISCONTINUITY/);zero(f);}finally{f.close();}});
test('third-party live modules discovered after waiting stop selection instead of becoming a new backup',async()=>{const f=H.fixture({hook:({call,setCurrent})=>{if(call.name==='code')setCurrent({main:'third-party'});}});try{await assert.rejects(f.run(),/BUILD_IDENTITY_INVALID|LIVE_BASELINE_DRIFT_UNRESOLVED/);assert.equal(read(f,'result.json').outcome,'WINDOW_SELECTION_FAILED');zero(f);}finally{f.close();}});
test('account mismatch during the new identity recheck is fatal',async()=>{const f=H.fixture();f.api.me=async()=>({ok:1,_id:'foreign',username:'foreign'});try{await assert.rejects(f.run(),/ACCOUNT_MISMATCH/);zero(f);}finally{f.close();}});
test('activeWorld change during waiting remains fatal',async()=>{const f=H.fixture();f.api.branches=async()=>({ok:1,list:[{branch:'third',activeWorld:true}]});try{await assert.rejects(f.run(),/ACTIVE_BRANCH_CHANGED/);zero(f);}finally{f.close();}});
test('room ownership loss during waiting remains fatal',async()=>{const f=H.fixture();f.api.overview=async()=>({ok:1,shards:{shard1:{rooms:[]}}});try{await assert.rejects(f.run(),/ROOM_OWNERSHIP_INVALID/);zero(f);}finally{f.close();}});
test('transient identity recheck failure is recorded then reconsidered before any binding',async()=>{let n=0;const f=H.fixture();const fn=f.api.me;f.api.me=async ms=>{if(n++===0)throw new f.C.Failure('HTTP_TRANSPORT_ERROR');return fn(ms);};try{await f.run();assert.ok(n>=2);const records=fs.readdirSync(path.join(f.dir,'window-selection')).filter(n=>n.startsWith('round-')).flatMap(n=>f.C.jsonl(path.join(f.dir,'window-selection',n,'identities.jsonl')));assert.equal(records.filter(x=>x.status==='IDENTITY_READ_FAILED').length,1);assert.equal(f.selector.verifySelection(f.dir).outcome,'WINDOW_SELECTED');zero(f);}finally{f.close();}});
test('measurement deadline is clipped to the selection deadline even mid-request',async()=>{const f=H.fixture({policy:{selection:{maxMs:130000}}});try{await assert.rejects(f.run(),/WINDOW_SELECTION_EXHAUSTED/);assert.ok(f.c.now<=130000);assert.ok(f.calls.at(-1).ms<=f.p.timing.requestMs);zero(f);}finally{f.close();}});
test('existing ON intent forbids restarting selection',async()=>{const f=H.fixture();try{f.C.durable(path.join(f.dir,'binding-intent.json'),{});await assert.rejects(f.run(),/AFTER_BINDING/);assert.equal(f.calls.length,0);assert.equal(f.writes,0);}finally{f.close();}});
test('existing candidate marker forbids restarting selection',async()=>{const f=H.fixture();try{f.C.durable(path.join(f.dir,'candidate-attempt.json'),{});await assert.rejects(f.run(),/AFTER_BINDING/);assert.equal(f.calls.length,0);assert.equal(f.writes,0);}finally{f.close();}});
test('same directory cannot refresh a consumed read-only selection run',async()=>{const f=H.fixture();try{await f.run();const n=f.calls.length;await assert.rejects(f.run());assert.equal(f.calls.length,n);zero(f);}finally{f.close();}});
test('removing a failed calibration directory is detected even if the outer hashes are recomputed',async()=>{const f=H.fixture();try{await f.run();fs.rmSync(path.join(f.dir,'window-selection/round-01'),{recursive:true});rehash(f);assert.throws(()=>f.selector.verifySelection(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('tampering with an unsuccessful decision rate is detected by recomputation not merely hashes',async()=>{const f=H.fixture();try{await f.run();const p=path.join(f.dir,'window-selection/round-01/decisions.jsonl'),ds=f.C.jsonl(p);ds[0].plan.conservativeMsPerTick=1;fs.writeFileSync(p,ds.map(x=>JSON.stringify(x)).join('\n')+'\n');rehash(f);assert.throws(()=>f.selector.verifySelection(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('altered selection limits in the persisted start record are rejected',async()=>{const f=H.fixture();try{await f.run();edit(f,'start.json',x=>x.maxMs*=2);rehash(f);assert.throws(()=>f.selector.verifySelection(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('forged canonical recheck digest is rejected even after rehashing',async()=>{const f=H.fixture();try{const s=await f.run(),p=path.join(f.dir,'window-selection',`round-0${s.round}`,'identities.jsonl'),rows=f.C.jsonl(p);rows.at(-1).digest.hash='0'.repeat(64);fs.writeFileSync(p,rows.map(x=>JSON.stringify(x)).join('\n')+'\n');rehash(f);assert.throws(()=>f.selector.verifySelected(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('a mismatching promoted measurement cannot be used for upload',async()=>{const f=H.fixture();try{await f.run();const p=path.join(f.dir,'timing-measurement.json'),x=f.C.json(p);x.conservativeMsPerTick=1;fs.writeFileSync(p,JSON.stringify(x));assert.throws(()=>f.selector.verifySelected(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('duplicating the promoted time read cannot create a valid proof',async()=>{const f=H.fixture();try{await f.run();const rs=f.C.jsonl(path.join(f.dir,'time-observations.jsonl'));f.C.append(path.join(f.dir,'time-observations.jsonl'),rs.at(-1));assert.throws(()=>f.selector.verifySelected(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('time plan remains four points, two CPU and fixed 75 minutes after selection',async()=>{const f=H.fixture();try{const s=await f.run();assert.equal(s.profile.maxSampleCpu,2);assert.equal(s.profile.reserveCpu,5);assert.equal(s.profile.intervalTicks,100);assert.equal(s.profile.endTick,s.profile.startTick+300);assert.equal(s.plan.exposureLimitMs,4500000);assert.equal(s.plan.noAutomaticExtension,true);zero(f);}finally{f.close();}});
test('an uncommitted plan may become admissible solely as alignment lead shortens; its sampling interval never changes',()=>{const R=require('../tools/repository.cjs'),review=require('../references/prior-XV-independent-review.json');const prior=review.timeRecomputation.binding;assert.equal(prior.requiredMs,4899346);assert.equal(prior.conservativeMsPerTick,8518);const a=R.profileFor(73876253),b=R.profileFor(73876330);assert.equal(a.startTick,b.startTick);assert.equal((b.endTick-73876330)*8518+240000,4243460);assert.ok(4500000-4243460>=180000);assert.equal(b.endTick-b.startTick,300);});
test('crossing the alignment boundary is allowed to reject a previously admissible proposal, never silently moving a bound one',()=>{const R=require('../tools/repository.cjs');const a=R.profileFor(73876350),b=R.profileFor(73876351);assert.equal(a.startTick,73876500);assert.equal(b.startTick,73876600);assert.ok((b.endTick-73876351)*8518+240000>4500000);});
test('an exact previous failed estimate is not described as actual elapsed deployment time',()=>{const review=require('../references/prior-XV-independent-review.json');assert.equal(review.outcome?.status??review.timeRecomputation.binding.status,'TIME_BUDGET_INSUFFICIENT');assert.equal(review.timeRecomputation.binding.requiredMs,547*8518+240000);assert.equal(review.timeRecomputation.writeBoundaries,0);});
test('the additional slack is stricter than merely fitting under the exposure cap',()=>{const T=require('../runtime/time-budget.cjs'),R=require('../tools/repository.cjs'),C=require('../runtime/common.cjs');const {seed}=require('./time-helper.cjs'),d=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'selector-margin-'));try{const f=seed(d),m=structuredClone(f.measurement);m.conservativeMsPerTick=9300;const q=T.plan(m,f.binding,R.profileFor(50),'binding');assert.ok(q.requiredMs<=4500000);assert.equal(q.status,'TIME_BUDGET_MARGIN_INSUFFICIENT');assert.ok(q.slackMs<180000);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('real previous eleven time reads and their measurement/plan retain exact Git blob identities',()=>{const C=require('../runtime/common.cjs'),p=path.join(__dirname,'../references'),m=require('../references/prior-XV-timing-identities.json');for(const[n,x]of Object.entries(m.files)){const b=fs.readFileSync(path.join(p,n));assert.equal(C.blob(b),x.gitBlob);assert.equal(C.sha(b),x.sha256);assert.equal(b.length,x.bytes);}});
test('the new estimator independently reproduces the real XV rejection without weakening its bound',()=>{const C=require('../runtime/common.cjs'),T=require('../runtime/time-budget.cjs'),R=require('../tools/repository.cjs');const rows=C.jsonl(path.join(__dirname,'../references/prior-XV-time-observations.jsonl')).map(r=>({...r,runId:C.POLICY.parentRunId}));const m=T.measurement(rows.filter(r=>r.purpose==='rate-measurement'));const old=require('../references/prior-XV-timing-measurement.json');assert.equal(m.worstObservedMsPerTick,old.worstObservedMsPerTick);assert.equal(m.conservativeMsPerTick,8518);const q=T.plan(m,rows.at(-1),R.profileFor(rows.at(-1).tick),'binding');assert.equal(q.requiredMs,4899346);assert.equal(q.status,'TIME_BUDGET_INSUFFICIENT');assert.equal(q.remainingTicks,547);});
test('forged shortened total duration does not make prematurely exhausted selection verified',async()=>{const f=H.fixture({rateMs:9000});try{await assert.rejects(f.run(),/WINDOW_SELECTION_EXHAUSTED/);edit(f,'result.json',r=>{r.elapsedMs=1000;r.rounds=1;});assert.throws(()=>f.selector.verifySelection(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('stored selection cannot claim a larger authorized round count',async()=>{const f=H.fixture();try{await f.run();edit(f,'result.json',r=>r.maximumRounds=600);assert.throws(()=>f.selector.verifySelection(f.dir),/EVIDENCE_INVALID/);}finally{f.close();}});
test('identity recheck can cross an alignment boundary and reject that proposal without binding it',async()=>{const f=H.fixture({startTick:73876320});try{await f.run();const ds=fs.readdirSync(path.join(f.dir,'window-selection')).filter(n=>n.startsWith('round-')).flatMap(n=>f.C.jsonl(path.join(f.dir,'window-selection',n,'decisions.jsonl')));assert.ok(ds.some(d=>d.stage==='after_identity'&&d.plan.status==='TIME_BUDGET_INSUFFICIENT'));assert.equal(f.selector.verifySelection(f.dir).outcome,'WINDOW_SELECTED');zero(f);}finally{f.close();}});
