'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../runtime/common.cjs'),U=require('../tools/util.cjs'),F=require('./fixture.cjs');
function setup(){const root=F.root(),repo=path.join(root,'repo');F.initGit(repo);const run=path.join(repo,'evidence/run');fs.mkdirSync(run,{recursive:true});
 const s=F.session(),special={'public-session.json':JSON.stringify(s),'console.jsonl':F.firstFrame(s),'upload-attempt.json':'{}\n','upload-result.json':'{}\n'};
 for(const [n,b]of Object.entries(special))fs.writeFileSync(path.join(run,n),b);for(let i=0;i<25;i++)fs.writeFileSync(path.join(run,`entry-${i}.json`),'{}\n');
 F.git(repo,['add','.']);F.git(repo,['commit','-qm','fixture']);const refactor=F.git(repo,['rev-parse','HEAD']),runTree=F.git(repo,['rev-parse','HEAD:evidence/run']);
 const p={refactor,sourceRoot:'evidence',runTree,publicBlob:C.blob(C.bytes(path.join(run,'public-session.json'))),consoleBlob:C.blob(C.bytes(path.join(run,'console.jsonl'))),uploadAttemptBlob:C.blob(C.bytes(path.join(run,'upload-attempt.json'))),uploadResultBlob:C.blob(C.bytes(path.join(run,'upload-result.json')))};
 return {root,repo,p,out:path.join(root,'source'),clean:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('materialization reconstructs an actual pinned Git tree with exact bytes',()=>{const x=setup();try{assert.equal(U.materialize(x.repo,x.out,x.p).files,29);assert.equal(U.verifySource(x.out,x.p).runTree,x.p.runTree);}finally{x.clean();}});
test('materializer rejects wrong tree before producing output',()=>{const x=setup();try{assert.throws(()=>U.materialize(x.repo,x.out,{...x.p,runTree:'0'.repeat(40)}),{code:'SOURCE_TREE_MISMATCH'});assert.equal(fs.existsSync(x.out),false);}finally{x.clean();}});
test('source byte mutation is detected',()=>{const x=setup();try{U.materialize(x.repo,x.out,x.p);fs.appendFileSync(path.join(x.out,'run/entry-3.json'),' ');assert.throws(()=>U.verifySource(x.out,x.p),{code:'SOURCE_BYTES_CHANGED'});}finally{x.clean();}});
test('changing both nonanchor source bytes and manifest cannot bypass pinned tree identity',()=>{const x=setup();try{U.materialize(x.repo,x.out,x.p);const f=path.join(x.out,'run/entry-4.json');fs.writeFileSync(f,'changed');const m=C.json(path.join(x.out,'MANIFEST.json')),e=m.files.find(f=>f.name==='entry-4.json'),b=C.bytes(f);Object.assign(e,{bytes:b.length,sha256:C.sha256(b),blob:C.blob(b)});fs.writeFileSync(path.join(x.out,'MANIFEST.json'),JSON.stringify(m));assert.throws(()=>U.verifySource(x.out,x.p),{code:'SOURCE_MANIFEST_TREE_MISMATCH'});}finally{x.clean();}});
test('extra source files are not silently ignored',()=>{const x=setup();try{U.materialize(x.repo,x.out,x.p);fs.writeFileSync(path.join(x.out,'run','extra.json'),'{}');assert.throws(()=>U.verifySource(x.out,x.p),{code:'SOURCE_FILE_SET_CHANGED'});}finally{x.clean();}});
test('tree parser rejects traversal or unsupported file modes',()=>{assert.throws(()=>U.parseTree(Buffer.from('120000 blob '+'a'.repeat(40)+'\tfile\0')),{code:'SOURCE_TREE_INVALID'});assert.throws(()=>U.parseTree(Buffer.from('100644 blob '+'a'.repeat(40)+'\t../file\0')),{code:'SOURCE_TREE_INVALID'});});
