'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const F=require('./fixture.cjs'),O=require('../runtime/closure-observer.cjs'),V=require('../runtime/verify-closure.cjs'),C=require('../runtime/common.cjs');
async function run(mode='healthy'){const out=F.root(),closureId='abc',parentRunId='parent';const r=await O.observeRuntime({out,closureId,parentRunId,secret:F.secret,
 WebSocketClass:F.wsClass(mode),durationMs:250,startupMs:1500,silenceMs:1000,pollMs:5});return {out,r,closureId,parentRunId};}
test('new recovery stream independently proves runtime after old collector has exited',async()=>{const t=await run();try{assert.equal(t.r.status,'RECOVERY_RUNTIME_COLLECTED');assert.equal(V.verifyObserver(t.out,t.closureId,t.parentRunId,{runtimeMs:250,silenceMs:1000}).status,'RECOVERY_RUNTIME_INDEPENDENTLY_VERIFIED');}finally{fs.rmSync(t.out,{recursive:true,force:true});}});
for(const mode of ['no-console','no-cpu','wrong-shard','zero-cpu','bridge','close','reauth'])test('observer fails safely for '+mode,async()=>{const t=await run(mode);try{assert.equal(t.r.status,'RECOVERY_RUNTIME_UNCONFIRMED');assert.throws(()=>V.verifyObserver(t.out,t.closureId,t.parentRunId,{runtimeMs:250,silenceMs:1000}));}finally{fs.rmSync(t.out,{recursive:true,force:true});}});
test('auth echoes and token-bearing console messages are not persisted as credentials',async()=>{const t=await run('redact');try{for(const n of C.list(t.out))assert.ok(!C.bytes(path.join(t.out,n)).toString().includes(F.secret.token));}finally{fs.rmSync(t.out,{recursive:true,force:true});}});
test('independent observer verifier rejects duplicate footer',async()=>{const t=await run();try{const f=path.join(t.out,'runtime-console.jsonl'),rows=V.jsonl(f);fs.appendFileSync(f,JSON.stringify(rows.at(-1))+'\n');assert.throws(()=>V.verifyObserver(t.out,t.closureId,t.parentRunId,{runtimeMs:250,silenceMs:1000}));}finally{fs.rmSync(t.out,{recursive:true,force:true});}});
test('independent observer verifier rejects PID substitution',async()=>{const t=await run();try{const f=path.join(t.out,'runtime-console.jsonl'),rows=V.jsonl(f);rows[2].pid++;fs.writeFileSync(f,rows.map(x=>JSON.stringify(x)).join('\n')+'\n');assert.throws(()=>V.verifyObserver(t.out,t.closureId,t.parentRunId,{runtimeMs:250,silenceMs:1000}));}finally{fs.rmSync(t.out,{recursive:true,force:true});}});
