'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const {createRequire}=require('node:module');
const U=require('./util.cjs'),B=require('./build.cjs'),X=require('./source.cjs'),{closeSource}=require('./close-source.cjs');
const C=require('../runtime/common.cjs'),P=require('../runtime/protocol.cjs'),K=require('../runtime/policy.cjs'),S=require('../runtime/store.cjs'),A=require('../runtime/actions.cjs'),Q=require('../runtime/readiness.cjs'),L=require('../runtime/live-baseline.cjs');
const {client}=require('../runtime/transport.cjs'),RR=require('../runtime/read-retry.cjs'),{inspectProfile,validateProfileLead}=require('../runtime/check-profile.cjs');
function publicReadiness(r){return{status:r.status,authorization:{...r.authorization,modules:undefined},lastTick:r.lastTick,rooms:r.rooms,stableReads:r.stableReads,attempts:r.attempts,elapsedMs:r.elapsedMs,verifiedAtMs:r.verifiedAtMs};}
async function prepare(o){
 const compat=path.resolve(o.compat),refactor=path.resolve(o.refactor),work=path.resolve(o.work);const source=X.verifyHead(compat);U.exactHead(refactor,K.REFACTOR,'refactor/empire-treasury-rearchitecture');
 if(U.remoteHead(refactor,'refactor/empire-treasury-rearchitecture')!==K.REFACTOR||U.remoteHead(compat,'compat/treasury-read-bridge-i')!==K.COMPAT)C.fail('REMOTE_BASELINE_CHANGED');
 U.outside(work,compat);U.outside(work,refactor);U.outside(U.ROOT,compat);U.outside(U.ROOT,refactor);
 const offline=C.readJson(path.join(o.offline,'result.json'));if(offline.sourceHead!==source.head||offline.status!=='ENVELOPE_XII_RETRY_OFFLINE_VERIFIED'||offline.repositoryNodeTests!==290||offline.sourceManifestOutputValidation!=='all-listed-outputs'||offline.packageFingerprint!==C.sha256(fs.readFileSync(path.join(U.ROOT,'INTEGRITY.json'))))C.fail('OFFLINE_BASELINE_GATE_MISSING');
 const selfTests=C.readJson(path.join(o.tests,'summary.json'));if(selfTests.status!=='ENVELOPE_XII_RETRY_PACKAGE_TESTS_VERIFIED'||selfTests.tests!==require('../references/test-contract.json').count||selfTests.passed!==selfTests.tests||['failed','skipped','todo','cancelled'].some(k=>selfTests[k]!==0)||selfTests.packageFingerprint!==C.sha256(fs.readFileSync(path.join(U.ROOT,'INTEGRITY.json'))))C.fail('PACKAGE_TEST_GATE_MISSING');
 if(!o['canonical-baseline-only'])C.fail('CANONICAL_BASELINE_ONLY_REQUIRED');
 const secret=C.loadSecret(o.secret),guard=C.loadGuard(compat),ts=createRequire(path.join(compat,'package.json'))('typescript');inspectProfile(compat,'off',undefined,ts);U.newDir(work);const run=path.join(work,'run');U.newDir(run);const api=client(secret);
 const readinessEvent=v=>C.log(S.file(run,'baseline-readiness-events.jsonl'),v),readEvent=v=>readinessEvent({component:'identity',...v});
 const read=(operation,fn,budgetMs=K.READINESS_OPERATION_MS)=>RR.readWithRetry({operation,budgetMs:Math.max(100,Math.min(K.READINESS_OPERATION_MS,Math.floor(budgetMs))),read:fn,record:v=>readinessEvent({component:'read-only',...v}),policy:{...RR.DEFAULT_READ_POLICY,perAttemptMaxMs:8000}});
 let canonical=null;try{if(o['canonical-backup'])canonical=L.loadCanonicalBackup(path.resolve(o['canonical-backup']),guard);}catch(e){S.newRecord(run,'canonical-backup-failure.json',{error:C.code(e),atMs:Date.now()});S.newRecord(run,'preparation-failure.json',{error:C.code(e),atMs:Date.now(),noUpload:true,baselineBound:false,canonicalBaselineAccepted:false});throw e;}
 try{
  const ready=await Q.establish({guard,record:readinessEvent,readIdentity:(_attempt,budget)=>A.current(api,guard,{attempts:1,requestMs:Math.max(100,Math.min(20000,Math.floor(budget/4))),record:readEvent}),readOverview:(_attempt,budget)=>read('readiness.overview',ms=>api.overview(C.EXPECTED.shard,ms),budget),readTime:(_attempt,budget)=>read('readiness.time',ms=>api.time(C.EXPECTED.shard,ms),budget)});
  S.newRecord(run,'baseline-readiness.json',publicReadiness(ready));
  const prebind=await A.current(api,guard,{record:v=>readinessEvent({component:'prebind-identity',...v}),requestMs:20000});if(!P.equalModules(prebind.modules,ready.baseline.modules,guard))C.fail('LIVE_BASELINE_CHANGED_AFTER_READINESS');
  const live=await read('prepare.time.anchor',ms=>api.time(C.EXPECTED.shard,ms));if(live?.ok!==1||!Number.isSafeInteger(live.time)||live.time<ready.lastTick)C.fail('GAME_TICK_UNREADABLE');
  const profile=K.profileFor(live.time),runId=crypto.randomBytes(16).toString('hex');S.newRecord(run,'binding-intent.json',{runId,sourceHead:source.head,sourceTree:source.tree,observedTick:live.time,profile,atMs:Date.now()});
  fs.writeFileSync(path.join(compat,K.CONFIG),K.renderConfig(profile));U.git(compat,['add','--',K.CONFIG]);U.git(compat,['commit','-m',`evidence(compat): bind envelope XII online II retry I ${profile.startTick}-${profile.endTick}`]);U.clean(compat);
  const head=U.textGit(compat,['rev-parse','HEAD']);if(U.textGit(compat,['rev-parse','HEAD^'])!==source.head||U.textGit(compat,['diff','--name-only',source.head,head])!==K.CONFIG)C.fail('PROFILE_COMMIT_SCOPE_INVALID');S.newRecord(run,'binding.json',{runId,sourceHead:source.head,sourceTree:source.tree,profileHead:head,observedTick:live.time,profile,atMs:Date.now()});inspectProfile(compat,'on',live.time,ts);
  const b=B.detachedBuild(compat,head,work),build=P.confirmBuild(b.modules,b.head,b.tree);const current=await A.current(api,guard,{record:v=>readinessEvent({component:'postbuild-identity',...v}),requestMs:20000});
  const fresh=await read('prepare.time.fresh',ms=>api.time(C.EXPECTED.shard,ms));if(fresh?.ok!==1||!Number.isSafeInteger(fresh.time)||fresh.time<live.time)C.fail('GAME_TICK_UNREADABLE');validateProfileLead(profile,fresh.time);if(!P.equalModules(ready.baseline.modules,current.modules,guard)||!P.equalModules(prebind.modules,current.modules,guard))C.fail('BASELINE_CHANGED_DURING_BUILD');
  const backup=P.makeSnapshot(current.modules,guard),candidate=P.makeSnapshot(b.modules,guard),authorization={...ready.authorization};delete authorization.modules;
  S.newRecord(run,'backup.json',backup);S.newRecord(run,'candidate.json',candidate);
  const s={kind:K.KIND,runId,...C.EXPECTED,refactorBase:K.REFACTOR,compatRootBase:K.COMPAT,compatBase:source.head,sourceHead:source.head,sourceTree:source.tree,observedTick:live.time,baselineAuthorization:authorization,
   profile,profileHead:head,profileTree:b.tree,build,backupBuild:current.build,preparedAtMs:Date.now(),wallLimitMs:K.WALL_MS,toolFingerprint:C.sha256(fs.readFileSync(path.join(U.ROOT,'INTEGRITY.json'))),backupFileSha256:C.sha256(fs.readFileSync(S.file(run,'backup.json'))),candidateFileSha256:C.sha256(fs.readFileSync(S.file(run,'candidate.json')))};
  S.newRecord(run,'session.json',s);S.loadRun(run,guard);const pub={...s,kind:K.PUBLIC_KIND,backupDigest:backup.digest,candidateDigest:candidate.digest};S.newRecord(run,'public-session.json',pub);
  const result={status:'ENVELOPE_XII_RETRY_PREPARED_NOT_DEPLOYED',runId,profileHead:head,startTick:profile.startTick,endTick:profile.endTick,latestObservedTick:fresh.time,baselineAuthorization:authorization,work};S.newRecord(run,'prepare-result.json',result);return result;
 }catch(e){
  const code=C.code(e);if(code==='LIVE_BASELINE_DRIFT_UNRESOLVED'&&e.readinessIdentity){if(!fs.existsSync(S.file(run,'baseline-readiness.json')))S.newRecord(run,'baseline-readiness.json',{status:'LIVE_BASELINE_DRIFT_UNRESOLVED',canonicalBaselineAccepted:false,details:e.details||null,stableReads:e.readinessSamples||[],atMs:Date.now()});if(canonical){const diff=L.diffSummary(e.readinessIdentity.modules,canonical,guard);S.newRecord(run,'baseline-drift-diff.json',diff);}}
  const intent=S.optional(run,'binding-intent.json'),readyRecord=S.optional(run,'baseline-readiness.json');S.newRecord(run,'preparation-failure.json',{error:code,atMs:Date.now(),noUpload:true,baselineBound:Boolean(intent),canonicalBaselineAccepted:readyRecord?.authorization?.canonicalBaselineAccepted===true});if(intent)try{closeSource(compat,run);}catch(err){S.newRecord(run,'close-source-failure.json',{error:C.code(err)});}throw e;
 }
}
module.exports={prepare,publicReadiness};if(require.main===module)U.cli(async()=>{const o=U.options(['refactor','compat','work','secret','offline','tests','canonical-backup'],['bind-profile','canonical-baseline-only']);C.required(o,'refactor','compat','work','secret','offline','tests');if(!o['bind-profile'])C.fail('EXPLICIT_PROFILE_BINDING_REQUIRED');U.verifyPackage();console.log(JSON.stringify(await prepare(o)));});
