'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const C=require('../runtime/common.cjs'),U=require('../tools/util.cjs'),X=require('../tools/source.cjs');
const ROOT=path.resolve(__dirname,'..');
function assembled(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'gen-hot-xi-'));fs.cpSync(path.join(ROOT,'source/implementation'),d,{recursive:true});return d;}
test('optimized generator parses and exports both hot-path transforms',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs'));assert.equal(typeof g.verifyOutputIdentities,'function');assert.equal(typeof g.H.transform,'function');assert.equal(typeof g.P.transform,'function');});
test('optimized generator deterministically reproduces core preview manifest and provenance',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs'));const out=g.generate(fs.readFileSync(path.join(d,g.FIXTURE)),fs.readFileSync(path.join(d,g.TEMPLATE)),JSON.parse(fs.readFileSync(path.join(d,g.SOURCE_MANIFEST))),fs.readFileSync(path.join(d,g.PREVIEW_FIXTURE)));for(const rel of [g.GENERATED,g.PREVIEW,g.SOURCE_MANIFEST,g.PROVENANCE])assert.equal(out[rel].equals(fs.readFileSync(path.join(d,rel))),true,rel);});
test('core hot-path transform reverses exactly to IX input',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs')),after=fs.readFileSync(path.join(d,g.GENERATED),'utf8'),before=fs.readFileSync(path.join(d,g.IX_CORE_BLOB? 'test/treasury-compat/fixtures/core-before-hotpath-optimization-xi.ts.txt':'test/treasury-compat/fixtures/core-before-hotpath-optimization-xi.ts.txt'),'utf8');assert.equal(g.H.restore(after),before);});
test('preview hot-path transform reverses exactly to IX input',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs')),after=fs.readFileSync(path.join(d,g.PREVIEW),'utf8'),before=fs.readFileSync(path.join(d,g.PREVIEW_FIXTURE),'utf8');assert.equal(g.P.restore(after),before);});
test('implementation changed byte is rejected by frozen lock',()=>{const tmp=assembled(),rel='src/runtime/treasuryCompatCpu.ts',p=path.join(tmp,rel),b=fs.readFileSync(p);fs.writeFileSync(p,Buffer.concat([b,Buffer.from('x')]));assert.throws(()=>X.verifyFiles(tmp,X.LOCK),e=>e.code==='SOURCE_LOCK_CHANGED');});
test('run-tests requires exact test contract',()=>{const c=require('../references/test-contract.json'),files=fs.readdirSync(path.join(ROOT,'tests')).filter(x=>x.endsWith('.spec.cjs')).sort().map(x=>'tests/'+x);assert.deepEqual(files,c.files);});
test('package verifier rejects an extra file in a copy',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pkg-hot-xi-'));fs.cpSync(ROOT,tmp,{recursive:true});fs.writeFileSync(path.join(tmp,'extra.txt'),'x');const r=cp.spawnSync(process.execPath,['-e',`require(${JSON.stringify(path.join(tmp,'tools/util.cjs'))}).verifyPackage()`],{encoding:'utf8'});assert.notEqual(r.status,0);});
test('CLI argument parser rejects duplicates',()=>assert.throws(()=>C.options(['--x','a','--x','b'],['x']),e=>e.code==='INVALID_ARGUMENTS'));
