'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../runtime/common.cjs'),K=require('../runtime/policy.cjs'),P=require('../tools/prerequisites.cjs'),M=require('../tools/compare.cjs');
const H=require('./reader-fixture.cjs'),F=require('./fixture.cjs'),W=require('../runtime/samples.cjs'),V=require('../runtime/verify-run.cjs');
const ROOT=path.resolve(__dirname,'..'),copy=x=>JSON.parse(JSON.stringify(x));
function actual({chargeBuild=0,enabled=true,catalogFailure=false}={}){
 const f=H.fixture({probeCost:0.001});let catalog=['energy','H','O','X'];let calls=0;
 const game={time:100,rooms:f.rooms,getObjectById:()=>null};
 const source=fs.readFileSync(path.join(ROOT,'references/treasuryCompatReadCore.generated.ts'),'utf8');
 const core=H.compile(source,'treasuryCompatReadCore.generated.ts',{Game:game,Memory:f.memory,get RESOURCES_ALL(){return catalog;}});
 f.ports.readers=()=>{calls++;if(catalogFailure&&calls>1)throw new Error('fixture unavailable catalog');const r=core.exports.createCompatibilityReadCore();return {buildObservation:r.buildObservation,buildCommitments:o=>{const x=r.buildCommitments(o);f.charge(chargeBuild);return x;}};};
 const profile={...K.profileFor(1000),enabled};const preview=H.loadReader().exports.createTreasuryCompatPreview(profile,f.ports,{cpuDiagnostics:true});
 for(const tick of K.dueTicks({...profile,enabled:true})){game.time=tick;f.setTime(tick);preview.run();}
 return {f,profile,preview,calls,reports:f.logs.map(JSON.parse)};
}
test('VIII historical baseline is the exact accepted CPU VI capture',()=>{const v=P.packaged().prior;assert.equal(P.LOCK.priorDiagnostic.blob,'d1be370705d4bb3d1a0e522d0afc57f72f52f1f8');assert.equal(v.profileHead,'2ed75fd5780f0abb386bd71d9824f364c6cf9dbd');assert.deepEqual(v.receivedTicks,[73676300,73676400,73676500,73676600]);});
test('VIII CPU VI baseline retains three observation and three commitment invocations',()=>{const m=M.measures(P.packaged().prior);assert.equal(m.invocations.observationBuild.count,3);assert.equal(m.invocations.commitmentBuild.count,3);assert.equal(m.completeSamples,0);assert.equal(m.invocations.observationBuild.boundaryOnlyIntervals.length,1);});
test('VIII CPU VI post-first loader median is pinned exactly',()=>{const m=M.measures(P.packaged().prior);assert.equal(m.firstAdmissionIsFirstReaderInvocation,true);assert.equal(m.invocations.readerLoad.followingInvocationCount,3);assert.equal(m.invocations.readerLoad.followingInvokedIntervalMedian,0.12270699999498902);});
test('VIII Build VII acceptance pins both changed factories and unresolved engine gap',()=>{const a=P.packaged().accepted;assert.equal(a.compatHead,K.COMPAT);assert.deepEqual(a.factoryBodiesChanged,['commitments: full task-bucket storage','observation: intermediates']);assert.equal(a.followingFactoryExecutions,0);assert.equal(a.taskBucketStorageChanged,true);assert.equal(a.observationIntermediatesReduced,true);assert.equal(a.engineCpuGapRepaired,false);});
test('VIII retained older CPU II oracle cannot satisfy CPU VI prerequisite bytes',()=>{const b=fs.readFileSync(path.join(ROOT,'references/diagnostic-II-result.json'));assert.throws(()=>P.checkedBytes(b,P.LOCK.priorDiagnostic),e=>e.code==='PREREQUISITE_BYTES_MISMATCH');});
test('VIII complete actual Build VII report includes all four query rows and qualifies without loosening validator',()=>{const a=actual();for(const [i,r]of a.reports.entries()){assert.equal(W.diagnosticError(r,a.profile,i,a.reports[i-1]||null,a.f.logs[i-1]||null),null);const d=M.reportDetail(r,a.profile);assert.equal(d.commitmentActuallyInvoked,true);assert.equal(d.commitmentIndexComplete,true);assert.equal(d.commitmentProjectionRows,4);assert.equal(d.completeSample,true);assert.equal(d.directOkEndpoints,4);assert.equal(d.coreMatchedEndpoints,4);}});
test('VIII completed index with zero projected rows remains budget partial and never zero commitment',()=>{const a=actual({chargeBuild:2.2});for(const r of a.reports){assert.equal(r.cpuProfile.calls.commitmentBuild,1);assert.equal(r.commitments.completeness.complete,true);assert.equal(r.commitments.rows.length,0);const d=M.reportDetail(r,a.profile);assert.equal(d.commitmentProjectionRows,0);assert.equal(d.completeSample,false);assert.equal(d.emptyRowsProveNoCommitments,false);assert.equal(d.sampleCompletenessReason,'SAMPLE_NOT_COMPLETE');}});
test('VIII a non-invoked index is not an empty completed index',()=>{const s=F.session(),reports=F.reports(s,{partialAll:true});for(const r of reports){const d=M.reportDetail(r,s.profile);assert.equal(d.commitmentActuallyInvoked,false);assert.equal(d.commitmentIndexComplete,null);assert.equal(d.commitmentProjectionRows,null);assert.equal(d.completeSample,false);}});
test('VIII a partial four-point actual core run is useful diagnosis without full sample acceptance',()=>{const a=actual({chargeBuild:2.2});for(const[i,r]of a.reports.entries()){assert.equal(W.diagnosticError(r,a.profile,i,a.reports[i-1]||null,a.f.logs[i-1]||null),null);assert.equal(W.sampleError(r,a.profile),'SAMPLE_NOT_COMPLETE');}const v={rawReports:4,diagnosticReports:4,completeSamples:0,partialCpuSamples:4,analysis:V.summarize(a.reports,a.profile)};assert.equal(M.measures(v).invocations.commitmentBuild.count,4);assert.equal(M.measures(v).completeSamples,0);});
test('VIII complete emitted rows with incomplete index cannot pass sample qualification',()=>{const a=actual(),r=copy(a.reports[0]);r.commitments.completeness.complete=false;const d=M.reportDetail(r,a.profile);assert.equal(d.commitmentProjectionRows,4);assert.equal(d.completeSample,false);assert.equal(d.sampleCompletenessReason,'COMMITMENTS_INCOMPLETE');});
test('VIII four result rows with a duplicated scope do not imply complete projection',()=>{const a=actual(),r=copy(a.reports[0]);r.commitments.rows[3]=copy(r.commitments.rows[0]);assert.equal(M.reportDetail(r,a.profile).sampleCompletenessReason,'COMMITMENT_ROW_INVALID');});
test('VIII direct core mismatch remains a runtime safety failure, not a performance observation',()=>{const a=actual(),r=copy(a.reports[0]);r.endpoints[0].coreComparison='mismatch';assert.equal(W.diagnosticError(r,a.profile,0),'CORE_COMPARISON_MISMATCH');assert.equal(M.reportDetail(r,a.profile).completeSample,false);});
test('VIII legitimate old projection mismatch remains visible and does not make direct core self-comparison',()=>{const a=actual(),r=copy(a.reports[0]);r.endpoints[0].legacyProjection={status:'mismatch',mismatches:['terminalEnergy']};assert.equal(W.sampleError(r,a.profile),null);assert.equal(M.reportDetail(r,a.profile).coreMatchedEndpoints,4);});
test('VIII complete prefixes do not invent final fourth tail or infer global CPU repair',()=>{const a=actual();const v={status:'CPU_DIAGNOSTIC_CAPTURE_VERIFIED',captureVerified:true,closure:'RESTORED_BYTES_AND_RUNTIME_VERIFIED',rawReports:4,diagnosticReports:4,completeSamples:4,partialCpuSamples:0,analysis:V.summarize(a.reports,a.profile)};const r=M.compareResults(v,P.packaged().prior);assert.equal(r.current.measurements.prefixRows.at(-1).afterRetentionCpu,null);assert.equal(r.current.measurements.successorTailProfiles,3);assert.equal(r.interpretation.engineCpuGapRepaired,false);assert.equal(r.interpretation.fullCompatibilityObserved,false);});
test('VIII OFF remains zero readers and zero reports with Build VII definitions',()=>{const a=actual({enabled:false});assert.equal(a.calls,0);assert.equal(a.reports.length,0);assert.equal(a.f.calls.memory,0);});
test('VIII warm initialization failure disables rather than borrowing an earlier completed report',()=>{const a=actual({catalogFailure:true});assert.equal(a.reports[0].status,'sampled');assert.equal(a.reports[1].status,'fault_disabled');assert.equal(a.reports.length,2);assert.equal(a.preview.stats().retainedEndpoints,0);});
test('VIII comparison outcome is independent of improvement; exact equality is a valid record',()=>{const prior=P.packaged().prior,now=copy(prior);now.runId='f'.repeat(32);const r=M.compareResults(now,prior);assert.equal(r.status,'BUILD_VIII_COMPARISON_RECORDED');assert.equal(r.phaseComparisons.readerLoad.relation,'equal_observed_median');assert.equal(r.interpretation.causalSpeedupClaim,false);});
test('VIII no current session cannot borrow historical projection rows',()=>{const dir=F.tmp(),r=M.makeComparison(dir);assert.equal(r.currentCaptureVerified,false);assert.deepEqual(r.currentReportDetails,[]);assert.equal(r.currentProjectionSummary.fullSamples,0);assert.equal(r.historical.measurements.invocations.commitmentBuild.count,3);});
test('VIII corrupt current public session remains an inconclusive record not a successful fallback',()=>{const dir=F.tmp();fs.writeFileSync(path.join(dir,'public-session.json'),'{bad');const r=M.makeComparison(dir);assert.equal(r.currentCaptureVerified,false);assert.equal(r.current.measurements,null);assert.equal(r.currentProjectionSummary.reports,0);});
test('VIII read-only comparison does not mutate report, source profile or accepted historical object',()=>{const a=actual(),prior=P.packaged().prior,before=JSON.stringify([a.reports,a.profile,prior]);a.reports.forEach(r=>M.reportDetail(r,a.profile));M.compareResults({...prior,runId:'f'.repeat(32)},prior);assert.equal(JSON.stringify([a.reports,a.profile,prior]),before);});
function repoGateFixture({tests=200,pass=200,skipped=0,cancelled=0,status=0}={}){
 const cp=require('node:child_process'),B=require('../tools/build.cjs'),out=F.tmp(),saved=cp.spawnSync;let observed;
 const names=['DEST','DEPLOY_ALLOW_DIRTY','NODE_OPTIONS','NODE_PATH','CPU_DIAG_FIXTURE_ROOT'];const oldEnv=names.map(k=>[k,process.env[k]]);for(const k of names)delete process.env[k];
 cp.spawnSync=(exe,args,options)=>{observed={exe,args,options};return {status,signal:null,stdout:`TAP version 13\n# fixture output keeps spaces \n# tests ${tests}\n# pass ${pass}\n# fail 0\n# skipped ${skipped}\n# cancelled ${cancelled}\n# todo 0\n`,stderr:''};};
 try{return {result:B.runRepositoryTests('/synthetic-repository-not-real',out),observed,out};}finally{cp.spawnSync=saved;for(const[k,v]of oldEnv){if(v===undefined)delete process.env[k];else process.env[k]=v;}}
}
test('VIII offline repository gate binds all five specs and exact 200-test TAP',()=>{const x=repoGateFixture();assert.equal(x.result.passed,200);assert.equal(x.observed.args.filter(p=>p.endsWith('.spec.cjs')).length,5);assert.ok(x.observed.args.some(p=>p.endsWith('build-optimization.spec.cjs')));assert.equal(x.observed.args[0],'--test');assert.equal(x.observed.options.timeout,900000);assert.ok(fs.readFileSync(path.join(x.out,'repository-tests.stdout'),'utf8').includes('spaces \n'));});
test('VIII missing repository test does not pass just because subprocess exits zero',()=>{assert.throws(()=>repoGateFixture({tests:199,pass:199}),e=>e.code==='REPOSITORY_NODE_TEST_GATE_FAILED');});
test('VIII skipped repository tests cannot count toward the fixed gate',()=>{assert.throws(()=>repoGateFixture({skipped:1}),e=>e.code==='REPOSITORY_NODE_TEST_GATE_FAILED');});
test('VIII cancelled repository tests cannot count toward the fixed gate',()=>{assert.throws(()=>repoGateFixture({cancelled:1}),e=>e.code==='REPOSITORY_NODE_TEST_GATE_FAILED');});
