'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),crypto=require('node:crypto');
const C=require('../runtime/common.cjs'),I=require('../runtime/identity.cjs'),T=require('../runtime/transport.cjs'),R=require('../runtime/recovery.cjs'),O=require('../runtime/observer.cjs'),A=require('../tools/archive.cjs'),P=C.POLICY;
const actual=I.loadOrigin(process.env.RECOVERY_FIXTURE_RUN);
test('real-size snapshots traverse HTTP, lost POST reply, readback and fresh observer end to end',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'recovery-e2e-'));let state='candidate',posts=0,clock=0;
 const s=http.createServer((q,r)=>{if(q.method==='POST'){let data=[];q.on('data',b=>data.push(b));q.on('end',()=>{const m=JSON.parse(Buffer.concat(data));assert.ok(I.eq(m.modules,actual.backup.modules));posts++;state='backup';q.socket.destroy();});return;}
  if(q.url==='/api/auth/me')r.end(JSON.stringify({ok:1,_id:P.expected.userId,username:P.expected.username}));else if(q.url==='/api/user/branches')r.end(JSON.stringify({ok:1,list:[{branch:'default',activeWorld:true}]}));else r.end(JSON.stringify({ok:1,modules:state==='candidate'?actual.candidate.modules:actual.backup.modules}));});
 await new Promise(resolve=>s.listen(0,'127.0.0.1',resolve));
 class WS{constructor(){this.l={};setTimeout(()=>this.l.open?.(),1);}addEventListener(k,f){this.l[k]=f;}send(text){if(text.startsWith('auth '))setTimeout(()=>this.l.message?.({data:'auth ok'}),1);if(text.endsWith('/cpu'))this.timer=setInterval(()=>{this.l.message?.({data:JSON.stringify([`user:${P.expected.userId}/console`,{shard:'shard1',messages:{log:[],results:[]}}])});this.l.message?.({data:JSON.stringify([`user:${P.expected.userId}/cpu`,{cpu:1}])});},5);}close(){clearInterval(this.timer);}}
 try{const result=await R.recover({origin:{...actual,run:root},api:T.client({token:'fixture-token'},{testOrigin:'http://127.0.0.1:'+s.address().port}),secret:{token:'fixture-token',redact:x=>x},fingerprint:'a'.repeat(64),execute:true,exclusive:true,workersStopped:true,authorizeAdditional:true,mono:()=>clock,pause:async ms=>{clock+=ms;},readBudgetMs:25000,observer:o=>O.observe({...o,WebSocketClass:WS,durationMs:40,startupMs:1000,silenceMs:1000,pollMs:5}),verifyObserver:d=>O.verify(d,{durationMs:40,silenceMs:1000})});assert.equal(result.status,'RESTORED_BYTES_AND_RUNTIME_VERIFIED');assert.equal(result.postOutcome.error,'HTTP_TRANSPORT_ERROR');assert.equal(posts,1);assert.equal(state,'backup');}finally{s.closeAllConnections();await new Promise(resolve=>s.close(resolve));fs.rmSync(root,{recursive:true,force:true});}});

test('full archive, native Git commit, local bare remote push and idempotent republish',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'archive-e2e-')),beforePolicy={compatHead:P.compatHead,refactorHead:P.refactorHead,sourceTree:P.sourceTree};
 try{const origin=path.join(temp,'original');fs.mkdirSync(origin);for(const n of Object.keys(P.originFiles).concat('actions.jsonl')){const f=path.join(origin,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.copyFileSync(path.join(actual.run,n),f);}
  const info=C.verifyPackage(),root=path.join(origin,P.ledgerDirectory),id='b'.repeat(32),out=path.join(root,'invocation-'+id);fs.mkdirSync(out,{recursive:true});C.durable(path.join(root,'authorization.json'),{authorizationId:P.authorizationId,parentRunId:P.parentRunId,packageFingerprint:info.fingerprint});C.durable(path.join(out,'invocation.json'),{authorizationId:P.authorizationId,parentRunId:P.parentRunId,invocationId:id,packageFingerprint:info.fingerprint,createdAtMs:500,mode:'read-only'});
  C.durable(path.join(out,'result.json'),{status:'ONLINE_CLOSE_UNCONFIRMED',authorizationId:P.authorizationId,parentRunId:P.parentRunId,invocationId:id,originalCaptureRemains:'CPU_DIAGNOSTIC_CAPTURE_INCONCLUSIVE',originalRestorePostAttempts:1,httpRestoreCallsInThisInvocation:0,automaticWriteRetry:false,finalByteReadConfirmed:false,runtimeConfirmed:false,error:'RECOVERY_READ_DEADLINE',atMs:1000});
  const tests=path.join(temp,'offline');fs.mkdirSync(tests);const count=require('../references/test-contract.json').count;C.durable(path.join(tests,'result.json'),{status:'RECOVERY_OFFLINE_TESTS_VERIFIED',packageFingerprint:info.fingerprint,tests:count,passed:count,failed:0});fs.writeFileSync(path.join(tests,'tests.tap'),'fixture test log, not a real test result\n');fs.writeFileSync(path.join(tests,'tests.stderr'),'');
  const remote=path.join(temp,'origin.git');fs.mkdirSync(remote);A.git(remote,['init','--bare']);function repo(name,branch){const p=path.join(temp,name);fs.mkdirSync(p);A.git(p,['init']);A.git(p,['config','user.email','fixture@example.invalid']);A.git(p,['config','user.name','Recovery Fixture']);A.git(p,['branch','-M',branch]);fs.writeFileSync(path.join(p,'base'),'base\n');A.git(p,['add','base']);A.git(p,['commit','-m','base']);A.git(p,['remote','add','origin',remote]);A.git(p,['push','origin','HEAD:refs/heads/'+branch]);return p;}
  const compat=repo('compat','compat/treasury-read-bridge-i'),refactor=repo('refactor','refactor/empire-treasury-rearchitecture');P.compatHead=A.text(compat,['rev-parse','HEAD']);P.sourceTree=A.text(compat,['rev-parse','HEAD^{tree}']);P.refactorHead=A.text(refactor,['rev-parse','HEAD']);const secret=path.join(temp,'private-secret.json');C.durable(secret,{main:{hostname:'screeps.com',branch:'default',token:crypto.randomBytes(32).toString('hex')}});
  const args={run:origin,tests,compat,refactor,secret,push:true};const a=A.archive(args),b=A.archive(args);assert.equal(a.status,'SANCTIONED_RECOVERY_EVIDENCE_PUSHED');assert.equal(a.refactorHead,b.refactorHead);assert.equal(A.text(compat,['rev-parse','HEAD']),P.compatHead);const files=C.list(path.join(refactor,P.evidencePath));assert.equal(files.some(n=>/(?:^|\/)(?:backup|candidate)\.json$/.test(n)),false);A.clean(refactor);A.clean(compat);
 }finally{Object.assign(P,beforePolicy);fs.rmSync(temp,{recursive:true,force:true});}});
