'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const C=require('../runtime/common.cjs'),E=require('../runtime/evidence.cjs'),O=require('../runtime/observer.cjs'),A=require('../tools/archive.cjs'),P=C.POLICY;
function proof(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'proof-test-')),fp='a'.repeat(64),id='b'.repeat(32),closure='c'.repeat(32),dir=path.join(root,'invocation-'+id);fs.mkdirSync(dir);C.durable(path.join(root,'authorization.json'),{authorizationId:P.authorizationId,parentRunId:P.parentRunId,packageFingerprint:fp});
 const meta={authorizationId:P.authorizationId,parentRunId:P.parentRunId,invocationId:id,packageFingerprint:fp,mode:'read-only',createdAtMs:500};C.durable(path.join(dir,'invocation.json'),meta);
 const before={state:'CURRENT_IS_BACKUP',digest:P.backupDigest,build:P.backupBuild,atMs:800},after={...before,atMs:77000};C.durable(path.join(dir,'code-before-runtime.json'),before);C.durable(path.join(dir,'code-after-runtime.json'),after);
 const r={status:'RECOVERY_RUNTIME_COLLECTED',reason:'runtime_complete',parentRunId:P.parentRunId,closureId:closure,invocationId:id,pid:1234,createdAtMs:900,startedAtMs:1000,endedAtMs:76000,monotonicDurationMs:75000,requestedDurationMs:75000,authentications:1,observationSamplesAccepted:0};C.durable(path.join(dir,'runtime-result.json'),r);
 const add=(atMs,kind,more={})=>C.append(path.join(dir,'runtime-console.jsonl'),{atMs,parentRunId:P.parentRunId,closureId:closure,invocationId:id,pid:1234,kind,...more});add(900,'runtime-start');add(950,'auth-confirmed');add(1000,'runtime-ready',{startedAtMs:1000});for(const t of [1000,2000,20000,40000,60000,75500]){add(t,'ws-frame',{text:JSON.stringify([`user:${P.expected.userId}/console`,{shard:'shard1',messages:{log:[],results:[]}}]),redacted:false});add(t,'ws-frame',{text:JSON.stringify([`user:${P.expected.userId}/cpu`,{cpu:1}]),redacted:false});}add(76000,'runtime-footer',{endedAtMs:76000,reason:'runtime_complete'});
 const result={status:'RESTORED_BYTES_AND_RUNTIME_VERIFIED',authorizationId:P.authorizationId,parentRunId:P.parentRunId,invocationId:id,originalCaptureRemains:'CPU_DIAGNOSTIC_CAPTURE_INCONCLUSIVE',originalRestorePostAttempts:1,httpRestoreCallsInThisInvocation:0,automaticWriteRetry:false,finalByteReadConfirmed:true,runtimeConfirmed:true,before,after,runtime:O.verify(dir),atMs:78000,error:null};C.durable(path.join(dir,'result.json'),result);return {root,dir,fp,result,clean(){fs.rmSync(root,{recursive:true,force:true});}};
}
test('recovery proof independently recomputes runtime and byte ordering',()=>{const p=proof();try{assert.equal(E.verify(p.root,p.fp).status,'RESTORED_BYTES_AND_RUNTIME_VERIFIED');}finally{p.clean();}});
test('a claimed success with substituted final bytes is rejected',()=>{const p=proof();try{const f=path.join(p.dir,'code-after-runtime.json'),v=C.json(f);v.digest=P.candidateDigest;fs.writeFileSync(f,JSON.stringify(v));assert.throws(()=>E.verify(p.root,p.fp),/RECOVERY_BYTE_EVIDENCE_INVALID/);}finally{p.clean();}});
test('a claimed success without a full runtime interval is rejected',()=>{const p=proof();try{const f=path.join(p.dir,'runtime-result.json'),v=C.json(f);v.monotonicDurationMs=1;fs.writeFileSync(f,JSON.stringify(v));assert.throws(()=>E.verify(p.root,p.fp),/RUNTIME_RESULT_INVALID/);}finally{p.clean();}});
test('private snapshots and unexpected files are never eligible for archive',()=>{const p=proof();try{fs.writeFileSync(path.join(p.root,'backup.json'),'private');assert.throws(()=>E.verify(p.root,p.fp),/UNAPPROVED_RECOVERY_EVIDENCE_FILE/);}finally{p.clean();}});
test('secret scanning covers raw, prefix, encoded, base64 and hex',()=>{const t='token-1234+/ABcd5678';for(const x of [t,t.slice(0,8),encodeURIComponent(t),Buffer.from(t).toString('base64'),Buffer.from(t).toString('hex')])assert.equal(A.secretScan(Buffer.from('x'+x+'y'),t),true);});
test('native Git evidence scope and whitespace gate accept package but reject source edit',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'archive-native-'));try{A.git(dir,['init']);A.git(dir,['config','user.email','test@example.invalid']);A.git(dir,['config','user.name','Recovery Test']);fs.writeFileSync(path.join(dir,'baseline'),'base\n');A.git(dir,['add','baseline']);A.git(dir,['commit','-m','baseline']);const dest=path.join(dir,P.evidencePath,'task-package');fs.cpSync(path.resolve(__dirname,'..'),dest,{recursive:true});A.git(dir,['add','--',P.evidencePath]);assert.ok(A.scope(dir,['diff','--cached']).length>10);A.git(dir,['diff','--cached','--check']);A.git(dir,['commit','-m','test evidence']);A.clean(dir);fs.mkdirSync(path.join(dir,'src'));fs.writeFileSync(path.join(dir,'src/main.ts'),'bad\n');A.git(dir,['add','src/main.ts']);assert.throws(()=>A.scope(dir,['diff','--cached']),/EVIDENCE_SCOPE_CHANGED/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
