'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const C=require('../runtime/common.cjs'),O=require('../runtime/observer.cjs'),P=C.POLICY;
const con=(log=[],extra={})=>JSON.stringify([`user:${P.expected.userId}/console`,{shard:'shard1',messages:{log,results:[]},...extra}]);
const cpu=n=>JSON.stringify([`user:${P.expected.userId}/cpu`,{cpu:n}]);
function trace(mutate=()=>{}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-proof-'));let r={status:'RECOVERY_RUNTIME_COLLECTED',reason:'runtime_complete',parentRunId:P.parentRunId,closureId:'a'.repeat(32),invocationId:'b'.repeat(32),pid:1234,createdAtMs:900,startedAtMs:1000,endedAtMs:76000,monotonicDurationMs:75000,requestedDurationMs:75000,authentications:1,observationSamplesAccepted:0};let e=[];const add=(atMs,kind,more={})=>e.push({atMs,parentRunId:r.parentRunId,invocationId:r.invocationId,closureId:r.closureId,pid:r.pid,kind,...more});add(900,'runtime-start');add(950,'auth-confirmed');add(1000,'runtime-ready',{startedAtMs:1000});for(const t of [1000,2000,20000,40000,60000,75500]){add(t,'ws-frame',{text:con(),redacted:false});add(t,'ws-frame',{text:cpu(1),redacted:false});}add(76000,'runtime-footer',{endedAtMs:76000,reason:'runtime_complete'});mutate(r,e);C.durable(path.join(dir,'runtime-result.json'),r);for(const x of e)C.append(path.join(dir,'runtime-console.jsonl'),x);return dir;}
function check(mutate,pattern){const d=trace(mutate);try{if(pattern)assert.throws(()=>O.verify(d),pattern);else assert.equal(O.verify(d).status,'RECOVERY_RUNTIME_INDEPENDENTLY_VERIFIED');}finally{fs.rmSync(d,{recursive:true,force:true});}}
test('independent 75-second synthetic trace passes',()=>check());
test('missing continuous console evidence is rejected',()=>check((r,e)=>{for(let i=e.length-1;i>=0;i--)if(e[i].kind==='ws-frame'&&O.frameKind(e[i].text).kind==='console')e.splice(i,1);},/RUNTIME_CHANNEL_GAP/));
test('zero CPU after readiness is not liveness proof',()=>check((r,e)=>{for(const x of e)if(x.kind==='ws-frame'&&O.frameKind(x.text).kind==='cpu')x.text=cpu(0);},/RUNTIME_CHANNEL_GAP/));
test('a bridge report invalidates recovery liveness',()=>check((r,e)=>{e.find(x=>x.kind==='ws-frame').text=con(['{"kind":"treasury-legacy-read-bridge"}']);},/UNEXPECTED_BRIDGE/));
test('runtime server errors invalidate recovery proof',()=>check((r,e)=>{e.find(x=>x.kind==='ws-frame').text=con([],{error:'failure'});},/CONSOLE_RUNTIME_ERROR/));
test('short duration is rejected',()=>check(r=>{r.monotonicDurationMs=74999;},/RUNTIME_RESULT_INVALID/));
test('candidate deploy identity invalidates recovery proof',()=>check((r,e)=>{e.find(x=>x.kind==='ws-frame').text=con(['[deploy] '+P.candidateBuild.tag]);},/UNEXPECTED_DEPLOY/));
test('redacted frames cannot sign off runtime liveness',()=>check((r,e)=>{e.find(x=>x.kind==='ws-frame').redacted=true;},/REDACTED_RUNTIME/));
test('repeated auth event is rejected',()=>check((r,e)=>{e.splice(2,0,{...e[1]});},/RUNTIME_EVENT_COUNT_INVALID/));
test('secret redactor removes token and encoded/prefix forms',()=>{const token='unique-live-token-12345678';const f=C.redactor(token);for(const v of [token,encodeURIComponent(token),token.slice(0,8),Buffer.from(token).toString('base64')])assert.equal(f(v).includes(v),false);});
test('observer subscribes only to console/CPU and never sends console evaluation',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'observer-event-'));let sent=[];class WS{constructor(){this.listeners={};setTimeout(()=>{this.emit('open');},0);}addEventListener(k,fn){this.listeners[k]=fn;}emit(k,data){this.listeners[k]?.(data);}send(s){sent.push(s);if(s.startsWith('auth '))setTimeout(()=>{this.emit('message',{data:'auth ok'});},1);if(s.endsWith('/cpu')){this.timer=setInterval(()=>{this.emit('message',{data:con()});this.emit('message',{data:cpu(1)});},5);}}close(){clearInterval(this.timer);}}
 try{const r=await O.observe({out:dir,secret:{token:'test-token',redact:x=>x},invocationId:'b'.repeat(32),WebSocketClass:WS,durationMs:30,startupMs:1000,silenceMs:1000,pollMs:5});assert.equal(r.status,'RECOVERY_RUNTIME_COLLECTED');assert.equal(O.verify(dir,{durationMs:30,silenceMs:1000}).status,'RECOVERY_RUNTIME_INDEPENDENTLY_VERIFIED');assert.equal(sent.length,3);assert.equal(sent[1],`subscribe user:${P.expected.userId}/console`);assert.equal(sent[2],`subscribe user:${P.expected.userId}/cpu`);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
