'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');const C=require('../runtime/common.cjs'),T=require('../runtime/transport.cjs'),I=require('../runtime/identity.cjs');const origin=I.loadOrigin(process.env.RECOVERY_FIXTURE_RUN);
async function withServer(fn,tester){const s=http.createServer(fn);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await tester(T.client({token:'not-a-real-token'},{testOrigin:'http://127.0.0.1:'+s.address().port}));}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}}
test('actual 4.6 MB candidate GET is decoded without truncation',()=>withServer((q,s)=>{s.end(JSON.stringify({ok:1,modules:origin.candidate.modules}));},async api=>{const r=await api.code(3000);assert.ok(I.eq(r.modules,origin.candidate.modules));}));
test('actual backup POST sends exact byte payload once with content length',async()=>{let count=0;await withServer((q,s)=>{const chunks=[];q.on('data',b=>chunks.push(b));q.on('end',()=>{count++;const b=Buffer.concat(chunks);assert.equal(q.method,'POST');assert.equal(q.url,'/api/user/code');assert.equal(b.length,Number(q.headers['content-length']));const x=JSON.parse(b);assert.equal(x.branch,'default');assert.ok(I.eq(x.modules,origin.backup.modules));s.end('{"ok":1}');});},async api=>{await api.restore(origin.backup.modules,3000);});assert.equal(count,1);});
test('lost POST reply results in one request only',async()=>{let n=0;await withServer((q,s)=>{q.resume();q.on('end',()=>{n++;q.socket.destroy();});},async api=>{await assert.rejects(api.restore(origin.backup.modules,3000),/HTTP_TRANSPORT_ERROR/);});assert.equal(n,1);});
test('explicit total timeout destroys stalled local request',()=>withServer((q,s)=>{},async api=>{await assert.rejects(api.code(40),/HTTP_DEADLINE/);}));
test('HTTP redirects are not followed',async()=>{let n=0;await withServer((q,s)=>{n++;s.writeHead(302,{Location:'http://127.0.0.1:9/'});s.end();},async api=>{await assert.rejects(api.code(500),/HTTP_STATUS_REJECTED/);});assert.equal(n,1);});
test('auth rejection is distinguished from transient failure',()=>withServer((q,s)=>{s.writeHead(403);s.end('forbidden');},async api=>{await assert.rejects(api.me(500),/HTTP_AUTH_REJECTED/);}));
test('malformed success JSON is rejected',()=>withServer((q,s)=>{s.end('not-json');},async api=>{await assert.rejects(api.code(500),/HTTP_JSON_INVALID/);}));
test('test transport cannot point to an arbitrary remote origin',()=>assert.throws(()=>T.client({token:'x'},{testOrigin:'https://example.com'}),/TEST_ORIGIN_FORBIDDEN/));

test('transport refuses uploading candidate or arbitrary bytes as restoration',()=>{const api=T.client({token:'not-real'});assert.throws(()=>api.restore(origin.candidate.modules,1000),/RESTORE_PAYLOAD_NOT_CANONICAL/);});
