'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const C=require('../runtime/common.cjs'),U=require('../tools/util.cjs'),X=require('../tools/source.cjs');
const ROOT=path.resolve(__dirname,'..');
function assembled(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'genx-retry-'));fs.cpSync(path.join(ROOT,'references/current-source'),d,{recursive:true});return d;}
test('current generator parses and exports full-output verifier',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs'));assert.equal(typeof g.verifyOutputIdentities,'function');assert.equal(g.EXPECTED_OUTPUT_PATHS.length,13);});
test('current generator deterministically reproduces manifest and provenance',()=>{const base=assembled(),g=require(path.join(base,'scripts/build-treasury-compat-loader.cjs'));const out=g.generate(fs.readFileSync(path.join(base,g.FIXTURE)),fs.readFileSync(path.join(base,g.TEMPLATE)),JSON.parse(fs.readFileSync(path.join(base,g.SOURCE_MANIFEST))));assert.equal(out[g.SOURCE_MANIFEST].equals(fs.readFileSync(path.join(base,g.SOURCE_MANIFEST))),true);assert.equal(out[g.PROVENANCE].equals(fs.readFileSync(path.join(base,g.PROVENANCE))),true);});
test('source lock changed byte is rejected by frozen verifier',()=>{const tmp=assembled(),rel='src/runtime/treasuryCompatCpu.ts',p=path.join(tmp,rel),b=fs.readFileSync(p);fs.writeFileSync(p,Buffer.concat([b,Buffer.from('x')]));assert.throws(()=>{for(const [name,x] of Object.entries(X.LOCK)){const q=fs.readFileSync(path.join(tmp,name));if(q.length!==x.bytes||C.blob(q)!==x.blob||C.sha256(q)!==x.sha256)C.fail('SOURCE_LOCK_CHANGED');}},e=>e.code==='SOURCE_LOCK_CHANGED');});
test('run-tests requires exact test contract',()=>{const c=require('../references/test-contract.json'),files=fs.readdirSync(path.join(ROOT,'tests')).filter(x=>x.endsWith('.spec.cjs')).sort().map(x=>'tests/'+x);assert.deepEqual(files,c.files);});
test('package verifier rejects an extra file in a copy',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pkgx-retry-'));fs.cpSync(ROOT,tmp,{recursive:true});fs.writeFileSync(path.join(tmp,'extra.txt'),'x');const r=cp.spawnSync(process.execPath,['-e',`require(${JSON.stringify(path.join(tmp,'tools/util.cjs'))}).verifyPackage()`],{encoding:'utf8'});assert.notEqual(r.status,0);});
test('CLI argument parser rejects duplicates',()=>assert.throws(()=>C.options(['--x','a','--x','b'],['x']),e=>e.code==='INVALID_ARGUMENTS'));
