'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');const {client}=require('../runtime/transport.cjs');const F=require('./fixture.cjs');
async function serve(fn,body){const server=http.createServer(fn);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{return await body('http://127.0.0.1:'+server.address().port+'/');}finally{await new Promise(r=>server.close(r));}}
test('real loopback HTTP client reads expected code field and keeps explicit branch',async()=>serve((req,res)=>{assert.equal(req.url,'/api/user/code?branch=default');res.end(JSON.stringify({ok:1,modules:{main:'fixture'}}));},async origin=>{const a=client(F.secret,{testOrigin:origin});const r=await a.code('default');assert.equal(r.modules.main,'fixture');}));
test('HTTP redirects are refused and never followed with credentials',async()=>serve((req,res)=>{res.statusCode=302;res.setHeader('Location','https://example.invalid');res.end();},async origin=>{await assert.rejects(client(F.secret,{testOrigin:origin}).me(),e=>e.code==='HTTP_NOT_200');}));
test('authentication rejection gets stable error without response text',async()=>serve((req,res)=>{res.statusCode=401;res.end('secret-response');},async origin=>{await assert.rejects(client(F.secret,{testOrigin:origin}).me(),e=>e.code==='HTTP_AUTH_REJECTED'&&!JSON.stringify(e).includes('secret-response'));}));
test('write deadline issues no automatic retry',async()=>{let requests=0;await serve((req,res)=>{requests++;req.resume();},async origin=>{await assert.rejects(client(F.secret,{testOrigin:origin,timeoutMs:30}).setCode('default',{main:'fixture'}),e=>e.code==='HTTP_DEADLINE');assert.equal(requests,1);});});
test('wrong branch or arbitrary test hostname is refused',()=>{assert.throws(()=>client(F.secret,{testOrigin:'http://example.invalid/'}));assert.throws(()=>client(F.secret).setCode('other',{main:'x'}));});
test('invalid JSON does not become an empty module response',async()=>serve((req,res)=>res.end('bad'),async origin=>await assert.rejects(client(F.secret,{testOrigin:origin}).me(),e=>e.code==='HTTP_JSON_INVALID')));
