'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const U=require('../tools/util.cjs'),C=require('../runtime/common.cjs'),K=require('../runtime/policy.cjs'),A=require('../tools/archive.cjs'),Pub=require('../tools/publish.cjs'),X=require('../tools/source.cjs');
function git(repo,args){return U.git(repo,args).trim();}
function repo(root,name){const p=path.join(root,name);fs.mkdirSync(p);U.git(p,['init']);U.git(p,['config','user.email','fixture@example.invalid']);U.git(p,['config','user.name','fixture']);fs.writeFileSync(path.join(p,'seed.txt'),'seed\n');U.git(p,['add','.']);U.git(p,['commit','-m','seed']);return p;}
function packet(dir,name,text='ok \n'){fs.writeFileSync(path.join(dir,name+'.stdout'),text);fs.writeFileSync(path.join(dir,name+'.stderr'),'');C.writeNew(path.join(dir,name+'.exit.json'),{status:0,signal:null,error:null});}
function make(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'subx-retry-wf-')),ref=repo(root,'ref'),compat=repo(root,'compat'),run=path.join(root,'run'),tests=path.join(root,'tests'),offline=path.join(root,'offline');for(const p of [run,tests,offline])fs.mkdirSync(p);
 const old={R:K.REFACTOR,C:K.COMPAT,T:X.SOURCE_TREE,V:X.verifyHead,load:C.loadSecret};K.REFACTOR=git(ref,['rev-parse','HEAD']);K.COMPAT=git(compat,['rev-parse','HEAD']);X.SOURCE_TREE=git(compat,['rev-parse','HEAD^{tree}']);X.verifyHead=()=>({head:K.COMPAT,tree:X.SOURCE_TREE});const source=K.COMPAT,secret={token:crypto.randomBytes(32).toString('hex')};C.loadSecret=()=>secret;
 C.writeNew(path.join(run,'source-closed.json'),{status:'SOURCE_DEFAULT_OFF_RESTORED',sourceHead:source,profileHead:null,closedHead:source,sameTreeAsSource:true,atMs:Date.now()});
 C.writeNew(path.join(tests,'summary.json'),{status:'SUBPHASE_X_RETRY_TOOL_TESTS_VERIFIED',tests:1,passed:1,failed:0,skipped:0,todo:0,cancelled:0});fs.writeFileSync(path.join(tests,'tests.tap'),'ok 1 - fixture \n');fs.writeFileSync(path.join(tests,'tests.stderr'),'');C.writeNew(path.join(tests,'tests.exit.json'),{status:0});
 for(const n of ['repository-tests','loader-regenerate','typecheck-build','typecheck-tests','jest-budget','warm-build'])packet(offline,n);C.writeNew(path.join(offline,'result.json'),{status:'SUBPHASE_X_RETRY_OFFLINE_VERIFIED'});
 const bare=path.join(root,'remote.git');U.git(root,['init','--bare',bare]);for(const p of [ref,compat])U.git(p,['remote','add','origin',bare]);fs.mkdirSync(path.dirname(path.join(ref,K.EVIDENCE)),{recursive:true});
 U.git(ref,['add','.']);if(U.textGit(ref,['status','--porcelain']))U.git(ref,['commit','-m','evidence parent']);K.REFACTOR=git(ref,['rev-parse','HEAD']);U.git(ref,['branch','-M','refactor/empire-treasury-rearchitecture']);U.git(compat,['branch','-M','compat/treasury-read-bridge-i']);U.git(ref,['push','-u','origin','HEAD']);U.git(compat,['push','-u','origin','HEAD']);
 return{root,ref,compat,run,tests,offline,source,secret,restore(){K.REFACTOR=old.R;K.COMPAT=old.C;X.SOURCE_TREE=old.T;X.verifyHead=old.V;C.loadSecret=old.load;}};}
function archived(f){return A.archive({refactor:f.ref,run:f.run,tests:f.tests,offline:f.offline,secret:'fixture'});}
test('archive includes retry attribution and no remediation rerun packets',()=>{const f=make();try{archived(f);const d=path.join(f.ref,K.EVIDENCE);assert.ok(fs.existsSync(path.join(d,'SUBPHASE-ATTRIBUTION.json')));assert.equal(fs.existsSync(path.join(d,'remediation')),false);assert.equal(C.readJson(path.join(d,'ARCHIVE-MANIFEST.json')).sourceHead,f.source);}finally{f.restore();}});
test('archive preserves exact raw stdout bytes in JSON wrapper',()=>{const f=make();try{archived(f);const j=C.readJson(path.join(f.ref,K.EVIDENCE,'tool-tests/tests.tap.json'));assert.ok(j.text.endsWith(' \n'));assert.equal(j.sha256,C.sha256(Buffer.from(j.text)));}finally{f.restore();}});
test('private module snapshots are excluded from archive',()=>{const f=make();try{for(const n of ['backup.json','candidate.json','session.json'])fs.writeFileSync(path.join(f.run,n),'PRIVATE');archived(f);for(const n of ['backup.json','candidate.json','session.json'])assert.equal(fs.existsSync(path.join(f.ref,K.EVIDENCE,'run',n)),false);}finally{f.restore();}});
test('secret in permitted evidence rejects archive',()=>{const f=make();try{fs.writeFileSync(path.join(f.run,'collector.stdout'),f.secret.token);assert.throws(()=>archived(f),e=>e.code==='SECRET_IN_ARCHIVE_INPUT');}finally{f.restore();}});
test('staging gate requires native whitespace clean evidence',()=>{const f=make();try{archived(f);const g=Pub.stageGate(f.ref,f.compat);assert.equal(g.whitespaceExceptions,0);assert.equal(g.status,'SUBPHASE_X_RETRY_STAGED_BYTES_AND_WHITESPACE_VERIFIED');}finally{f.restore();}});
test('attribution tampering is detected even when manifest hash is updated',()=>{const f=make();try{archived(f);const d=path.join(f.ref,K.EVIDENCE),name='SUBPHASE-ATTRIBUTION.json',j=C.readJson(path.join(d,name));j.status='SUBPHASE_X_RETRY_ATTRIBUTION_RECORDED';const b=Buffer.from(JSON.stringify(j,null,2)+'\n');fs.writeFileSync(path.join(d,name),b);const m=C.readJson(path.join(d,'ARCHIVE-MANIFEST.json'));m.files[name]={bytes:b.length,sha256:C.sha256(b)};fs.writeFileSync(path.join(d,'ARCHIVE-MANIFEST.json'),JSON.stringify(m,null,2)+'\n');assert.throws(()=>Pub.verifyArchive(f.ref),e=>e.code==='ATTRIBUTION_EVIDENCE_CHANGED');}finally{f.restore();}});
test('evidence commit and local bare push read back exactly',()=>{const f=make();try{archived(f);const out=path.join(f.root,'receipt.json'),r=Pub.publish(f.ref,f.compat,{out,push:true});assert.equal(r.pushed,true);assert.equal(U.remoteHead(f.ref,'refactor/empire-treasury-rearchitecture'),r.refactorHead);assert.equal(U.remoteHead(f.compat,'compat/treasury-read-bridge-i'),r.compatHead);}finally{f.restore();}});
test('unrelated staged path blocks evidence commit',()=>{const f=make();try{archived(f);fs.writeFileSync(path.join(f.ref,'other.txt'),'x\n');U.git(f.ref,['add','other.txt']);assert.throws(()=>Pub.stageGate(f.ref,f.compat),e=>e.code==='UNRELATED_CHANGES');}finally{f.restore();}});
