'use strict';
const path=require('node:path'),fs=require('node:fs'),C=require('../runtime/common.cjs'),W=require('../runtime/samples.cjs'),O=require('../runtime/observer.cjs'),R=require('./repository.cjs'),P=C.POLICY,T=require('../runtime/time-budget.cjs');
function verify(dir,compat){const issues=[],need=(x,k)=>{if(!x)issues.push(k);},s=C.optional(dir,'session.json'),attempt=C.optional(dir,'candidate-attempt.json'),writes=C.jsonl(path.join(dir,'actions.jsonl')).filter(e=>e.kind==='code-write-boundary');const ups=writes.filter(x=>x.action==='candidate'),rest=writes.filter(x=>x.action==='restore');need(ups.length<=1&&rest.length<=1&&writes.length===ups.length+rest.length&&writes.every(x=>x.runId===P.parentRunId),'WRITE_QUOTA_INVALID');const residue=['action.lock','source-close.lock'].filter(n=>fs.existsSync(path.join(dir,n)));need(!residue.length,'RESIDUAL_LOCK');for(const n of ['collector','worker']){const p=C.optional(dir,n+'-process.json');if(p)need(!C.alive(p.pid),'RESIDUAL_PROCESS');}
 let windowSelection=null;try{if(C.optional(path.join(dir,'window-selection'),'start.json'))windowSelection=require('../runtime/window-selection.cjs').verifySelection(dir);}catch(e){issues.push(C.code(e));}let sourceOff=false;try{R.closed(compat);sourceOff=true;}catch{}need(sourceOff,'SOURCE_OFF_UNCONFIRMED');if(!attempt){need(ups.length===0&&rest.length===0,'NO_MARKER_WITH_WRITES');const r={status:'NOT_DEPLOYED',captureVerified:false,closure:'NOT_DEPLOYED',terminationReason:C.optional(dir,'execution-failure.json')?.error||null,sourceOff,windowSelection,rawReports:0,acceptedReports:0,completeSamples:0,writeBoundaries:{candidate:ups.length,restore:rest.length},issues,atMs:Date.now()};return r;}
 need(!!s&&s.runId===P.parentRunId&&s.packageFingerprint===C.verifyPackage().fingerprint,'SESSION_INVALID');if(!s)C.fail('CANDIDATE_WITHOUT_SESSION');need(C.same(s.profile,R.profileFor(s.observedTick)),'PROFILE_BINDING_CHANGED');need(s.source?.base===P.compatBase&&s.source?.tree===R.manifest().expectedSourceTree,'SOURCE_IDENTITY_CHANGED');try{R.verifyImplementation(compat);need(s.source.head===P.compatBase&&s.source.sourceModified===false&&R.tree(compat,s.source.head)===P.compatBaseTree,'SOURCE_COMMIT_INVALID');need(R.text(compat,['show','-s','--format=%P',s.profileHead])===s.source.head&&C.same(R.paths(compat,s.source.head,s.profileHead),[R.CONFIG]),'ON_COMMIT_INVALID');}catch{issues.push('SOURCE_GIT_OBJECT_UNAVAILABLE');}
 let timeAdmission=null;try{timeAdmission=T.verifyRun(dir,s,attempt);}catch(e){issues.push(C.code(e));}
 need(attempt.runId===P.parentRunId&&attempt.candidateHash===s.candidateDigest?.hash&&attempt.profileHead===s.profileHead&&ups.length===1&&ups[0].atMs>=attempt.atMs,'CANDIDATE_MARKER_INVALID');const rm=C.optional(dir,'restore-attempt.json');if(rest.length)need(rm?.runId===P.parentRunId&&rm.candidateHash===s.candidateDigest.hash&&rm.backupHash===P.backupDigest.hash&&rest[0].atMs>=rm.atMs,'RESTORE_MARKER_INVALID');const u=C.optional(dir,'upload-result.json');need(u?.confirmed===true&&u.accepted===true&&C.same(u.digest,s.candidateDigest),'UPLOAD_UNCONFIRMED');
 const w=W.watch(s),events=C.jsonl(path.join(dir,'console.jsonl'));let auth=0,last=-1;const start=events.filter(e=>e.kind==='collector-start'),footer=events.filter(e=>e.kind==='collector-footer'),cp=C.optional(dir,'collector-process.json'),ce=C.optional(dir,'collector-exit.json');need(start.length===1&&footer.length===1&&events.at(-1)===footer[0]&&footer[0]?.reason==='REQUESTED_STOP','COLLECTOR_TERMINAL_INVALID');need(cp&&ce?.pid===cp.pid&&ce?.code===0,'COLLECTOR_EXIT_UNCONFIRMED');for(const e of events){need(e.runId===P.parentRunId&&e.pid===cp?.pid&&Number.isSafeInteger(e.atMs)&&e.atMs>=last,'FRAME_IDENTITY_OR_TIME_INVALID');last=e.atMs;if(e.kind==='auth-confirmed'){auth++;continue;}if(e.kind!=='ws-frame')continue;need(e.redacted===false,'REDACTED_EVIDENCE');if(auth===1){w.frame(e.text,e.atMs);if(e.atMs<attempt.atMs&&e.text.includes('treasury-legacy-read-bridge'))issues.push('PRE_UPLOAD_REPORT');}}
 need(auth===1,'AUTH_SEQUENCE_INVALID');need(w.accepted.length===4,'FOUR_REPORTS_REQUIRED');if(P.fullCostMeasurement)need(w.costs.length===4,'FOUR_COST_RECEIPTS_REQUIRED');const st=w.state();need(st.deploySeen,'DEPLOY_FRAME_MISSING');issues.push(...st.issues);const closing=C.optional(dir,'closing.json'),wr=C.optional(dir,'worker-result.json'),we=C.optional(dir,'worker-exit.json'),wp=C.optional(dir,'worker-process.json');need(wr?.reason==='FOUR_REPORTS_CAPTURED'&&we?.code===0&&we?.pid===wp?.pid,'GUARD_DID_NOT_COMPLETE');const off=C.optional(dir,'source-closed.json');need(off?.sameTreeAsSource===true&&off.sourceHead===s.source.head&&off.closedHead===R.head(compat),'SOURCE_CLOSURE_INVALID');
 if(closing){const con=[],cpu=[];for(const e of events){if(e.kind!=='ws-frame')continue;let f;try{f=JSON.parse(e.text);}catch{continue;}if(!Array.isArray(f))continue;if(f[0]===`user:${P.expected.userId}/console`&&f[1]?.shard==='shard1')con.push(e.atMs);if(f[0]===`user:${P.expected.userId}/cpu`&&Number.isFinite(f[1]?.cpu))cpu.push(e.atMs);}need(O.gap(con,attempt.atMs,closing.atMs)<=45000&&O.gap(cpu,attempt.atMs,closing.atMs)<=45000,'OBSERVATION_CHANNEL_GAP');}else issues.push('CLOSING_BOUNDARY_MISSING');
 const uploadOutcomeResolved=!!(u?.confirmed===true||rm);let runtime=null,closure='ONLINE_CLOSE_UNCONFIRMED';const recovery=path.join(dir,'recovery'),before=C.optional(recovery,'code-before-runtime.json'),after=C.optional(recovery,'code-after-runtime.json');const original=x=>x?.state==='CURRENT_IS_BACKUP'&&C.same(x.digest,P.backupDigest)&&x.build?.commit===P.backupBuild.commit&&x.build?.tree===P.backupBuild.tree&&Number.isSafeInteger(x.atMs);
 if(original(after)||original(before))closure='RESTORED_BYTES_RUNTIME_UNCONFIRMED';try{runtime=O.verify(recovery);const r=C.json(path.join(recovery,'runtime-result.json'));if(!uploadOutcomeResolved||r.invocationId!==P.parentRunId||!Number.isSafeInteger(r.pid)||r.pid<=0||!/^[a-f0-9]{32}$/.test(r.closureId)||!original(before)||!original(after)||before.atMs>r.createdAtMs||after.atMs<r.endedAtMs)C.fail('RECOVERY_BYTE_TIME_ORDER');closure='RESTORED_BYTES_AND_RUNTIME_VERIFIED';}catch{runtime=null;}need(closure==='RESTORED_BYTES_AND_RUNTIME_VERIFIED','RECOVERY_NOT_CLOSED');
 const rawSummary=w.raw.map(r=>{let t=null,error=null;try{t=W.trace(r.cpuProfile);}catch(e){error=C.code(e);}let taskTrace=null,taskTraceError=null;try{taskTrace=require('../runtime/task-trace.cjs').taskTrace(r.cpuProfile);}catch(e){taskTraceError=C.code(e);}return {tick:r.tick,prefix:r.cpuBeforeSerializationAndEmit,reportedCalls:r.cpuProfile?.calls||null,trace:t,traceError:error,taskTrace,taskTraceError,preCommitmentCpu:r.cpuProfile?.commitmentEnvelope?.marks?.parentStart??null,phaseIntervals:r.cpuProfile?.phases||null,work:r.cpuProfile?.attribution?.work||null,accepted:w.accepted.includes(r),claimedComplete:w.accepted.includes(r)&&W.complete(r)};});
 return {status:issues.length?'CPU_DIAGNOSTIC_CAPTURE_INCONCLUSIVE':'CPU_DIAGNOSTIC_CAPTURE_VERIFIED',captureVerified:issues.length===0,closure,runtime,uploadOutcomeResolved,sourceOff,windowSelection,timeAdmission,terminationReason:wr?.reason||null,sourceHead:s.source.head,profileHead:s.profileHead,rawReports:w.raw.length,acceptedReports:w.accepted.length,completeSamples:st.complete,duplicates:st.duplicates,expectedTicks:[0,1,2,3].map(i=>s.profile.startTick+100*i),acceptedTicks:w.accepted.map(x=>x.tick),rawSummary,costReceipts:w.costs,measurementProtocol:P.measurementProtocol||null,completedTailProfiles:w.tails,writeBoundaries:{candidate:ups.length,restore:rest.length},issues:[...new Set(issues)],engineCpuGapRepaired:false,fullCompatibilityObserved:false,rootCauseAssigned:false,atMs:Date.now()};}
module.exports={verify};if(require.main===module)C.cli(async()=>{const o=C.options(['run','compat','out']);C.requireArgs(o,['run','compat','out']);C.verifyPackage();const r=verify(o.run,o.compat);C.durable(o.out,r);console.log(JSON.stringify(r));});
