'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const H=require('./reader-fixture.cjs'),W=require('../runtime/samples.cjs'),C=require('../runtime/common.cjs');
function run(opts={}){const f=H.fixture({probeCost:.001,...opts}),profile={...H.profile(),endTick:400},preview=H.loadReader().exports.createTreasuryCompatPreview(profile,f.ports,{cpuDiagnostics:true});for(const t of [100,200,300,400]){f.setTime(t);preview.run();}return{f,profile,preview,reports:f.logs.map(JSON.parse)};}
test('IX real preview emits four complete reports in synthetic low-cost run',()=>{const x=run();assert.equal(x.reports.length,4);assert.ok(x.reports.every(r=>r.status==='sampled'));});
test('each complete synthetic report has nine intervals and 12 boundaries',()=>{for(const r of run().reports){assert.equal(r.cpuProfile.attribution.boundaries,12);assert.deepEqual(Object.keys(r.cpuProfile.attribution.intervals),W.SUBPHASES);}});
test('projection work is exactly four rows and sixteen index queries',()=>{for(const r of run().reports){const w=r.cpuProfile.attribution.work;assert.equal(w.projectionRowsPlanned,4);assert.equal(w.projectionRowsCompleted,4);assert.equal(w.projectionIndexQueries,16);}});
test('complete synthetic reports pass unchanged diagnostic and sample validators',()=>{const x=run();for(const [i,r] of x.reports.entries()){assert.equal(W.diagnosticError(r,x.profile,i,x.reports[i-1]||null,i?x.f.logs[i-1]:null),null);assert.equal(W.sampleError(r,x.profile),null);}});
test('attribution remains nested in parent phases',()=>{for(const r of run().reports){const a=r.cpuProfile.attribution.intervals,p=r.cpuProfile.phases;assert.ok(Object.values(a).reduce((n,v)=>n+v,0)>0);assert.ok(p.observationBuild>0);assert.ok(p.commitmentBuild>0);}});
test('CPU-port reads do not scale with task count in synthetic fixture',()=>{const a=run(),b=run();for(let i=0;i<256;i++)b.f.memory.data.resourceControl.tasks['t'+i]={};assert.equal(a.reports[0].cpuProfile.attribution.boundaries,b.reports[0].cpuProfile.attribution.boundaries);});
test('diagnostics disabled produces no cpuProfile',()=>{const f=H.fixture(),p={...H.profile(),endTick:400},v=H.loadReader().exports.createTreasuryCompatPreview(p,f.ports,{cpuDiagnostics:false});f.setTime(100);v.run();assert.equal(JSON.parse(f.logs[0]).cpuProfile,undefined);});
test('default OFF performs no reads and emits nothing',()=>{const f=H.fixture(),p={...H.profile(),enabled:false},v=H.loadReader().exports.createTreasuryCompatPreview(p,f.ports,{cpuDiagnostics:true});assert.equal(v.run().status,'disabled');assert.equal(f.calls.memory,0);assert.equal(f.logs.length,0);});
test('partial budget retains useful attribution without becoming complete',()=>{const x=run({cost:{commitmentBuild:2.2}});for(const r of x.reports){assert.equal(r.status,'partial_cpu_budget');assert.equal(W.sampleError(r,x.profile),'SAMPLE_NOT_COMPLETE');assert.ok(r.cpuProfile.attribution.boundaries>=10);}});
test('unknown attribution work key faults only the preview',()=>{const f=H.fixture(),old=f.ports.readers;f.ports.readers=()=>{const x=old();const bo=x.buildObservation;x.buildObservation=o=>{o.compatDiagnostics?.work({badKey:1});return bo(o);};return x;};const v=H.loadReader().exports.createTreasuryCompatPreview(H.profile(),f.ports,{cpuDiagnostics:true});f.setTime(100);assert.equal(v.run().status,'fault_disabled');assert.equal(f.memory.data.resourceControl.tasks instanceof Object,true);});
test('IX reference core and CPU files match source lock',()=>{const root=path.resolve(__dirname,'..'),l=require('../references/source-lock.json');for(const rel of ['src/runtime/treasuryCompatReadCore.generated.ts','src/runtime/treasuryCompatCpu.ts']){const b=fs.readFileSync(path.join(root,'references',path.basename(rel)));assert.equal(C.blob(b),l[rel].blob);}});
