'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const C=require('../runtime/common.cjs'),R=require('../tools/remediate.cjs'),U=require('../tools/util.cjs');
const ROOT=path.resolve(__dirname,'..');
function assembled(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'genx-'));fs.cpSync(path.join(ROOT,'references/subphase-IX'),d,{recursive:true});for(const rel of ['docs/treasury-compat-loader-optimization.json','docs/treasury-compat-source-manifest.json','scripts/build-treasury-compat-loader.cjs','test/treasury-compat/attribution.spec.cjs','docs/treasury-compat-source-manifest-remediation-x.md']){const src=path.join(ROOT,'remediation/implementation',rel);if(fs.existsSync(src)){const dst=path.join(d,rel);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst);}}return d;}
test('remediation generator parses and exports full-output verifier',()=>{const d=assembled(),g=require(path.join(d,'scripts/build-treasury-compat-loader.cjs'));assert.equal(typeof g.verifyOutputIdentities,'function');assert.equal(g.EXPECTED_OUTPUT_PATHS.length,13);});
test('stale IX manifest and provenance are corrected deterministically by generator',()=>{const base=assembled(),g=require(path.join(base,'scripts/build-treasury-compat-loader.cjs'));const out=g.generate(fs.readFileSync(path.join(base,g.FIXTURE)),fs.readFileSync(path.join(base,g.TEMPLATE)),JSON.parse(fs.readFileSync(path.join(base,g.SOURCE_MANIFEST))));const m=JSON.parse(out[g.SOURCE_MANIFEST]);assert.equal(m.loaderOptimization.sourceManifestOutputValidation,'all-listed-outputs');assert.equal(m.outputs.find(x=>x.file==='src/runtime/treasuryCompatRuntime.ts').bytes,865);assert.equal(out[g.PROVENANCE].equals(fs.readFileSync(path.join(ROOT,'remediation/implementation',g.PROVENANCE))),true);});
test('remediation payload changed byte is rejected',()=>{const row=R.LOCK.changes[0],p=path.join(ROOT,'remediation/implementation',row.path),b=fs.readFileSync(p);fs.writeFileSync(p,Buffer.concat([b,Buffer.from('x')]));try{assert.throws(()=>R.verifyPayload(),e=>e.code==='REMEDIATION_PAYLOAD_CHANGED');}finally{fs.writeFileSync(p,b);}});
test('run-tests requires exact test contract',()=>{const c=require('../references/test-contract.json'),files=fs.readdirSync(path.join(ROOT,'tests')).filter(x=>x.endsWith('.spec.cjs')).sort().map(x=>'tests/'+x);assert.deepEqual(files,c.files);});
test('package verifier rejects an extra file in a copy',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pkgx-'));fs.cpSync(ROOT,tmp,{recursive:true});fs.writeFileSync(path.join(tmp,'extra.txt'),'x');const r=cp.spawnSync(process.execPath,['-e',`require(${JSON.stringify(path.join(tmp,'tools/util.cjs'))}).verifyPackage()`],{encoding:'utf8'});assert.notEqual(r.status,0);});
test('CLI argument parser rejects duplicates',()=>assert.throws(()=>C.options(['--x','a','--x','b'],['x']),e=>e.code==='INVALID_ARGUMENTS'));
