'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),os=require('node:os');const C=require('../tools/common.cjs'),W=require('../tools/workflow.cjs');
const tmp=()=>C.fs.mkdtempSync(C.path.join(os.tmpdir(),'compat-cpu-I-'));
test('pinned baseline files match independently retrieved Git blob identities',()=>{const m=C.read(C.path.join(C.ROOT,'references/source-lock.json'));for(const[n,sha]of Object.entries(m.baselineBlobs)){const b=C.fs.readFileSync(C.path.join(C.ROOT,'baseline',n));assert.equal(C.blob(b),sha,n);}});
test('implementation changes the three source files and exact repository sandbox helper',()=>{assert.deepEqual(C.sourcePlan().map(x=>x.path).sort(),['src/runtime/treasuryCompatCpu.ts','src/runtime/treasuryCompatRead.ts','src/runtime/treasuryCompatRuntime.ts','test/treasury-compat/helpers.cjs']);const m=C.read(C.path.join(C.ROOT,'references/source-lock.json'));assert.equal(m.protectedBlobs['src/runtime/treasuryCompatReadCore.generated.ts'],'c44d8a306f2b11986c6556e098be7d2e10315fa6');});
test('fixed byte application succeeds against the exact baseline and is not rerunnable',()=>{const root=tmp();try{C.fs.cpSync(C.path.join(C.ROOT,'baseline'),root,{recursive:true});W.applyBytes(root,C.sourcePlan());for(const e of C.sourcePlan())assert.ok(C.fs.readFileSync(C.path.join(root,e.path)).equals(e.bytes));assert.throws(()=>W.applyBytes(root,C.sourcePlan()),{code:'NEW_FILE_EXISTS'});}finally{C.fs.rmSync(root,{recursive:true,force:true});}});
test('write failure rolls back original CRLF bytes and the newly created file',()=>{const root=tmp(),write=C.fs.writeFileSync;try{C.fs.cpSync(C.path.join(C.ROOT,'baseline'),root,{recursive:true});const file=C.path.join(root,'src/runtime/treasuryCompatRead.ts');C.fs.writeFileSync(file,C.fs.readFileSync(file,'utf8').replace(/\n/g,'\r\n'));const before=C.fs.readFileSync(file);let failed=false;C.fs.writeFileSync=(p,...args)=>{if(!failed&&String(p).endsWith('treasuryCompatRuntime.ts')){failed=true;throw new Error('injected write failure');}return write(p,...args);};assert.throws(()=>W.applyBytes(root,C.sourcePlan()));assert.ok(C.fs.readFileSync(file).equals(before));assert.equal(C.fs.existsSync(C.path.join(root,'src/runtime/treasuryCompatCpu.ts')),false);}finally{C.fs.writeFileSync=write;C.fs.rmSync(root,{recursive:true,force:true});}});
test('paths with parent traversal or absolute paths are refused',()=>{const root=tmp();try{for(const p of ['../outside','a/../../outside','/absolute','a//b'])assert.throws(()=>C.assertInside(root,p),{code:'PATH_INVALID'});}finally{C.fs.rmSync(root,{recursive:true,force:true});}});
test('package inventory is locale-order independent but exact in case and bytes',()=>{const root=tmp(),scan=C.files;try{C.put(C.path.join(root,'Z-upper.txt'),'upper');C.put(C.path.join(root,'a-lower.txt'),'lower');const m={files:{}};for(const n of ['a-lower.txt','Z-upper.txt']){const b=C.fs.readFileSync(C.path.join(root,n));m.files[n]={bytes:b.length,sha256:C.sha(b)};}C.put(C.path.join(root,'INTEGRITY.json'),m);assert.equal(C.integrity(root).files,2);C.fs.appendFileSync(C.path.join(root,'a-lower.txt'),'tampered');assert.throws(()=>C.integrity(root),{code:'PACKAGE_BYTES_MISMATCH'});}finally{C.files=scan;C.fs.rmSync(root,{recursive:true,force:true});}});
test('package verifier rejects extra and missing files',()=>{const root=tmp();try{C.put(C.path.join(root,'INTEGRITY.json'),{files:{}});C.put(C.path.join(root,'unexpected'),'x');assert.throws(()=>C.integrity(root),{code:'PACKAGE_FILE_SET_MISMATCH'});}finally{C.fs.rmSync(root,{recursive:true,force:true});}});
test('build environment clears deployment targets and node injection',()=>{const old={};for(const k of ['DEST','DEPLOY_ALLOW_DIRTY','NODE_OPTIONS']){old[k]=process.env[k];process.env[k]='DO_NOT_EXECUTE';}try{const e=C.safeEnv();assert.equal(e.DEST,undefined);assert.equal(e.DEPLOY_ALLOW_DIRTY,undefined);assert.equal(e.NODE_OPTIONS,undefined);}finally{for(const[k,v]of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}});
test('local patches apply and match the full replacement payloads',()=>{const root=tmp();try{C.fs.cpSync(C.path.join(C.ROOT,'baseline'),root,{recursive:true});C.git(root,['init','-q']);for(const n of ['0001-reader-cpu-accounting.patch','0002-repository-sandbox-import.patch']){C.git(root,['-c','core.autocrlf=false','-c','core.eol=lf','apply','--check',C.path.join(C.ROOT,'patches',n)]);C.git(root,['-c','core.autocrlf=false','-c','core.eol=lf','apply',C.path.join(C.ROOT,'patches',n)]);}for(const e of C.sourcePlan())assert.ok(C.fs.readFileSync(C.path.join(root,e.path)).equals(e.bytes));}finally{C.fs.rmSync(root,{recursive:true,force:true});}});
test('offline execution surface contains no Screeps transport or write clients',()=>{for(const n of ['tools/common.cjs','tools/workflow.cjs','tools/characterize.cjs','tools/run.cjs']){const s=C.fs.readFileSync(C.path.join(C.ROOT,n),'utf8');assert.equal(/require\(['"](?:node:)?(?:https?|net|tls|ws)['"]\)/.test(s),false,n);assert.equal(/\b(?:fetch|WebSocket)\s*\(/.test(s),false,n);assert.equal(/\.secret\.json/.test(s),false,n);}});
test('archive assembler and staged verifier agree on a real temporary Git index with autocrlf',()=>{const root=tmp(),old={compat:C.COMPAT,ref:C.REF};try{
 const repo=C.path.join(root,'refactor'),compat=C.path.join(root,'compat'),tests=C.path.join(root,'tests'),checks=C.path.join(root,'checks'),ch=C.path.join(root,'characterization');
 for(const [r,b]of [[repo,C.REFBRANCH],[compat,C.BRANCH]]){C.fs.mkdirSync(r);C.git(r,['init','-q','-b',b]);C.git(r,['config','user.email','fixture@example.invalid']);C.git(r,['config','user.name','Fixture']);C.git(r,['config','core.autocrlf','true']);C.put(C.path.join(r,'seed'),'seed\n');if(r===compat)C.fs.cpSync(C.path.join(C.ROOT,'baseline'),r,{recursive:true});C.git(r,['add','.']);C.git(r,['commit','-qm','fixture base']);}
 C.COMPAT=C.gt(compat,['rev-parse','HEAD']);C.REF=C.gt(repo,['rev-parse','HEAD']);W.applyBytes(compat,C.sourcePlan());C.git(compat,['add','--',...C.sourcePlan().map(e=>e.path)]);C.git(compat,['commit','-qm','fixed reader payload']);
 const count=C.read(C.path.join(C.ROOT,'references/test-set.json')).tests;
 C.put(C.path.join(tests,'summary.json'),{status:'COMPAT_CPU_IMPLEMENTATION_OFFLINE_VERIFIED',tests:count,packageFingerprint:C.sha(C.fs.readFileSync(C.path.join(C.ROOT,'INTEGRITY.json')))});C.put(C.path.join(tests,'tests.stdout'),'# pass '+count+'\n# fail 0\n');
 C.put(C.path.join(checks,'summary.json'),{status:'COMPAT_FULL_OFFLINE_CHECKS_VERIFIED'});for(const n of ['repository-tests','typecheck-build','typecheck-test','jest-budget','build-only'])C.put(C.path.join(checks,n+'.exit.json'),{code:0});
 C.put(C.path.join(ch,'characterization.json'),{status:'REAL_PINNED_CORE_OFFLINE_CHARACTERIZED',generatedBlob:'c44d8a306f2b11986c6556e098be7d2e10315fa6',engineCpuGapRepaired:false,scenarios:Array.from({length:10},()=>({offByteEquivalent:true,diagnosticSemanticEquivalent:true}))});
 const R=require('../tools/run.cjs');R.archive({compat,refactor:repo,tests,characterization:ch,checks,out:C.path.join(root,'archive-result.json')});assert.equal(R.verifyArchive(repo).status,'COMPAT_CPU_ARCHIVE_BYTES_VERIFIED');
 C.git(repo,['add',C.TARGET]);assert.equal(R.verifyArchive(repo,true).staged,true);
 C.fs.appendFileSync(C.path.join(repo,C.TARGET,'EXECUTION-REPORT.md'),'tamper');assert.throws(()=>R.verifyArchive(repo),{code:'ARCHIVE_BYTES_MISMATCH'});
 }finally{C.COMPAT=old.compat;C.REF=old.ref;C.fs.rmSync(root,{recursive:true,force:true});}});
