'use strict';
const C=require('./common.cjs'),P=C.POLICY;
const PHASES=['legacyInputs','directRead','readerLoad','observationBuild','coreCompare','commitmentBuild','commitmentProjection','report','serializationAndSize','emit','retention'];
const CALLS=['readerLoad','observationBuild','commitmentBuild'];
const SUB=['observationSetup','observationRooms','observationFinalize','observationView','commitmentSetup','commitmentTasks','commitmentReservations','commitmentFinalize','projectionRows'];
const WORK=['observationRooms','observationLocations','observationExistingLocations','observationResourceKeys','commitmentTaskRecords','commitmentPendingTaskRecords','commitmentTaskInvalidEvents','commitmentDemandHealthChecks','commitmentReceiverHealthChecks','commitmentRouteCandidates','commitmentReservationRecords','commitmentReservationInvalidEvents','commitmentOwnerEvaluations','commitmentActiveReservations','commitmentScopeBuckets','commitmentRoomBuckets','commitmentMergeRoutes','commitmentReservationScopes','projectionRowsPlanned','projectionRowsCompleted','projectionIndexQueries'];
const MARKS=['parentStart','callStart','bodyStart','bodyEnd','callEnd','parentEnd'];
const SEGMENTS=['callerPreparation','callEntryBeforeFirstBodyBoundary','measuredBody','returnAfterLastBodyBoundary','callerPostlude'];
const nn=x=>Number.isSafeInteger(x)&&x>=0,fin=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0;
const sameKeys=(a,b)=>C.obj(a)&&C.same(Object.keys(a).sort(),[...b].sort());
const near=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-7*Math.max(1,Math.abs(a),Math.abs(b));
const need=(x,k)=>{if(!x)C.fail(k);};
function decode(text){return text.replace(/&(quot|apos|lt|gt|amp|#\d+|#[xX][a-fA-F0-9]+);/g,(_,k)=>{const m={quot:'"',apos:"'",lt:'<',gt:'>',amp:'&'};if(k[0]!=='#')return m[k];const hex=/^#[xX]/.test(k),digits=k.slice(hex?2:1),n=parseInt(digits,hex?16:10);need(digits.length<=8&&n>0&&n<=0x10ffff&&(n<0xd800||n>0xdfff),'CONSOLE_ENTITY_INVALID');return String.fromCodePoint(n);});}
function parse(text){if(typeof text!=='string')return null;need(Buffer.byteLength(text)<=1048576,'CONSOLE_LINE_TOO_LARGE');let obj,json=text;try{obj=JSON.parse(json);}catch{if(!text.includes('treasury-'))return null;json=decode(text);try{obj=JSON.parse(json);}catch{C.fail('BRIDGE_JSON_INVALID');}}return {obj,json};}
function trace(profile){const e=profile?.commitmentEnvelope;need(e?.version===1&&C.obj(e.marks),'COMMITMENT_ENVELOPE_MISSING');const m=e.marks,keys=Object.keys(m);need(keys.every(k=>MARKS.includes(k))&&keys.every(k=>fin(m[k])&&m[k]<=profile.elapsed+1e-7),'ENVELOPE_MARK_INVALID');let last=-1;for(const k of MARKS){if(Object.hasOwn(m,k)){need(m[k]>=last,'ENVELOPE_MARK_REGRESSION');last=m[k];}}
 if(profile.calls.commitmentBuild===0){need(e.status==='not_called'&&!['bodyStart','bodyEnd','callEnd'].some(k=>Object.hasOwn(m,k)),'ENVELOPE_WITHOUT_CALL');if(Object.hasOwn(m,'parentStart')&&Object.hasOwn(m,'parentEnd'))need(near(m.parentEnd-m.parentStart,profile.phases.commitmentBuild),'ENVELOPE_PARENT_SUM');return {status:'not_called',parentInterval:profile.phases.commitmentBuild??null,actualCallCost:null};}
 need(e.status==='complete'&&sameKeys(m,MARKS),'ENVELOPE_INCOMPLETE');const total=m.parentEnd-m.parentStart,body=m.bodyEnd-m.bodyStart;
 need(near(total,profile.phases.commitmentBuild),'ENVELOPE_PARENT_SUM');need(SUB.slice(4,8).every(k=>fin(profile.attribution?.intervals[k])),'ENVELOPE_BODY_SUBPHASE_MISSING');const covered=SUB.slice(4,8).reduce((n,k)=>n+profile.attribution.intervals[k],0);need(near(body,covered),'ENVELOPE_BODY_SUM');const segments={};for(let i=0;i<SEGMENTS.length;i++)segments[SEGMENTS[i]]=m[MARKS[i+1]]-m[MARKS[i]];need(near(Object.values(segments).reduce((n,v)=>n+v,0),total),'ENVELOPE_PARTITION_SUM');return {status:'complete',segments,parentInterval:total,callInterval:m.callEnd-m.callStart,measuredBody:body,outsideMeasuredBody:total-body,rootCause:'unattributed interval, not a function-level causal verdict'};}
function profile(p,tick,ordinal){need(p?.version===1&&p.tick===tick&&p.sampleOrdinal===ordinal&&p.boundary==='beforeSerialization'&&fin(p.elapsed)&&nn(p.checkpoints)&&p.checkpoints>=1&&p.checkpoints<=100,'CPU_PROFILE_IDENTITY');need(sameKeys(p.calls,CALLS)&&CALLS.every(k=>[0,1].includes(p.calls[k]))&&p.calls.commitmentBuild<=p.calls.observationBuild&&p.calls.observationBuild<=p.calls.readerLoad,'CPU_CALLS_INVALID');need(C.obj(p.phases)&&Object.keys(p.phases).every(k=>PHASES.includes(k)&&fin(p.phases[k]))&&Object.hasOwn(p.phases,'legacyInputs')&&near(Object.values(p.phases).reduce((n,x)=>n+x,0),p.elapsed),'CPU_PHASE_SUM_INVALID');need(['serializationAndSize','emit','retention'].every(k=>!p.phases[k]),'FUTURE_COST_IN_PREFIX');if(p.attribution){const a=p.attribution;need(a.version===1&&nn(a.boundaries)&&a.boundaries<=12&&a.active===null&&C.obj(a.intervals)&&C.obj(a.work),'ATTRIBUTION_IDENTITY_INVALID');need(Object.keys(a.intervals).every(k=>SUB.includes(k)&&fin(a.intervals[k]))&&Object.keys(a.work).every(k=>WORK.includes(k)&&nn(a.work[k])),'ATTRIBUTION_VALUES_INVALID');if(p.calls.observationBuild)need(SUB.slice(0,4).every(k=>Object.hasOwn(a.intervals,k))&&a.boundaries>=5,'OBSERVATION_ATTRIBUTION_INCOMPLETE');else need(!SUB.slice(0,4).some(k=>Object.hasOwn(a.intervals,k)),'OBSERVATION_WITHOUT_CALL');if(p.calls.commitmentBuild)need(a.boundaries===12&&SUB.slice(4).every(k=>Object.hasOwn(a.intervals,k)),'COMMITMENT_ATTRIBUTION_INCOMPLETE');else need(!SUB.slice(4).some(k=>Object.hasOwn(a.intervals,k)),'COMMITMENT_WITHOUT_CALL');need((a.work.projectionRowsCompleted??0)<=(a.work.projectionRowsPlanned??0),'PROJECTION_WORK_INVALID');}else need(!p.calls.observationBuild&&!p.calls.commitmentBuild,'ATTRIBUTION_MISSING');const t=trace(p);require('./task-trace.cjs').taskTrace(p);return t;}
function completion(prefix,tail){need(tail?.version===1&&tail.tick===prefix.tick&&tail.sampleOrdinal===prefix.sampleOrdinal&&tail.boundary==='afterRetention'&&tail.completion==='tail_only'&&tail.attribution===undefined&&tail.commitmentEnvelope===undefined&&tail.taskEnvelope===undefined,'TAIL_IDENTITY');need(C.same(tail.calls,prefix.calls)&&nn(tail.checkpoints)&&tail.checkpoints>=prefix.checkpoints&&tail.checkpoints<=100&&fin(tail.elapsed)&&tail.elapsed>=prefix.elapsed,'TAIL_EXTENSION_INVALID');need(sameKeys(tail.phases,['serializationAndSize','emit','retention'])&&Object.values(tail.phases).every(fin),'TAIL_PHASES_INVALID');need(near(prefix.elapsed+Object.values(tail.phases).reduce((n,x)=>n+x,0),tail.elapsed),'TAIL_SUM_INVALID');return {tick:prefix.tick,elapsed:tail.elapsed,phases:{...prefix.phases,...tail.phases}};}
function complete(r){if(r.status!=='sampled'||(!P.fullCostMeasurement&&r.cpuBeforeSerializationAndEmit>=2)||r.endpoints.length!==4||!C.same(r.coreObservationRooms,P.rooms))return false;for(const e of r.endpoints){const d=e.direct;if(e.directStatus!=='ok'||e.coreComparison!=='match_selected_scope'||!Array.isArray(e.coreMismatches)||e.coreMismatches.length||!d||typeof d.id!=='string'||!d.id||!nn(d.used)||!nn(d.capacity)||!Number.isSafeInteger(d.free)||!(d.used+d.free===d.capacity||(d.used>d.capacity&&d.free===0))||d.overCapacity!==(d.used>d.capacity)||typeof d.active!=='boolean'||(e.location==='terminal'?!nn(d.cooldown):d.cooldown!==null)||P.resources.some(k=>!nn(d.amounts?.[k]))||P.resources.reduce((n,k)=>n+d.amounts[k],0)>d.used)return false;}
 for(const n of ['tasks','reservations']){const t=r.legacyInputs?.[n];if(!t||!['empty','nonempty'].includes(t.status)||!nn(t.count)||t.count>256||(t.status==='empty')!==(t.count===0))return false;}
 const c=r.commitments,a=r.cpuProfile.attribution;if(c?.status!=='read_complete'||c.allTableScan!==true||c.tableLimitEach!==256||c.completeness?.complete!==true||c.completeness.globalIncomplete!==false||c.completeness.invalidRecords!==0||c.completeness.incompleteScopeCount!==0||c.rows?.length!==4||a?.boundaries!==12||a.work.projectionRowsPlanned!==4||a.work.projectionRowsCompleted!==4||a.work.projectionIndexQueries!==16)return false;
 for(const room of P.rooms)for(const resource of P.resources){const rows=c.rows.filter(x=>x.room===room&&x.resource===resource);if(rows.length!==1||rows[0].scope!=='room_not_endpoint'||rows[0].completeness!=='complete'||![rows[0].outgoing,rows[0].incoming,rows[0].productionReserved].every(nn))return false;}return true;}
function validate(r,s,i,previous,previousText){need(r?.kind==='treasury-legacy-read-bridge'&&r.tick===s.profile.startTick+i*100&&i<4,'DIAGNOSTIC_TICK_INVALID');need(['sampled','partial_cpu_budget'].includes(r.status),'DIAGNOSTIC_STATUS_INVALID');need(r.diagnosticRevision==='XIV'&&r.shard==='shard1'&&r.sourceCommit==='01bd9831454950c4928df98dd8679692b55603e5'&&r.productionBase===(P.measurementSourceBaseCommit||P.backupBuild.commit),'DIAGNOSTIC_SOURCE_MISMATCH');need(r.authorizesActions===false&&r.spendable===null&&r.kernelLifecycleRun===false&&r.facadeQueryRun===false&&r.storageMode==='heap_only'&&r.evaluation==='observation_and_legacy_commitments_only'&&r.cooperativeBudget===true,'DIAGNOSTIC_AUTHORITY_CHANGED');need(C.same(r.scope?.rooms,P.rooms)&&C.same(r.scope?.resources,P.resources)&&r.scope.isEmpireTotal===false,'DIAGNOSTIC_SCOPE_CHANGED');const t=profile(r.cpuProfile,r.tick,i+1);need(fin(r.cpuBeforeSerializationAndEmit)&&near(r.cpuBeforeSerializationAndEmit,r.cpuProfile.elapsed),'PREFIX_CPU_MISMATCH');if(P.fullCostMeasurement){need(s.profile.maxSampleCpu===10&&s.profile.reserveCpu===25,'FC1_PROFILE_POLICY');need(r.status!=='sampled'||r.cpuProfile.elapsed<10,'SAMPLED_OVER_EXPOSURE_CEILING');need(r.localSafety===undefined,'FC1_EXPECTS_OUTER_SAFETY');}else{need(r.status!=='sampled'||r.cpuProfile.elapsed<2,'SAMPLED_OVER_BUDGET');need(r.localSafety?.thresholdCpu===5&&typeof r.localSafety.latched==='boolean'&&r.localSafety.scope==='preview_heap_instance'&&r.localSafety.currentCallPreempted===false,'LOCAL_SAFETY_MISSING');need(r.cpuProfile.elapsed<=P.safetyCpu&&!r.localSafety.latched,'CPU_OBSERVED_SAFETY_STOP');}let tail=null;if(!i)need(r.previousRun===null&&r.previousCpuProfile===null,'FIRST_NOT_FRESH');else{need(!!previous,'PREDECESSOR_MISSING');tail=completion(previous.cpuProfile,r.previousCpuProfile);const p=r.previousRun;need(p?.tick===previous.tick&&fin(p.cpuIncludingEmit)&&p.cpuIncludingEmit+1e-7>=previous.cpuProfile.elapsed&&p.cpuIncludingEmit<=tail.elapsed+1e-7&&p.emittedBytes===Buffer.byteLength(previousText)&&p.emittedBytes<=16384&&nn(p.retainedPrimitiveChars),'PREVIOUS_RUN_INVALID');if(!P.fullCostMeasurement)need(tail.elapsed<=P.safetyCpu,'CPU_OBSERVED_SAFETY_STOP');}
 need(Array.isArray(r.endpoints)&&r.requestedEndpointRows===4&&r.collectedEndpointRows===r.endpoints.length&&r.endpoints.length<=4&&Array.isArray(r.coreObservationRooms)&&r.coreObservationRooms.every(n=>P.rooms.includes(n))&&new Set(r.coreObservationRooms).size===r.coreObservationRooms.length,'ENDPOINT_SHAPE');const keys=new Set();for(const e of r.endpoints){const k=e.room+':'+e.location;need(P.rooms.includes(e.room)&&['storage','terminal'].includes(e.location)&&!keys.has(k),'ENDPOINT_IDENTITY');keys.add(k);need(!['mismatch','existence_mismatch'].includes(e.coreComparison),'CORE_COMPARISON_MISMATCH');}need(Buffer.byteLength(JSON.stringify(r))<=16384,'OUTPUT_TOO_LARGE');return {trace:t,tail,complete:complete(r)};}
function watch(s){const accepted=[],texts=[],raw=[],issues=[],traces=[],tails=[],costs=[];let con=null,cpu=null,positive=null,deploySeen=false,duplicates=0,safety=false;
 function frame(text,at){let f;try{f=JSON.parse(text);}catch{return;}if(!Array.isArray(f)||f.length!==2)return;const[ch,d]=f;if(ch===`user:${P.expected.userId}/cpu`&&fin(d?.cpu)){cpu=at;if(d.cpu>0)positive=at;return;}if(ch!==`user:${P.expected.userId}/console`||d?.shard!=='shard1'||!Array.isArray(d.messages?.log)||!Array.isArray(d.messages?.results))return;con=at;if(d.error||d.messages.error)issues.push('CONSOLE_RUNTIME_ERROR');for(const line of d.messages.log){if(typeof line!=='string')continue;let p;try{p=parse(line);}catch(e){issues.push(C.code(e));continue;}const plain=line.trimStart().startsWith('{')?line:decode(line);if(plain===`[deploy] ${s.build.tag}`)deploySeen=true;else if(plain.startsWith('[deploy] ')&&plain!==`[deploy] ${P.backupBuild.tag}`)issues.push('UNEXPECTED_DEPLOY');if(p?.obj?.kind==='treasury-compat-safety-stop'){safety=true;issues.push('LOCAL_SAFETY_STOP');continue;}if(p?.obj?.kind==='treasury-full-cost-sample'){
 if(!P.fullCostMeasurement){issues.push('UNEXPECTED_COST_RECEIPT');continue;}
 try{if(costs.some(x=>x.tick===p.obj.tick))C.fail('DUPLICATE_COST_RECEIPT');require('./cost-receipts.cjs').validate(p.obj,accepted[costs.length],s,costs.at(-1));costs.push(p.obj);if(p.obj.stopsFutureSamples){safety=true;issues.push('FULL_COST_SAFETY_STOP');}}catch(e){issues.push(C.code(e));}continue;
 }if(p?.obj?.kind!=='treasury-legacy-read-bridge')continue;const r=p.obj;raw.push(r);const old=accepted.findIndex(x=>x.tick===r.tick);if(old>=0){if(texts[old]!==p.json)issues.push('CONFLICTING_DUPLICATE');else duplicates++;continue;}try{const v=validate(r,s,accepted.length,accepted.at(-1),texts.at(-1));accepted.push(r);texts.push(p.json);traces.push(v.trace);if(v.tail)tails.push(v.tail);}catch(e){issues.push(C.code(e));}}}
 return {frame,accepted,raw,texts,issues,traces,tails,costs,state:()=>({costReceipts:costs.length,lastConsole:con,lastCpu:cpu,lastPositiveCpu:positive,accepted:accepted.length,raw:raw.length,complete:accepted.filter(complete).length,issues:[...new Set(issues)],deploySeen,duplicates,safety})};}
module.exports={PHASES,CALLS,SUB,WORK,MARKS,SEGMENTS,near,decode,parse,trace,profile,completion,complete,validate,watch};
