'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const C=require('../runtime/common.cjs'),ROOT=path.resolve(__dirname,'..');
const git=(r,...a)=>cp.execFileSync('git',['-c','core.autocrlf=false','-C',r,...a],{encoding:null,stdio:['ignore','pipe','pipe']});const gt=(r,...a)=>git(r,...a).toString('utf8').trim();
function integrity(root){const files={};for(const n of C.list(root).filter(n=>n!=='INTEGRITY.json')){const b=fs.readFileSync(path.join(root,n));files[n]={bytes:b.length,sha256:C.sha(b)};}fs.writeFileSync(path.join(root,'INTEGRITY.json'),JSON.stringify({kind:'package-integrity/v1',files},null,2)+'\n');}
function init(r,branch){fs.mkdirSync(r);git(r,'init','-b',branch);git(r,'config','user.name','Fixture');git(r,'config','user.email','fixture@example.invalid');}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'xiv-flow-')),pkg=path.join(root,'pkg'),repo=path.join(root,'compat'),refactor=path.join(root,'refactor');fs.cpSync(ROOT,pkg,{recursive:true});const p=JSON.parse(fs.readFileSync(path.join(pkg,'policy.json')));p.runtimeMs=40;init(repo,p.compatBranch);fs.mkdirSync(path.join(repo,'src/runtime'),{recursive:true});fs.writeFileSync(path.join(repo,'src/runtime/treasuryCompatConfig.ts'),'export const config = "OFF";\n');fs.writeFileSync(path.join(repo,'before.txt'),'base\n');git(repo,'add','.');git(repo,'commit','-m','base');p.compatBase=gt(repo,'rev-parse','HEAD');p.compatBaseTree=gt(repo,'rev-parse','HEAD^{tree}');fs.writeFileSync(path.join(repo,'before.txt'),'after\n');fs.writeFileSync(path.join(repo,'new.txt'),'new\n');git(repo,'add','.');const expectedSourceTree=gt(repo,'write-tree');const patch=git(repo,'diff','--cached','--binary','--unified=0');const files={};for(const n of ['before.txt','new.txt']){const b=fs.readFileSync(path.join(repo,n));files[n]={after:{bytes:b.length,sha256:C.sha(b)}};}fs.writeFileSync(path.join(pkg,'patches/source.patch'),patch);fs.writeFileSync(path.join(pkg,'source-manifest.json'),JSON.stringify({expectedSourceTree,files}));git(repo,'read-tree',p.compatBase);git(repo,'checkout-index','-a','-f');fs.unlinkSync(path.join(repo,'new.txt'));
 init(refactor,p.refactorBranch);fs.mkdirSync(path.dirname(path.join(refactor,p.priorRecoveryPath)),{recursive:true});fs.writeFileSync(path.join(refactor,p.priorRecoveryPath),JSON.stringify({status:'RESTORED_BYTES_AND_RUNTIME_VERIFIED'})+'\n');git(refactor,'add','.');git(refactor,'commit','-m','evidence-base');p.refactorBase=gt(refactor,'rev-parse','HEAD');p.priorRecoveryBlob=gt(refactor,'rev-parse','HEAD:'+p.priorRecoveryPath);fs.writeFileSync(path.join(pkg,'policy.json'),JSON.stringify(p,null,2)+'\n');integrity(pkg);
 const remote=path.join(root,'remote');fs.mkdirSync(remote);git(remote,'init','--bare');for(const r of [repo,refactor]){git(r,'remote','add','origin',remote);git(r,'push','-u','origin','HEAD');}
 return {root,pkg,repo,refactor,p,mod:n=>require(path.join(pkg,n)),close:()=>fs.rmSync(root,{recursive:true,force:true})};}
module.exports={integrity,fixture};
test('native apply, new-path scope, exact resume, bind and OFF close run through production tools',async()=>{const f=fixture();try{const R=f.mod('tools/repository.cjs');assert.equal(R.baseline(f.refactor,f.repo).source.state,'base');const a=R.apply(f.repo);assert.equal(a.status,'TASK_XIV_SOURCE_APPLIED');assert.equal(R.apply(f.repo).resumed,true);assert.equal(gt(f.repo,'rev-list','--count',f.p.compatBase+'..HEAD'),'1');const d=path.join(f.root,'run');fs.mkdirSync(d);const b=R.bind(f.repo,d,0);assert.equal(b.profile.startTick,200);assert.equal(b.profile.endTick,500);const off=await R.closeSource(f.repo,d);assert.equal(off.sameTreeAsSource,true);assert.deepEqual(await R.closeSource(f.repo,d),off);assert.equal(gt(f.repo,'rev-list','--count',f.p.compatBase+'..HEAD'),'3');assert.equal(git(f.repo,'status','--porcelain=v1','-z').length,0);}finally{f.close();}});
test('recovery recognizes OFF commit created before its final evidence write',async()=>{const f=fixture();try{const R=f.mod('tools/repository.cjs');R.apply(f.repo);const d=path.join(f.root,'run');fs.mkdirSync(d);const b=R.bind(f.repo,d,0);await R.closeSource(f.repo,d);fs.unlinkSync(path.join(d,'source-closed.json'));const h=R.head(f.repo);assert.equal((await R.closeSource(f.repo,d)).closedHead,h);assert.equal(R.head(f.repo),h);}finally{f.close();}});
test('foreign source changes fail closed rather than being reset or amended',()=>{const f=fixture();try{const R=f.mod('tools/repository.cjs');R.apply(f.repo);fs.writeFileSync(path.join(f.repo,'new.txt'),'foreign\n');assert.throws(()=>R.source(f.repo),/WORKTREE_NOT_CLEAN/);assert.equal(fs.readFileSync(path.join(f.repo,'new.txt'),'utf8'),'foreign\n');}finally{f.close();}});
test('one experiment authorization remains consumed across output-directory changes',()=>{const f=fixture();try{const o=f.mod('tools/observe.cjs'),a=path.join(f.root,'one'),b=path.join(f.root,'two');fs.mkdirSync(a);fs.mkdirSync(b);o.authorization(f.repo,a);assert.throws(()=>o.authorization(f.repo,b));const common=path.join(f.repo,'.git/treasury-experiments',f.p.authorizationId+'.json');assert.equal(JSON.parse(fs.readFileSync(common)).work,fs.realpathSync(a));}finally{f.close();}});
test('native evidence archive, whitespace, local bare push and idempotent republish',async()=>{const f=fixture();try{const R=f.mod('tools/repository.cjs'),A=f.mod('tools/archive.cjs');R.apply(f.repo);const work=path.join(f.root,'execution');for(const n of ['live/run','offline-checks','tool-tests'])fs.mkdirSync(path.join(work,n),{recursive:true});fs.writeFileSync(path.join(work,'offline-checks/result.json'),'{}\n');fs.writeFileSync(path.join(work,'tool-tests/result.json'),'{}\n');fs.mkdirSync(path.join(work,'offline-checks/build'));fs.symlinkSync(f.repo,path.join(work,'offline-checks/build/node_modules'),process.platform==='win32'?'junction':'dir');fs.writeFileSync(path.join(work,'live/run/backup.json'),'PRIVATE BACKUP');fs.writeFileSync(path.join(work,'live/run/candidate.json'),'PRIVATE CANDIDATE');const secret=path.join(f.root,'secret.json');fs.writeFileSync(secret,JSON.stringify({main:{hostname:'screeps.com',branch:'default',token:require('node:crypto').randomBytes(32).toString('hex')}}));const a=A.archive({compat:f.repo,refactor:f.refactor,work,secret,push:true});assert.equal(a.status,'TASK_XIV_EVIDENCE_PUSHED');const h=R.head(f.refactor);assert.equal(R.remote(f.refactor,f.p.refactorBranch),h);const archive=path.join(f.refactor,f.p.evidencePath);assert.equal(fs.existsSync(path.join(archive,'run/backup.json')),false);assert.equal(fs.existsSync(path.join(archive,'offline-checks/build')),false);assert.deepEqual(A.archive({compat:f.repo,refactor:f.refactor,work,secret,push:true}),a);assert.equal(R.head(f.refactor),h);assert.equal(git(f.refactor,'show','--format=','--check','HEAD').length,0);}finally{f.close();}});
test('secret scan ignores source field names but rejects actual raw and encoded secret forms',()=>{const A=require('../tools/archive.cjs'),token='auth-fixture-P4jG5Bbc716r';assert.doesNotThrow(()=>A.scan("const token = 'test-only'; authorization: 'fixture'",token));assert.throws(()=>A.scan('prefix '+token+' suffix',token),/SECRET_SCAN_FAILED/);assert.throws(()=>A.scan(Buffer.from(token).toString('base64'),token),/SECRET_SCAN_FAILED/);});
test('independent whole-run verifier accepts four source-generated reports only with separate valid recovery',async()=>{const f=fixture();try{const R=f.mod('tools/repository.cjs'),C=f.mod('runtime/common.cjs'),O=f.mod('runtime/observer.cjs'),V=f.mod('tools/verify.cjs');R.apply(f.repo);const d=path.join(f.root,'run');fs.mkdirSync(d);const b=R.bind(f.repo,d,0),pid=Number(cp.execFileSync(process.execPath,['-e','process.stdout.write(String(process.pid))']));const s={runId:f.p.parentRunId,packageFingerprint:C.verifyPackage().fingerprint,source:b.source,profile:b.profile,observedTick:0,profileHead:b.profileHead,profileTree:b.profileTree,build:{tag:'fixture-candidate'},candidateDigest:{hash:'fixture-hash'},backupDigest:f.p.backupDigest};const now=Date.now()-1000;
 C.durable(path.join(d,'session.json'),s);C.durable(path.join(d,'candidate-attempt.json'),{runId:f.p.parentRunId,candidateHash:s.candidateDigest.hash,profileHead:b.profileHead,atMs:now});C.durable(path.join(d,'upload-result.json'),{confirmed:true,accepted:true,digest:s.candidateDigest});C.durable(path.join(d,'restore-attempt.json'),{runId:f.p.parentRunId,candidateHash:s.candidateDigest.hash,backupHash:f.p.backupDigest.hash,atMs:now+400});C.append(path.join(d,'actions.jsonl'),{runId:f.p.parentRunId,kind:'code-write-boundary',action:'candidate',atMs:now});C.append(path.join(d,'actions.jsonl'),{runId:f.p.parentRunId,kind:'code-write-boundary',action:'restore',atMs:now+400});for(const n of ['collector','worker']){C.durable(path.join(d,n+'-process.json'),{pid});C.durable(path.join(d,n+'-exit.json'),{pid,code:0});}C.durable(path.join(d,'worker-result.json'),{reason:'FOUR_REPORTS_CAPTURED'});C.durable(path.join(d,'closing.json'),{atMs:now+399});let t=now;const write=x=>C.append(path.join(d,'console.jsonl'),{runId:f.p.parentRunId,pid,atMs:t++,...x});write({kind:'collector-start'});write({kind:'auth-confirmed'});const msg=(kind,logs=[])=>JSON.stringify([`user:${f.p.expected.userId}/${kind}`,kind==='cpu'?{cpu:1}:{shard:'shard1',messages:{log:logs,results:[]}}]);write({kind:'ws-frame',text:msg('console',['[deploy] fixture-candidate']),redacted:false});for(const r of require('../references/synthetic-four-reports.json').reports){write({kind:'ws-frame',text:msg('cpu'),redacted:false});write({kind:'ws-frame',text:msg('console',[JSON.stringify(r)]),redacted:false});}write({kind:'collector-footer',reason:'REQUESTED_STOP'});
 const recovery=path.join(d,'recovery');fs.mkdirSync(recovery);const original=()=>({state:'CURRENT_IS_BACKUP',digest:f.p.backupDigest,build:f.p.backupBuild,atMs:Date.now()});C.durable(path.join(recovery,'code-before-runtime.json'),original());class WS{constructor(){this.handlers={};setTimeout(()=>this.emit('open',{}),0);}addEventListener(k,v){(this.handlers[k]??=[]).push(v);}emit(k,x){for(const v of this.handlers[k]||[])v(x);}send(x){if(x.startsWith('auth '))setTimeout(()=>this.emit('message',{data:'auth ok'}),0);if(x.endsWith('/console'))this.timer=setInterval(()=>{this.emit('message',{data:msg('console')});this.emit('message',{data:msg('cpu')});},5);}close(){clearInterval(this.timer);}}
 await O.observe({out:recovery,secret:{token:'fixture',redact:x=>x},invocationId:f.p.parentRunId,WebSocketClass:WS,pollMs:2});C.durable(path.join(recovery,'code-after-runtime.json'),original());await R.closeSource(f.repo,d);const v=V.verify(d,f.repo);assert.deepEqual(v.issues,[]);assert.equal(v.captureVerified,true);assert.equal(v.rawReports,4);assert.equal(v.acceptedReports,4);assert.equal(v.completeSamples,4);assert.equal(v.completedTailProfiles.length,3);assert.equal(v.closure,'RESTORED_BYTES_AND_RUNTIME_VERIFIED');
 fs.writeFileSync(path.join(d,'upload-result.json'),JSON.stringify({confirmed:false,accepted:null}));fs.unlinkSync(path.join(d,'restore-attempt.json'));const ledger=C.jsonl(path.join(d,'actions.jsonl')).filter(x=>x.action!=='restore');fs.writeFileSync(path.join(d,'actions.jsonl'),ledger.map(x=>JSON.stringify(x)).join('\n')+'\n');const unresolved=V.verify(d,f.repo);assert.equal(unresolved.uploadOutcomeResolved,false);assert.equal(unresolved.closure,'RESTORED_BYTES_RUNTIME_UNCONFIRMED');assert.equal(unresolved.captureVerified,false);
 fs.unlinkSync(path.join(recovery,'runtime-result.json'));const rejected=V.verify(d,f.repo);assert.equal(rejected.captureVerified,false);assert.equal(rejected.closure,'RESTORED_BYTES_RUNTIME_UNCONFIRMED');assert.ok(rejected.issues.includes('RECOVERY_NOT_CLOSED'));}finally{f.close();}});
