'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const F=require('./fixture.cjs'),A=require('../runtime/actions.cjs'),S=require('../runtime/store.cjs'),C=require('../runtime/common.cjs'),P=require('../runtime/protocol.cjs');
async function withRun(fn){const d=F.runDir();try{await fn(d,F.makeSession());}finally{fs.rmSync(d,{recursive:true,force:true});}}
test('actual upload and restore algorithms make one POST each and compare typed readbacks',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);const u=await A.uploadOnce(w.api,F.guard,s,d);assert.equal(u.confirmed,true);assert.equal(w.writes,1);const r=await A.restoreOnce(w.api,F.guard,s,d);assert.equal(r.status,'RESTORED_AND_VERIFIED');assert.equal(w.writes,2);assert.equal((await A.restoreOnce(w.api,F.guard,s,d)).status,'ALREADY_RESTORED');assert.equal(w.writes,2);}));
test('second upload is refused by durable one-use marker',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await A.uploadOnce(w.api,F.guard,s,d);await assert.rejects(()=>A.uploadOnce(w.api,F.guard,s,d),{code:'UPLOAD_ALREADY_ATTEMPTED_OR_CLOSING'});assert.equal(w.writes,1);}));
test('profile that expires after binding cannot reach a POST',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);w.time=s.profile.startTick-99;await assert.rejects(()=>A.uploadOnce(w.api,F.guard,s,d),{code:'PROFILE_WINDOW_EXPIRED'});assert.equal(w.writes,0);assert.equal(S.optional(d,'upload-attempt.json'),null);}));
test('changed baseline blocks upload and never overwrites third-party code',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);w.modules={main:F.main('d'.repeat(40),'e'.repeat(40),'third-party')};await assert.rejects(()=>A.uploadOnce(w.api,F.guard,s,d),{code:'ONLINE_BASELINE_CHANGED'});assert.equal(w.writes,0);}));
test('third-party code after upload is a restore conflict with no second POST',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await A.uploadOnce(w.api,F.guard,s,d);w.modules={main:F.main('d'.repeat(40),'e'.repeat(40),'third-party')};assert.equal((await A.restoreOnce(w.api,F.guard,s,d)).status,'CONFLICT_CURRENT_NOT_OUR_DEPLOYMENT');assert.equal(w.writes,1);}));
test('a thrown upload request remains unknown and is never silently retried',()=>withRun(async(d,s)=>{const w=F.apiWorld(s,{onWrite:()=>{C.fail('HTTP_DEADLINE');}});const r=await A.uploadOnce(w.api,F.guard,s,d);assert.equal(r.status,'UPLOAD_UNCONFIRMED');assert.equal(r.serverAccepted,null);assert.equal(w.writes,1);}));
test('an accepted POST with a missing readback is explicitly unconfirmed',()=>withRun(async(d,s)=>{const w=F.apiWorld(s,{failReadAfterWrite:true});const r=await A.uploadOnce(w.api,F.guard,s,d);assert.equal(r.status,'UPLOAD_UNCONFIRMED');assert.equal(r.serverAccepted,true);assert.equal(w.writes,1);}));
test('uncertain upload with baseline currently visible does not prove restoration',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);S.newRecord(d,'upload-attempt.json',{runId:s.runId,candidateHash:s.candidate.digest.hash,profileHead:s.profileHead,startedAtMs:Date.now()});const r=await A.restoreOnce(w.api,F.guard,s,d);assert.equal(r.confirmed,false);assert.equal(r.reason,'UPLOAD_OUTCOME_UNRESOLVED');assert.equal(w.writes,0);}));
test('durable restore marker blocks a repeated or crashed restore request',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await A.uploadOnce(w.api,F.guard,s,d);S.newRecord(d,'restore-attempt.json',{runId:s.runId});const r=await A.restoreOnce(w.api,F.guard,s,d);assert.equal(r.reason,'RESTORE_ALREADY_ATTEMPTED');assert.equal(w.writes,1);}));
test('restore does nothing at all when no candidate upload was attempted',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);const r=await A.restoreOnce(w.api,F.guard,s,d);assert.equal(r.status,'NOT_DEPLOYED_NO_RESTORE_NEEDED');assert.equal(w.writes,0);}));
test('read-only reconciliation does not call any writer',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await A.uploadOnce(w.api,F.guard,s,d);await A.restoreOnce(w.api,F.guard,s,d);const r=await A.reconcileReadOnly(w.api,F.guard,s,d);assert.equal(r.confirmed,true);assert.equal(w.writes,2);}));
test('two simultaneous recovery calls are serialized and restore only once',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await A.uploadOnce(w.api,F.guard,s,d);const r=await Promise.all([A.restoreOnce(w.api,F.guard,s,d),A.restoreOnce(w.api,F.guard,s,d)]);assert.equal(r.filter(x=>x.requestAttempted).length,1);assert.equal(w.writes,2);}));
test('guard not ready blocks upload before durable attempt and before POST',()=>withRun(async(d,s)=>{const w=F.apiWorld(s);await assert.rejects(()=>A.uploadOnce(w.api,F.guard,s,d,()=>C.fail('GUARD_NOT_READY')),{code:'GUARD_NOT_READY'});assert.equal(w.writes,0);assert.equal(S.optional(d,'upload-attempt.json'),null);}));
test('canonical typed comparison rejects a text/binary alias',()=>{assert.equal(P.equalModules({main:'bin:AA=='},{main:'different'},F.guard),false);assert.throws(()=>P.validateModules({main:'ok',x:{binary:'not-base64'}}));});
test('branch and account identity remain fail-closed',()=>{assert.throws(()=>P.activeBranch({ok:1,list:[{branch:'other',activeWorld:true}]}),{code:'ACTIVE_WORLD_CHANGED'});assert.throws(()=>P.account({ok:1,_id:'other',username:'forster'}),{code:'ACCOUNT_MISMATCH_OR_UNREADABLE'});});
