'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const U=require('./util.cjs'),C=require('../runtime/common.cjs'),K=require('../runtime/policy.cjs'),X=require('./source.cjs'),P=require('./source-patch.cjs'),F=require('../runtime/check-profile.cjs'),R=require('./source-migration.cjs');
const M=require('../MATERIALIZATION.json');
const REF='refs/heads/compat/treasury-read-bridge-i';
function materialization(){if(!M||M.kind!=='xii-materialization/v4'||!/^[0-9a-f]{40}$/.test(M.expectedSourceTree||'')||!/^[0-9a-f]{40}$/.test(M.supersededSourceTree||''))C.fail('MATERIALIZATION_IDENTITY_INVALID');return M;}
function verifyExpectedTree(v){const m=materialization();if(v.tree!==m.expectedSourceTree)C.fail('MATERIALIZED_SOURCE_TREE_MISMATCH');return v;}
function runGenerator(repo,mode,code){const r=cp.spawnSync(process.execPath,[path.join(repo,'scripts/build-treasury-compat-loader.cjs'),mode],{cwd:repo,encoding:'utf8',timeout:120000,maxBuffer:16*1048576,windowsHide:true});if(r.status!==0||r.error)C.fail(code,{status:r.status,stderr:r.stderr});return r;}
function verifyDetachedCommit(repo,head){if(U.textGit(repo,['rev-parse',head+'^'])!==K.COMPAT)C.fail('MIGRATED_SOURCE_PARENT_INVALID');if(U.textGit(repo,['show','-s','--format=%s',head])!==X.IMPL.commitMessage)C.fail('MIGRATED_SOURCE_MESSAGE_INVALID');if(U.textGit(repo,['rev-parse',head+'^{tree}'])!==M.expectedSourceTree)C.fail('MIGRATED_SOURCE_TREE_INVALID');return head;}
function migrateSuperseded(repo,current){const m=materialization();X.verifySupersededHead(repo);F.verifySupersededFrozen(repo);if(U.remoteHead(repo,'compat/treasury-read-bridge-i')!==K.COMPAT)C.fail('REMOTE_BASELINE_CHANGED');
 const next=R.replaceBranchCommit(repo,{current,base:K.COMPAT,tree:m.expectedSourceTree,message:X.IMPL.commitMessage,ref:REF});verifyDetachedCommit(repo,next);const v=verifyExpectedTree(X.verifyHead(repo));return {status:'ENVELOPE_XII_SOURCE_SUPERSEDED_MIGRATED',...v,resumed:true,migrated:true,replacedHead:current,migrationMethod:'verified-tree-commit+update-ref-CAS+read-tree',implementationFingerprint:C.sha256(fs.readFileSync(path.join(U.ROOT,'IMPLEMENTATION-MANIFEST.json'))),atMs:Date.now()};}
function apply(repo,out){U.verifyPackage();U.outside(out,repo);if(fs.existsSync(out))C.fail('OUTPUT_ALREADY_EXISTS');const m=materialization(),current=U.textGit(repo,['rev-parse','HEAD']),tree=U.textGit(repo,['rev-parse','HEAD^{tree}']);let result;
 if(current===K.COMPAT){X.verifyBaseline(repo);if(U.remoteHead(repo,'compat/treasury-read-bridge-i')!==K.COMPAT)C.fail('REMOTE_BASELINE_CHANGED');P.write(repo);runGenerator(repo,'--write','ENVELOPE_XII_GENERATOR_WRITE_FAILED');runGenerator(repo,'--check','ENVELOPE_XII_GENERATOR_CHECK_FAILED');U.git(repo,['diff','--check']);U.git(repo,['add','--',...X.IMPL.paths]);const staged=U.textGit(repo,['diff','--cached','--name-only']).split('\n').filter(Boolean).sort();if(JSON.stringify(staged)!==JSON.stringify([...X.IMPL.paths].sort()))C.fail('IMPLEMENTATION_STAGED_SCOPE_INVALID');U.git(repo,['diff','--cached','--check']);if(U.textGit(repo,['write-tree'])!==m.expectedSourceTree)C.fail('IMPLEMENTATION_STAGED_TREE_INVALID');U.git(repo,['commit','-m',X.IMPL.commitMessage]);U.clean(repo);const v=verifyExpectedTree(X.verifyHead(repo));result={status:'ENVELOPE_XII_SOURCE_APPLIED',...v,resumed:false,migrated:false,implementationFingerprint:C.sha256(fs.readFileSync(path.join(U.ROOT,'IMPLEMENTATION-MANIFEST.json'))),atMs:Date.now()};}
 else if(tree===m.expectedSourceTree){const v=verifyExpectedTree(X.verifyHead(repo));F.verifyFrozen(repo);result={status:'ENVELOPE_XII_SOURCE_ALREADY_APPLIED',...v,resumed:true,migrated:false,implementationFingerprint:C.sha256(fs.readFileSync(path.join(U.ROOT,'IMPLEMENTATION-MANIFEST.json'))),atMs:Date.now()};}
 else if(tree===m.supersededSourceTree)result=migrateSuperseded(repo,current);
 else C.fail('LOCAL_SOURCE_STATE_UNRECOGNIZED',{head:current,tree,expectedTree:m.expectedSourceTree,supersededTree:m.supersededSourceTree});
 C.durable(out,result);return result;}
module.exports={apply,migrateSuperseded,verifyExpectedTree,verifyDetachedCommit};if(require.main===module)U.cli(async()=>{const o=U.options(['compat','out']);C.required(o,'compat','out');console.log(JSON.stringify(apply(path.resolve(o.compat),path.resolve(o.out))));});
