'use strict';
const path=require('node:path'),C=require('./common.cjs'),A=require('./actions.cjs'),W=require('./samples.cjs'),P=C.POLICY;
async function collect({dir,secret,session,WebSocketClass=global.WebSocket,pollMs=250,startupMs=90000}){if(typeof WebSocketClass!=='function')C.fail('NODE22_WEBSOCKET_REQUIRED');const w=W.watch(session),createdAtMs=Date.now(),pid=process.pid,file=path.join(dir,'console.jsonl');let socket,timer,auth=0,done=false,size=0,resolve;const result=new Promise(r=>resolve=r);const log=x=>C.append(file,{atMs:Date.now(),runId:P.parentRunId,pid,...x});
 const heartbeat=()=>C.atomic(path.join(dir,'collector-heartbeat.json'),{runId:P.parentRunId,pid,atMs:Date.now(),streaming:auth===1&&!done,...w.state()});
 function stop(reason){if(done)return;done=true;clearInterval(timer);try{socket?.close();}catch{}const r={runId:P.parentRunId,pid,reason,authentications:auth,createdAtMs,endedAtMs:Date.now(),...w.state()};try{log({kind:'collector-footer',reason});C.durable(path.join(dir,'collector-result.json'),r);}catch{}resolve(r);}
 try{log({kind:'collector-start'});socket=new WebSocketClass('wss://screeps.com/socket/websocket');socket.addEventListener('open',()=>{try{socket.send('auth '+secret.token);}catch{stop('AUTH_SEND_FAILED');}});socket.addEventListener('message',e=>{if(done)return;try{const text=typeof e.data==='string'?e.data:Buffer.from(e.data).toString('utf8');if(Buffer.byteLength(text)>1048576||(size+=Buffer.byteLength(text))>16*1048576){stop('COLLECTOR_SIZE_LIMIT');return;}if(text==='auth ok'||text.startsWith('auth ok ')){if(++auth!==1){stop('REPEATED_AUTH');return;}log({kind:'auth-confirmed'});socket.send(`subscribe user:${P.expected.userId}/console`);socket.send(`subscribe user:${P.expected.userId}/cpu`);return;}if(text.startsWith('auth ')){stop('AUTH_FAILED');return;}const safe=secret.redact(text);log({kind:'ws-frame',text:safe,redacted:safe!==text});if(safe!==text){stop('REDACTED_EVIDENCE');return;}if(auth===1)w.frame(text,Date.now());heartbeat();}catch{stop('COLLECTOR_IO_OR_FRAME_ERROR');}});socket.addEventListener('close',()=>stop('SOCKET_CLOSED'));socket.addEventListener('error',()=>stop('SOCKET_ERROR'));
 timer=setInterval(()=>{try{if(C.optional(dir,'collector-stop.json')){stop('REQUESTED_STOP');return;}if(auth!==1&&Date.now()-createdAtMs>startupMs){stop('AUTH_STARTUP_TIMEOUT');return;}heartbeat();}catch{stop('COLLECTOR_IO_ERROR');}},pollMs);
 }catch{stop('COLLECTOR_START_FAILED');}return result;}
module.exports={collect};if(require.main===module)C.cli(async()=>{const o=C.options(['run','secret']);C.requireArgs(o,['run','secret']);await collect({dir:o.run,secret:C.loadSecret(o.secret),session:A.loadSession(o.run)});});
