'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const F=require('./executor-fixtures.cjs');
function env(){const x=F.load();return{...x,s:F.session(),r:F.report()};}
test('FC1 accepted sampled report above 2 retains all original profile validation',()=>{const{W,s,r}=env();assert.doesNotThrow(()=>W.validate(r,s,0,null,null));assert.equal(W.complete(r),true);});
test('FC1 sampled report above 5 is not a legacy safety failure',()=>{const{W,s}=env(),r=F.report(0,null,6);assert.doesNotThrow(()=>W.validate(r,s,0,null,null));assert.equal(W.complete(r),true);});
test('FC1 four reports plus four separately bound cost receipts close measurement',()=>{const{W,s}=env(),w=W.watch(s);let prev=null,prevCost=null;for(let i=0;i<4;i++){const r=F.report(i,prev),c=F.cost(r,prevCost);w.frame(F.frame([r,c]),1000+i);prev=r;prevCost=c;}assert.equal(w.state().accepted,4);assert.equal(w.state().costReceipts,4);assert.equal(w.state().complete,4);assert.equal(w.state().issues.length,0);});
test('fresh external authorization is distinct from the source-fixed emitter and still accepts its receipt',()=>{const{K,policy,s,r}=env();assert.notEqual(policy.authorizationId,policy.runtimeEmitterId);const receipt=F.cost(r);assert.equal(receipt.experimentId,policy.runtimeEmitterId);assert.doesNotThrow(()=>K.validate(receipt,r,s,null));const wrong={...receipt,experimentId:policy.authorizationId};assert.throws(()=>K.validate(wrong,r,s,null),/COST_IDENTITY/);});
test('FC1 last main tail is available without fabricating a successor sample',()=>{const{K,s,r}=env(),c=F.cost(r);assert.equal(K.validate(c,r,s,null).fullMainReportTail.tick,r.tick);});
test('FC1 main reports alone are insufficient cost evidence',()=>{const{W,s}=env(),w=W.watch(s);let p=null;for(let i=0;i<4;i++){const r=F.report(i,p);w.frame(F.frame([r]),i+1);p=r;}assert.equal(w.state().accepted,4);assert.equal(w.state().costReceipts,0);});
test('FC1 does not accept a legacy localSafety block as new runtime evidence',()=>{const{W,s,r}=env();r.localSafety={thresholdCpu:5,latched:false,scope:'preview_heap_instance',currentCallPreempted:false};assert.throws(()=>W.validate(r,s,0,null,null),/FC1_EXPECTS_OUTER_SAFETY/);});
for(const [name,mutate]of [['experiment',c=>c.experimentId='old'],['tick',c=>c.tick++],['window',c=>c.windowEnd+=100],['nativeDelta',c=>c.elapsedThroughPreviewReturn++],['tailTotal',c=>c.currentTailProfile.elapsed++],['admission',c=>{c.nativeEntry.used=480;c.nativeReturn.used=483.2;}],['missingTail',c=>c.currentTailProfile=null],['policy',c=>c.policy.retainedReserveCpu=5]])test('FC1 rejects forged receipt '+name,()=>{const{K,s,r}=env(),c=F.cost(r);mutate(c);assert.throws(()=>K.validate(c,r,s,null));});
test('FC1 receipt preceding its main report is rejected, not joined speculatively',()=>{const{W,s,r}=env(),w=W.watch(s);w.frame(F.frame([F.cost(r)]),1);assert.equal(w.state().costReceipts,0);assert.ok(w.state().issues.length);});
test('FC1 duplicate receipt is a visible evidence issue',()=>{const{W,s,r}=env(),w=W.watch(s),c=F.cost(r);w.frame(F.frame([r,c,c]),1);assert.equal(w.state().costReceipts,1);assert.ok(w.state().issues.includes('DUPLICATE_COST_RECEIPT'));});
test('FC1 partial projection is never promoted by the absence of the 2-CPU line',()=>{const{W,r}=env();r.commitments.rows=[];r.status='partial_cpu_budget';r.cpuProfile.attribution.work.projectionRowsCompleted=0;r.cpuProfile.attribution.work.projectionIndexQueries=0;assert.equal(W.complete(r),false);});
test('FC1 Core mismatch still rejects the sample',()=>{const{W,s,r}=env();r.endpoints[0].coreComparison='mismatch';assert.throws(()=>W.validate(r,s,0,null,null),/CORE_COMPARISON_MISMATCH/);});
test('FC1 damaged indexes cannot become complete through new measurement policy',()=>{const{W,r}=env();r.commitments.completeness.complete=false;assert.equal(W.complete(r),false);});
test('FC1 native receipt stop state must match actual measured overshoot',()=>{const{K,s,r}=env(),c=F.cost(r);c.elapsedThroughPreviewReturn=11;c.nativeReturn.used=61;assert.throws(()=>K.validate(c,r,s,null),/COST_STOP_ACCOUNTING/);c.stopsFutureSamples=true;c.stopReason='CPU_OBSERVED_EXPOSURE_STOP';assert.doesNotThrow(()=>K.validate(c,r,s,null));});
test('FC1 cannot continue after predecessor receipt exposed an overshoot',()=>{const{K,s,r}=env(),a=F.cost(r),next=F.report(1,r),b=F.cost(next,a);b.previousReceiptOverhead.elapsedAfterPreviewReturn=8;assert.throws(()=>K.validate(b,next,s,a),/COST_CONTINUED_AFTER_EXPOSURE/);});
test('FC1 previous main byte-length and tail identity remain enforced',()=>{const{W,s,r}=env(),n=F.report(1,r);n.previousRun.emittedBytes++;assert.throws(()=>W.validate(n,s,1,r,JSON.stringify(r)),/PREVIOUS_RUN_INVALID/);});
test('FC1 root phase sum cannot be faked to hide cost',()=>{const{W,s,r}=env();r.cpuProfile.phases.report+=.5;assert.throws(()=>W.validate(r,s,0,null,null),/CPU_PHASE_SUM_INVALID/);});

test('FC1 cannot label a cooperative-ceiling-truncated prefix as sampled',()=>{const{W,s}=env(),r=F.report(0,null,11);assert.throws(()=>W.validate(r,s,0,null,null),/SAMPLED_OVER_EXPOSURE_CEILING/);});
