'use strict';
// Independent evidence fixtures: not generated by the adapter under test.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), vm = require('node:vm');
const { verifyTreasuryRun } = require('./verify-run.cjs');
const { buildGraph } = require('./build.cjs');
const { parseArgs } = require('../terminal-transfer/tools/lab-control.cjs');
const C = { experimentId: 'lab-proof-001', username: 'lab-proof-user', sourceRoomName: 'W1N57', targetRoomName: 'W10N57',
  sourceTerminalId: 'a000000000000001', targetTerminalId: 'a000000000000002', resourceType: 'H', amount: 100,
  description: 'lab-proof-001 100H', targetTick: 100, maxFeeEnergy: 26 };
const userId = 'u0000001';
const key = 'biz:terminal-lab:' + C.experimentId, attemptId = 'tk1_fixture_only';
const copy = v => JSON.parse(JSON.stringify(v));
function fixture(fee = 26) {
  const tx = { transactionId: 'abcdef000000001', time: 100, sender: { username: C.username }, recipient: { username: C.username },
    resourceType: 'H', amount: 100, from: 'W1N57', to: 'W10N57', description: C.description };
  const query = (observed, committed) => ({ observed, committed, spendable: observed - committed });
  const beforeProjection = { sourceH: query(1000,100), sourceEnergy: query(10000,26), targetH: query(0,0), targetRiskAdjustedFree: 297900 };
  const finalProjection = { sourceH: query(900,0), sourceEnergy: query(10000-fee,0), targetH: query(100,0), targetRiskAdjustedFree: 297900 };
  const state = (tick, stage, active, projection) => ({ kind: 'lab-treasury-state', experimentId: C.experimentId, tick, stage,
    health: { status: 'healthy' }, active, projection: copy(projection) });
  const rows = [];
  for(let tick=98; tick<=120; tick++) {
    const done = tick > 100;
    const ep = (side) => ({ readStatus: 'ok', roomName: C[side+'RoomName'], terminalId: C[side+'TerminalId'], ownerUsername: C.username,
      resourceAmount: side === 'source' ? (done?900:1000) : (done?100:0), energy: side==='source' ? 10000-(done?fee:0) : 2000,
      freeCapacity: side==='source' ? 289000+(done?100+fee:0) : 298000-(done?100:0), cooldown: side==='source'&&done ? Math.max(0,110-tick) : 0 });
    rows.push({ kind: 'lab-sample', experimentId: C.experimentId, tick, configTargetTick: 100, source: ep('source'), target: ep('target'),
      feeQuote: { status:'ok', energyCost:26 }, transactions: { incoming: { status:'ok',records:done?[copy(tx)]:[] }, outgoing:{ status:'ok',records:done?[copy(tx)]:[] } } });
    if(tick===100) {
      rows.push(state(100,'admitted',[{attemptId,workKey:key,phase:'pending'}],beforeProjection));
      rows.push({ kind:'lab-send-attempt',experimentId:C.experimentId,tick,phase:'pre-call',fee:26 });
      rows.push({ kind:'lab-send-attempt',experimentId:C.experimentId,tick,phase:'boundary' });
      rows.push({ kind:'lab-send-attempt',experimentId:C.experimentId,tick,phase:'sync-return',result:{ok:true,code:0} });
      rows.push(state(100,'dispatched',[{attemptId,workKey:key,phase:'outcome_unknown'}],beforeProjection));
    }
  }
  rows.push(state(120,'end',[],finalProjection));
  const core = { version:3, active:{}, counters:{admitted:1,dispatched:1,settledCommitted:1,rearmings:0},
    ring:[{attemptId,workKey:key,terminalPhase:'committed'}] };
  const mem = { runtime:{treasuryCore:core}, __labTerminalTransferProbe:{ experimentId:C.experimentId,armed:true,attempted:true,
    attemptedTick:100,syncResult:{ok:true,code:0},stopped:true } };
  const before = {memory:'{}'};
  const after = {memory:JSON.stringify(mem),transactions:[{...tx,_id:tx.transactionId,sender:userId,recipient:userId}],
    objects:[{_id:C.sourceTerminalId,store:{H:900,energy:10000-fee}},{_id:C.targetTerminalId,store:{H:100,energy:2000}}]};
  return {rows,before,after,stop:{ok:true,windowComplete:true,pauseConfirmed:true,triggerLatencyMs:6},
    processStop:{terminated:true,elapsedMs:2800,observedPids:[100,101],auditErrors:[]}};
}
function verdict(f) {
  const raw = f.rows.map(r => ({channel:'user:'+userId+'/console',payload:JSON.stringify({userId,messages:{log:[JSON.stringify(r)]}})}));
  return verifyTreasuryRun(C,userId,raw,f.before,f.after,f.stop,f.processStop);
}
for(const fee of [26,10]) test('full independent evidence passes, observed fee '+fee,()=>{
  const f=fixture(fee),before=JSON.stringify(f),v=verdict(f);
  assert.equal(v.status,'TREASURY_INTEGRATION_PASS',JSON.stringify(v));
  assert.equal(v.observedFee,fee); assert.equal(v.warnings.length,fee===26?0:1);
  assert.equal(JSON.stringify(f),before,'verification must not rewrite evidence');
});
const last = f => f.rows.find(r=>r.kind==='lab-sample'&&r.tick===120);
const end = f => f.rows.find(r=>r.kind==='lab-treasury-state'&&r.stage==='end');
function memory(f, mutate) { const m=JSON.parse(f.after.memory); mutate(m); f.after.memory=JSON.stringify(m); }
for(const [name,mutate] of [
  ['missing tick',f=>{f.rows=f.rows.filter(r=>r.tick!==105);}],
  ['duplicate tick',f=>f.rows.push(copy(last(f)))],
  ['second API boundary',f=>f.rows.push({kind:'lab-send-attempt',experimentId:C.experimentId,tick:101,phase:'boundary'})],
  ['other experiment API boundary',f=>f.rows.push({kind:'lab-send-attempt',experimentId:'other',tick:101,phase:'boundary'})],
  ['only rejected API',f=>{f.rows.find(r=>r.phase==='sync-return').result={ok:false,code:-6};}],
  ['still unknown active',f=>memory(f,m=>{m.runtime.treasuryCore.active={a:{phase:'outcome_unknown'}};})],
  ['no admitted kernel work',f=>{f.rows=f.rows.filter(r=>r.stage!=='admitted');}],
  ['no dispatch history',f=>memory(f,m=>{m.runtime.treasuryCore.counters.dispatched=0;})],
  ['cleared attempted',f=>memory(f,m=>{m.__labTerminalTransferProbe.attempted=false;})],
  ['old Treasury reused',f=>{f.before.memory=JSON.stringify({runtime:{treasuryCore:{version:3}}});}],
  ['uncorrelated ring',f=>memory(f,m=>{m.runtime.treasuryCore.ring[0].attemptId='other';})],
  ['source H still double deducted',f=>{end(f).projection.sourceH.spendable=800;}],
  ['fee still double deducted',f=>{end(f).projection.sourceEnergy.spendable-=26;}],
  ['target space still double deducted',f=>{end(f).projection.targetRiskAdjustedFree-=100;}],
  ['missing source fee obligation',f=>{f.rows.find(r=>r.stage==='admitted').projection.sourceEnergy.committed=0;}],
  ['no public outgoing proof',f=>{last(f).transactions.outgoing.records=[];}],
  ['public mirror wrong resource',f=>{last(f).transactions.incoming.records[0].resourceType='O';}],
  ['public mirror conflicting amount',f=>{last(f).transactions.incoming.records[0].amount=60;}],
  ['wrong database route',f=>{f.after.transactions[0].to='W11N57';}],
  ['database stock disagrees',f=>{f.after.objects[0].store.H=899;}],
  ['missing endpoint numeric fields',f=>{delete last(f).source.energy;}],
  ['missing endpoint object',f=>{delete last(f).source;}],
  ['bad transaction shape',f=>{f.after.transactions={};}],
  ['bad Memory',f=>{f.after.memory='garbage';}],
  ['invalid active scalar',f=>memory(f,m=>{m.runtime.treasuryCore.active='';})],
  ['automatic process stop missing',f=>{f.processStop=undefined;}],
  ['process stop merely requested',f=>{f.processStop.terminated=false;}],
  ['process audit failed',f=>{f.processStop.auditErrors=['disk full'];}],
  ['negative latency',f=>{f.stop.triggerLatencyMs=-1;}],
  ['NaN process time',f=>{f.processStop.elapsedMs=NaN;}],
  ['pause delay exceeded',f=>{f.stop.triggerLatencyMs=1001;}],
  ['runtime error',f=>f.rows.push({kind:'lab-treasury-error',experimentId:C.experimentId,tick:101})],
]) test('postflight does not pass '+name,()=>{const f=fixture(); mutate(f); assert.equal(verdict(f).status,'INCONCLUSIVE');});
function graphFixture(files) {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'treasury-graph-'));
  for(const [name,text] of Object.entries(files)){fs.mkdirSync(path.dirname(path.join(dir,name)),{recursive:true});fs.writeFileSync(path.join(dir,name),text);}
  return {dir,close:()=>fs.rmSync(dir,{recursive:true,force:true})};
}
test('builder resolves real source alias and relative imports into executable static bundle',()=>{
  const f=graphFixture({'test/lab/main.ts':'import {x} from "@/value"; export const loop=()=>x+1;', 'src/value.ts':'import {n} from "./n"; export const x=n;', 'src/n.ts':'export const n=41;'});
  try { const r=buildGraph(f.dir,'test/lab/main.ts'), e={}; vm.runInNewContext(r.code,{exports:e});assert.equal(e.loop(),42);assert.equal(r.modules.length,3); assert.deepEqual(r,buildGraph(f.dir,'test/lab/main.ts')); }
  finally{f.close();}
});
for(const [name,source,extra] of [
  ['Node dependency','import fs from "node:fs"; export const loop=()=>fs;',{}],
  ['dynamic require','export const loop=(name:string)=>require(name);',{}],
  ['mock dependency','import x from "@mock/treasury"; export const loop=()=>x;',{}],
  ['old raw send','import {loop as send} from "./singleShot"; export const loop=()=>send();',{'test/lab/singleShot.ts':'export const loop=()=>1;'}],
  ['production main','import {loop as run} from "@/main"; export const loop=()=>run();',{'src/main.ts':'export const loop=()=>1;'}],
  ['missing source','import {a} from "./absent"; export const loop=()=>a;',{}],
]) test('builder rejects '+name,()=>{ const f=graphFixture({'test/lab/main.ts':source,...extra});try{assert.throws(()=>buildGraph(f.dir,'test/lab/main.ts'));}finally{f.close();} });
test('builder handles a legitimate circular source graph once',()=>{
  const f=graphFixture({'test/lab/main.ts':'import {x} from "@/a"; export const loop=()=>x();',
    'src/a.ts':'import {y} from "./b"; export const n=40; export const x=()=>y();', 'src/b.ts':'import {n} from "./a"; export const y=()=>n+2;'});
  try{const r=buildGraph(f.dir,'test/lab/main.ts'),e={};vm.runInNewContext(r.code,{exports:e});assert.equal(e.loop(),42);}finally{f.close();}
});
const flags = { command:'run-treasury', environment:'/synthetic-only',host:'127.0.0.1',port:'21027',pid:'12345',user:userId,username:C.username,experiment:C.experimentId,out:'/new-output',proof:'/proof',facts:'/facts',main:'/main.js' };
const args = o => Object.entries(o).flatMap(([k,v])=>['--'+k,v]);
test('new CLI mode accepts only explicit bound options and one main',()=>assert.equal(parseArgs(args(flags)).command,'run-treasury'));
for(const key of ['proof','facts','main']) test('new CLI rejects missing '+key,()=>{const o={...flags};delete o[key];assert.throws(()=>parseArgs(args(o)));});
for(const key of ['observer','single-shot']) test('new CLI rejects old side-module '+key,()=>assert.throws(()=>parseArgs(args({...flags,[key]:'/old.js'}))));
test('default integration entry has no loop side effects; observer exception blocks activation',()=>{
  const ts=require('typescript');const source=fs.readFileSync(path.join(__dirname,'main.ts'),'utf8');
  const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
  for(const enabled of [false,true]) {
    const e={},calls=[];vm.runInNewContext(code,{exports:e,Game:{time:100},console:{log:()=>{}},require:name=>{
      if(name.endsWith('labConfig'))return {LAB_EXAMPLE_EXPERIMENT:C};
      if(name.endsWith('enabled'))return {TREASURY_INTEGRATION_ENABLED:enabled};
      if(name.endsWith('observer'))return {loop:()=>{calls.push('observe');throw Error('observer failed');}};
      if(name==='./assembly')return {assembleTreasuryIntegration:()=>{calls.push('assemble');return{tick:()=>calls.push('tick')};}};
      throw Error(name);
    }});e.loop();assert.deepEqual(calls,enabled?['observe']:[]);
  }
});
test('official build source guard rejects staged/unstaged/untracked graph bytes',()=>{
  const {execFileSync}=require('node:child_process');
  const {assertCommittedSources}=require('./build.cjs');
  const f=graphFixture({'src/a.ts':'export const a=1;'});
  const git = a=>execFileSync('git',a,{cwd:f.dir,stdio:'pipe',encoding:'utf8'});
  try {
    git(['init','-q']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','isolated graph fixture']);
    const sources={'src/a.ts':{}};assert.match(assertCommittedSources(f.dir,sources),/^[a-f0-9]{40}$/);
    fs.writeFileSync(path.join(f.dir,'src/a.ts'),'export const a=2;');assert.throws(()=>assertCommittedSources(f.dir,sources),/differs/);
    git(['add','.']);assert.throws(()=>assertCommittedSources(f.dir,sources),/differs/);
    fs.writeFileSync(path.join(f.dir,'src/new.ts'),'export const b=1;');assert.throws(()=>assertCommittedSources(f.dir,{'src/new.ts':{}}));
  }finally{f.close();}
});
