'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const C=require('../runtime/common.cjs'),P=C.POLICY,ROOT=path.resolve(__dirname,'..');
function git(repo,args){try{return cp.execFileSync('git',['-c','core.autocrlf=false','-c','core.eol=lf','-C',repo,...args],{encoding:null,maxBuffer:64*1048576,timeout:120000,stdio:['ignore','pipe','pipe']});}catch{C.fail('GIT_OPERATION_FAILED');}}
const text=(repo,args)=>git(repo,args).toString('utf8').trim();
function clean(repo){if(git(repo,['status','--porcelain=v1','-z','--untracked-files=all']).length)C.fail('WORKTREE_NOT_CLEAN');}
function head(repo){return text(repo,['rev-parse','HEAD']);}
function tree(repo,ref='HEAD'){return text(repo,['rev-parse',ref+'^{tree}']);}
function branch(repo,n){if(text(repo,['branch','--show-current'])!==n)C.fail('BRANCH_CHANGED');}
function remote(repo,n){const out=text(repo,['ls-remote','--exit-code','origin','refs/heads/'+n]).split(/\s+/);if(!/^[a-f0-9]{40}$/.test(out[0]))C.fail('REMOTE_UNREADABLE');return out[0];}
function paths(repo,a,b){return git(repo,['diff','--name-only','-z',a,b]).toString('utf8').split('\0').filter(Boolean).sort();}
function outside(file,repo){const real=p=>{p=path.resolve(p);return fs.existsSync(p)?fs.realpathSync(p):path.join(real(path.dirname(p)),path.basename(p));};const r=path.relative(real(repo),real(file));if(r===''||(!r.startsWith('..'+path.sep)&&r!=='..'&&!path.isAbsolute(r)))C.fail('WORK_INSIDE_REPOSITORY');}
function manifest(){return C.json(path.join(ROOT,'source-manifest.json'));}
function source(repo){const m=manifest();clean(repo);branch(repo,P.compatBranch);const h=head(repo);if(h===P.compatBase)C.fail('SOURCE_NOT_APPLIED');if(!C.same(text(repo,['show','-s','--format=%P',h]).split(' '),[P.compatBase])||tree(repo)!==m.expectedSourceTree||text(repo,['show','-s','--format=%s',h])!==P.sourceMessage||!C.same(paths(repo,P.compatBase,h),Object.keys(m.files).sort()))C.fail('SOURCE_IDENTITY_CHANGED');for(const[n,v]of Object.entries(m.files)){const b=C.bytes(path.join(repo,n));if(b.length!==v.after.bytes||C.sha(b)!==v.after.sha256)C.fail('SOURCE_BYTES_CHANGED');}return {head:h,tree:m.expectedSourceTree,base:P.compatBase,paths:Object.keys(m.files).length};}
function baseline(refactor,compat,{allowApplied=true,network=true}={}){clean(refactor);branch(refactor,P.refactorBranch);if(head(refactor)!==P.refactorBase)C.fail('REFACTOR_BASE_CHANGED');clean(compat);branch(compat,P.compatBranch);let s;if(head(compat)===P.compatBase){if(tree(compat)!==P.compatBaseTree)C.fail('BASE_TREE_CHANGED');s={state:'base',head:P.compatBase};}else {if(!allowApplied)C.fail('COMPAT_BASE_CHANGED');s={state:'applied',...source(compat)};}
 const b=git(refactor,['show',P.refactorBase+':'+P.priorRecoveryPath]);if(C.blob(b)!==P.priorRecoveryBlob||JSON.parse(b).status!=='RESTORED_BYTES_AND_RUNTIME_VERIFIED')C.fail('PRIOR_RECOVERY_NOT_VERIFIED');
 if(network&&(remote(refactor,P.refactorBranch)!==P.refactorBase||remote(compat,P.compatBranch)!==P.compatBase))C.fail('REMOTE_BASE_CHANGED');return {status:'TASK_XIV_BASELINES_VERIFIED',source:s,priorRecovery:'verified'};}
function apply(compat){const m=manifest();clean(compat);branch(compat,P.compatBranch);if(head(compat)!==P.compatBase)return {status:'TASK_XIV_SOURCE_REUSED',resumed:true,...source(compat)};if(tree(compat)!==P.compatBaseTree)C.fail('BASE_TREE_CHANGED');const patch=path.join(ROOT,'patches/source.patch');git(compat,['apply','--unidiff-zero','--check','--index',patch]);git(compat,['apply','--unidiff-zero','--index',patch]);git(compat,['diff','--cached','--check']);if(text(compat,['write-tree'])!==m.expectedSourceTree)C.fail('APPLIED_TREE_MISMATCH');git(compat,['commit','-m',P.sourceMessage]);return {status:'TASK_XIV_SOURCE_APPLIED',resumed:false,...source(compat)};}
function profileFor(t){const startTick=Math.ceil((t+150)/100)*100;return {enabled:true,shardName:'shard1',rooms:P.rooms,resources:P.resources,startTick,endTick:startTick+300,intervalTicks:100,minBucket:2000,maxSampleCpu:2,reserveCpu:5,maxLogBytes:16384};}
function render(p){return 'import type { CompatConfig } from "./treasuryCompatTypes";\nexport const TREASURY_COMPAT_CONFIG: CompatConfig = Object.freeze({\n'+Object.entries(p).map(([k,v])=>'  '+k+': '+(Array.isArray(v)?'Object.freeze('+JSON.stringify(v)+')':JSON.stringify(v))+',').join('\n')+'\n});\n';}
const CONFIG='src/runtime/treasuryCompatConfig.ts';
function bind(repo,dir,t){const s=source(repo),profile=profileFor(t);C.durable(path.join(dir,'binding-intent.json'),{runId:P.parentRunId,source:s,observedTick:t,profile,atMs:Date.now()});fs.writeFileSync(path.join(repo,CONFIG),render(profile));git(repo,['add','--',CONFIG]);git(repo,['diff','--cached','--check']);git(repo,['commit','-m',`evidence(compat): bind task XIV ${profile.startTick}-${profile.endTick}`]);clean(repo);if(!C.same(paths(repo,s.head,'HEAD'),[CONFIG])||text(repo,['rev-parse','HEAD^'])!==s.head)C.fail('BIND_SCOPE_CHANGED');const b={runId:P.parentRunId,source:s,profile,observedTick:t,profileHead:head(repo),profileTree:tree(repo)};C.durable(path.join(dir,'binding.json'),b);return b;}
async function closeSource(repo,dir){return C.lock(dir,'source-close',async()=>{const b=C.optional(dir,'binding.json'),intent=C.optional(dir,'binding-intent.json');if(!intent)return {status:'NO_PROFILE_BOUND',head:head(repo)};branch(repo,P.compatBranch);const src=intent.source,old=C.optional(dir,'source-closed.json');if(old){if(head(repo)!==old.closedHead||tree(repo)!==src.tree)C.fail('CLOSED_SOURCE_CHANGED');clean(repo);return old;}
 let h=head(repo),closed;
 if(h===src.head){if(git(repo,['status','--porcelain=v1','-z']).length){if(!C.same(git(repo,['diff','--name-only','-z','HEAD']).toString('utf8').split('\0').filter(Boolean).sort(),[CONFIG]))C.fail('DIRTY_PROFILE_NOT_RECOGNIZED');if(fs.readFileSync(path.join(repo,CONFIG),'utf8')!==render(intent.profile))C.fail('DIRTY_PROFILE_CHANGED');fs.writeFileSync(path.join(repo,CONFIG),git(repo,['show',src.head+':'+CONFIG]));git(repo,['add','--',CONFIG]);}clean(repo);closed=h;}
 else if(b&&tree(repo)===src.tree&&text(repo,['rev-parse','HEAD^'])===b.profileHead){clean(repo);closed=h;}
 else{clean(repo);if(text(repo,['rev-parse','HEAD^'])!==src.head||!C.same(paths(repo,src.head,h),[CONFIG])||git(repo,['show',h+':'+CONFIG]).toString('utf8')!==render(intent.profile))C.fail('UNRECOGNIZED_PROFILE_HEAD');fs.writeFileSync(path.join(repo,CONFIG),git(repo,['show',src.head+':'+CONFIG]));git(repo,['add','--',CONFIG]);git(repo,['commit','-m','evidence(compat): close task XIV to default OFF']);clean(repo);closed=head(repo);}
 if(tree(repo)!==src.tree)C.fail('OFF_TREE_MISMATCH');const r={status:'SOURCE_DEFAULT_OFF_RESTORED',sourceHead:src.head,closedHead:closed,sameTreeAsSource:true,atMs:Date.now()};C.durable(path.join(dir,'source-closed.json'),r);return r;});}
function command(repo,args,out,stem,timeout=600000){const r=cp.spawnSync(process.execPath,args,{cwd:repo,encoding:'utf8',maxBuffer:64*1048576,timeout,windowsHide:true,env:{...process.env,DEST:'',DEPLOY_ALLOW_DIRTY:'',NODE_OPTIONS:'',NODE_PATH:''}});fs.writeFileSync(path.join(out,stem+'.stdout'),r.stdout||'');fs.writeFileSync(path.join(out,stem+'.stderr'),r.stderr||'');C.durable(path.join(out,stem+'.exit.json'),{exit:r.status,signal:r.signal,error:r.error?.code||null});if(r.status!==0||r.error)C.fail('OFFLINE_COMMAND_FAILED');return r;}
function detachedBuild(repo,ref,out){const d=path.join(out,'build');if(fs.existsSync(d))C.fail('BUILD_DIR_EXISTS');git(repo,['worktree','add','--detach',d,ref]);const target=path.join(repo,'node_modules');fs.symlinkSync(target,path.join(d,'node_modules'),process.platform==='win32'?'junction':'dir');clean(d);command(d,[path.join(target,'rollup/dist/bin/rollup'),'-c'],out,'bundle',600000);clean(d);return {modules:{main:fs.readFileSync(path.join(d,'dist/main.js'),'utf8')},head:head(d),tree:tree(d)};}
module.exports={ROOT,git,text,clean,head,tree,branch,remote,paths,outside,manifest,source,baseline,apply,profileFor,render,bind,closeSource,command,detachedBuild,CONFIG};
