'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const F=require('./fixture.cjs'),C=require('../runtime/common.cjs'),K=require('../runtime/policy.cjs'),D=require('../runtime/decoder.cjs'),W=require('../runtime/samples.cjs');
const copy=C.clone;
test('fixed profile has four fresh points with unchanged budget and bounded absolute window',()=>{
 const p=K.profileFor(73646525);assert.deepEqual(K.dueTicks(p),[73646700,73646800,73646900,73647000]);assert.equal(p.maxSampleCpu,2);assert.equal(p.reserveCpu,5);});
for(const field of ['maxSampleCpu','endTick','intervalTicks','minBucket','reserveCpu'])test('profile rejects changed '+field,()=>{const p=K.profileFor(1000);p[field]++;assert.throws(()=>K.validProfile(p));});
test('raw JSON is not destructively entity-decoded',()=>{const text=JSON.stringify({kind:'treasury-legacy-read-bridge',note:'&#x22; &amp;'});assert.equal(D.parseBridge(text).jsonText,text);assert.equal(D.parseBridge(text).report.note,'&#x22; &amp;');});
for(const entity of ['&quot;','&#34;','&#x22;','&#X22;'])test('accepts one transport escape layer '+entity,()=>{const text=JSON.stringify({kind:'treasury-legacy-read-bridge',tick:1});const p=D.parseBridge(text.replaceAll('"',entity));assert.equal(p.kind,'bridge');assert.equal(p.jsonText,text);});
test('double encoded JSON is rejected rather than recursively repaired',()=>{const t=JSON.stringify({kind:'treasury-legacy-read-bridge'}).replaceAll('"','&amp;#x22;');assert.equal(D.parseBridge(t).kind,'invalid');});
for(const entity of ['&#x110000;','&#xD800;','&#0;','&#99999999999;'])test('bad Unicode entity fails '+entity,()=>assert.throws(()=>D.decodeHtmlOnce(entity)));
test('actual old partial report is decoded but never a complete sample or new diagnostic',()=>{const r=require('../references/0003-first-report.json'),p=D.parseBridge(JSON.stringify(r).replaceAll('"','&#x22;'));assert.equal(p.kind,'bridge');assert.equal(p.report.status,'partial_cpu_budget');assert.equal(W.sampleError(p.report,K.profileFor(1000)),'SAMPLE_NOT_COMPLETE');});
test('actual accepted CPU reader emits four valid prefix and three linked tail profiles',()=>{const s=F.session(),a=F.reports(s);assert.equal(a.length,4);a.forEach((r,i)=>{assert.equal(W.diagnosticError(r,s.profile,i,a[i-1],i?JSON.stringify(a[i-1]):null),null);assert.equal(W.sampleError(r,s.profile),null);});});
test('partial CPU first point is useful diagnosis and does not count as complete',()=>{const s=F.session(),a=F.reports(s,{partialFirst:true});assert.equal(a[0].status,'partial_cpu_budget');assert.equal(a[0].cpuProfile.calls.commitmentBuild,0);a.forEach((r,i)=>assert.equal(W.diagnosticError(r,s.profile,i,a[i-1],i?JSON.stringify(a[i-1]):null),null));assert.equal(W.sampleError(a[0],s.profile),'SAMPLE_NOT_COMPLETE');});
test('four partial CPU points remain useful but none complete',()=>{const s=F.session(),a=F.reports(s,{partialAll:true});assert.ok(a.every(r=>r.status==='partial_cpu_budget'));a.forEach((r,i)=>assert.equal(W.diagnosticError(r,s.profile,i,a[i-1],i?JSON.stringify(a[i-1]):null),null));});
for(const[name,mutate]of [
 ['budget authority',r=>r.authorizesActions=true],['missing profile',r=>delete r.cpuProfile],['wrong ordinal',r=>r.cpuProfile.sampleOrdinal=2],
 ['wrong source',r=>r.sourceCommit='e'.repeat(40)],['future cost',r=>r.cpuProfile.phases.emit=1],['invalid phase',r=>r.cpuProfile.phases.unknown=0],
 ['bad call count',r=>r.cpuProfile.calls.readerLoad=2],['nonfinite',r=>r.cpuProfile.elapsed=NaN],['mismatched total',r=>r.cpuBeforeSerializationAndEmit=0.9],
 ['not fresh',r=>r.previousRun={}],['core mismatch',r=>r.endpoints[0].coreComparison='mismatch'],['output limited',r=>r.status='output_limited'],
 ['room scope',r=>r.scope.rooms=['W1N1']],['unsafe phase cost',r=>{r.cpuProfile.elapsed=6;r.cpuProfile.phases={legacyInputs:6};r.cpuBeforeSerializationAndEmit=6;}]
])test('rejects diagnostic '+name,()=>{const s=F.session(),r=copy(F.reports(s)[0]);mutate(r);assert.ok(W.diagnosticError(r,s.profile,0));});
for(const[name,mutate]of [
 ['tail absence',r=>delete r.previousCpuProfile],['tail backwards',r=>{r.previousCpuProfile.elapsed=0;r.previousCpuProfile.phases={legacyInputs:0};}],
 ['wrong previous bytes',r=>r.previousRun.emittedBytes++],['engine reset ordinal',r=>r.cpuProfile.sampleOrdinal=1],['wrong previous tick',r=>r.previousRun.tick++],
 ['wrong previous calls',r=>r.previousCpuProfile.calls.commitmentBuild=0]
])test('rejects linked tail '+name,()=>{const s=F.session(),a=F.reports(s);mutate(a[1]);assert.ok(W.diagnosticError(a[1],s.profile,1,a[0],JSON.stringify(a[0])));});
test('real row completeness string is accepted and invented object is not',()=>{const s=F.session(),r=F.reports(s)[0];assert.equal(r.commitments.rows[0].completeness,'complete');assert.equal(W.sampleError(r,s.profile),null);r.commitments.rows[0].completeness={complete:true};assert.ok(W.sampleError(r,s.profile));});
test('collector keeps partial raw reports streaming and does not signal a failure',()=>{const s=F.session(),w=W.createWatch(s,12),a=F.reports(s,{partialFirst:true});w.frame('auth ok');w.frame(F.frame(s,a.map(x=>JSON.stringify(x).replaceAll('"','&#x22;'))));assert.equal(w.state.bridgeReports,4);assert.equal(w.state.completeSamples,3);assert.equal(w.state.diagnosticFailure,null);assert.equal(w.state.stopReason,null);});
test('diagnostic fault is retained without force-closing transport evidence',()=>{const s=F.session(),w=W.createWatch(s,12);w.frame('auth ok');w.frame(F.frame(s,['{&#x22;kind&#x22;:&#x22;treasury-legacy-read-bridge&#x22;,BROKEN}']));assert.equal(w.state.diagnosticFailure,'BRIDGE_JSON_INVALID');assert.equal(w.state.state,'streaming');assert.equal(w.state.stopReason,null);});
test('wrong-shard report cannot be accepted as CPU evidence',()=>{const s=F.session(),w=W.createWatch(s,12);w.frame('auth ok');const f=JSON.parse(F.frame(s,[JSON.stringify(F.reports(s)[0])]));f[1].shard='shard2';w.frame(JSON.stringify(f));assert.equal(w.state.bridgeReports,0);});
test('same report duplicate is counted while conflicting duplicate remains fatal',()=>{const s=F.session(),w=W.createWatch(s,12),r=F.reports(s)[0];w.frame('auth ok');w.frame(F.frame(s,[JSON.stringify(r),JSON.stringify(r)]));assert.equal(w.state.duplicateSamples,1);r.note='changed';w.frame(F.frame(s,[JSON.stringify(r)]));assert.equal(w.state.diagnosticFailure,'CONFLICTING_DUPLICATE_SAMPLE');});
test('authentication repetition is a transport failure',()=>{const s=F.session(),w=W.createWatch(s,12);w.frame('auth ok');assert.equal(w.frame('auth ok'),'auth-failure');});

test('private session is bound to the exact delivered tool fingerprint',()=>{const S=require('../runtime/store.cjs'),s=F.session(),run=F.tmp(),old=C.ORIGINAL_DIGEST;F.save(run,s);try{C.ORIGINAL_DIGEST=s.backup.digest;assert.equal(S.loadRun(run,F.guard).profileHead,s.profileHead);const file=path.join(run,'session.json'),changed=C.readJson(file);changed.toolFingerprint='0'.repeat(64);fs.writeFileSync(file,JSON.stringify(changed));assert.throws(()=>S.loadRun(run,F.guard),e=>e.code==='SESSION_TOOL_FINGERPRINT_MISMATCH');}finally{C.ORIGINAL_DIGEST=old;}});
