'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const packaged=fs.existsSync(path.join(__dirname,'../implementation/treasuryCompatRuntime.ts'));
const source=fs.readFileSync(path.join(__dirname,packaged?'../implementation/treasuryCompatRuntime.ts':'../../src/runtime/treasuryCompatRuntime.ts'),'utf8');
const ts=require(process.env.FC1_TS_PATH||'typescript');
const cfg={enabled:true,shardName:'shard1',rooms:['E3N59','E4N58'],resources:['energy','H'],startTick:100,endTick:400,intervalTicks:100,minBucket:2000,maxSampleCpu:10,reserveCpu:25,maxLogBytes:16384};
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText;
const plain=x=>JSON.parse(JSON.stringify(x));
function api(){const c=vm.createContext({exports:{},require(n){if(n==='./treasuryCompatConfig')return{TREASURY_COMPAT_CONFIG:{enabled:false}};if(n==='./treasuryCompatRead')return{createTreasuryCompatPreview(){throw Error('unexpected default factory');},validCompatConfig:()=>true};if(n==='./treasuryCompatReadCore.generated')return{createCompatibilityReadCore(){throw Error('prewarm');}};throw Error('unexpected import '+n);}});new vm.Script(js).runInContext(c);return c.exports;}
function fixture(overrides={}){
 const state={tick:100,used:50,limit:100,tickLimit:500,bucket:6000,cost:3.5,status:'sampled',calls:0,native:0,created:0,logs:[],...overrides};
 const a=api(),config={...cfg,...overrides.config};
 const ports={tick:()=>state.tick,shard:()=>state.shard||'shard1',emit(line){if(state.emitThrows)throw Error('emit fail');state.logs.push(JSON.parse(line));state.used+=0.1;}};
 const native=()=>{state.native++;const out={used:state.used,limit:state.limit,tickLimit:state.tickLimit,bucket:state.bucket};if(state.nativeTransform)return state.nativeTransform(out,state.native);return out;};
 const factory=(received,p,options)=>{state.created++;assert.equal(received,config);assert.deepEqual(plain(options),{cpuDiagnostics:true,commitmentBoundaryDiagnostics:true,taskBoundaryDiagnostics:true,localSafetyStop:false});return{run(){state.calls++;state.used+=state.cost;return{status:state.status};},stats(){return{cpuProfile:{tick:state.tick,boundary:'afterRetention',elapsed:state.cost-0.1,completion:'tail_only'}};}};};
 const runtime=a.createFullCostRuntime(config,ports,native,factory);return{state,config,runtime,a,run(){runtime.run();return state.logs;},receipt(){return state.logs.find(x=>x.kind==='treasury-full-cost-sample');}};
}
test('FC1 OFF does not initialize a preview or read native CPU',()=>{const f=fixture({config:{enabled:false}});f.run();assert.equal(f.state.created,0);assert.equal(f.state.native,0);assert.equal(f.state.calls,0);});
test('FC1 non-due ticks do not sample CPU, Store or Memory',()=>{const f=fixture({tick:99});f.run();f.state.tick=101;f.run();assert.equal(f.state.native,0);assert.equal(f.state.calls,0);});
test('FC1 complete work above 2 CPU is measured without a performance failure',()=>{const f=fixture();f.run();assert.equal(f.receipt().elapsedThroughPreviewReturn,3.5);assert.equal(f.receipt().previewStatus,'sampled');assert.equal(f.receipt().performanceTargetCpu,null);assert.equal(f.receipt().stopsFutureSamples,false);});
test('FC1 no inherited 5-CPU latch truncates an otherwise complete 6-CPU sample',()=>{const f=fixture({cost:6});f.run();assert.equal(f.receipt().elapsedThroughPreviewReturn,6);assert.equal(f.receipt().stopsFutureSamples,false);});
test('FC1 four samples reuse one preview, preserving its state',()=>{const f=fixture();for(const tick of [100,200,300,400]){f.state.tick=tick;f.state.used=50;f.run();}assert.equal(f.state.created,1);assert.equal(f.state.calls,4);assert.deepEqual(f.state.logs.map(x=>x.sampleOrdinal),[1,2,3,4]);});
test('FC1 final current tail is emitted without a fifth business sample',()=>{const f=fixture();for(const tick of [100,200,300,400]){f.state.tick=tick;f.state.used=50;f.run();}assert.equal(f.state.logs.at(-1).currentTailProfile.tick,400);assert.equal(f.state.logs.at(-1).currentTailProfile.boundary,'afterRetention');f.state.tick=500;f.run();assert.equal(f.state.calls,4);});
test('FC1 retains only the predecessor receipt overhead and does not invent its own tail',()=>{const f=fixture();f.run();assert.equal(f.receipt().previousReceiptOverhead,null);f.state.tick=200;f.state.used=50;f.run();const x=f.state.logs.at(-1);assert.equal(x.previousReceiptOverhead.tick,100);assert.ok(Math.abs(x.previousReceiptOverhead.elapsedAfterPreviewReturn-.1)<1e-8);assert.equal(x.receiptSelfCost,undefined);});
test('FC1 duplicate same-tick invocation does not run or emit twice',()=>{const f=fixture();f.run();f.run();assert.equal(f.state.calls,1);assert.equal(f.state.logs.length,1);});
test('FC1 a fresh heap cannot begin at a later scheduled point',()=>{const f=fixture({tick:200});f.run();assert.equal(f.state.calls,0);assert.equal(f.state.logs[0].reason,'WINDOW_RESTART_UNPROVEN');f.state.tick=300;f.run();assert.equal(f.state.logs.length,1);});
test('FC1 wrong shard is latched without a reader call',()=>{const f=fixture({shard:'shard2'});f.run();assert.equal(f.state.calls,0);assert.equal(f.state.logs[0].reason,'WRONG_SHARD');});
for(const [name,config] of [['old2',{maxSampleCpu:2}],['smallReserve',{reserveCpu:5}],['changedInterval',{intervalTicks:20}],['extraPoint',{endTick:500}],['lowerBucket',{minBucket:1000}]])test('FC1 rejects unbound policy '+name,()=>{const f=fixture({config});f.run();assert.equal(f.state.calls,0);assert.equal(f.state.logs[0].reason,'FULL_COST_PROFILE_INVALID');});
test('FC1 headroom below 55 stops instead of choosing another tick',()=>{const f=fixture({used:445.01});f.run();assert.equal(f.state.calls,0);assert.equal(f.state.logs[0].reason,'INSUFFICIENT_NATIVE_HEADROOM');assert.equal(f.state.logs[0].nativeCpu.used,445.01);assert.equal(f.state.logs[0].requiredHeadroomCpu,55);f.state.tick=200;f.state.used=0;f.run();assert.equal(f.state.calls,0);});
test('FC1 exactly 55 headroom and bucket 2000 are admitted',()=>{const f=fixture({used:445,bucket:2000});f.run();assert.equal(f.state.calls,1);assert.equal(f.receipt().nativeEntry.tickLimit-f.receipt().nativeEntry.used,55);});
test('FC1 low bucket is rejected even with ample tickLimit',()=>{const f=fixture({bucket:1999});f.run();assert.equal(f.state.calls,0);});
for(const [name,override] of [['NaN',{used:NaN}],['negative',{used:-1}],['badLimit',{limit:0}],['fractionalBucket',{bucket:2000.5}],['inconsistentLimit',{limit:501}]])test('FC1 invalid CPU is fail-closed '+name,()=>{const f=fixture(override);f.run();assert.equal(f.state.calls,0);assert.equal(f.state.logs[0].reason,'INVALID_NATIVE_CPU');});
test('FC1 observed overshoot is reported honestly and future samples stop',()=>{const f=fixture({cost:14});f.run();assert.equal(f.receipt().elapsedThroughPreviewReturn,14);assert.equal(f.receipt().stopsFutureSamples,true);assert.equal(f.receipt().stopReason,'CPU_OBSERVED_EXPOSURE_STOP');f.state.tick=200;f.run();assert.equal(f.state.calls,1);});
test('FC1 partial result is not promoted to sampled',()=>{const f=fixture({status:'partial_cpu_budget'});f.run();assert.equal(f.receipt().previewStatus,'partial_cpu_budget');assert.equal(f.receipt().stopReason,'PREVIEW_NOT_COMPLETE');});
test('FC1 native return regression is rejected, not clamped to zero',()=>{const f=fixture({nativeTransform:(x,n)=>n===2?{...x,used:1}:x});f.run();assert.equal(f.receipt(),undefined);assert.equal(f.state.logs[0].reason,'INVALID_NATIVE_CPU_PROGRESSION');});
test('FC1 emission fault cannot escape into the old bot or re-arm',()=>{const f=fixture({emitThrows:true});assert.doesNotThrow(()=>f.run());f.state.emitThrows=false;f.state.tick=200;f.run();assert.equal(f.state.calls,1);});
test('FC1 observed receipt overhead can stop future samples separately',()=>{const f=fixture({cost:9.95});f.run();assert.equal(f.receipt().stopsFutureSamples,false);assert.equal(f.state.logs.at(-1).reason,'RECEIPT_OBSERVED_EXPOSURE_STOP');f.state.tick=200;f.run();assert.equal(f.state.calls,1);});
test('FC1 configuration is not silently increased or mutated by the wrapper',()=>{const f=fixture(),before=JSON.stringify(f.config);f.run();assert.equal(JSON.stringify(f.config),before);assert.deepEqual(f.receipt().policy,{cooperativeCeilingCpu:10,retainedReserveCpu:25,admissionHeadroomCpu:55,minBucket:2000,maxReceiptBytes:16384});});

// These three REAL integration tests are mandatory in the repository. The maker
// package tests above use a stub preview to isolate the new wrapper boundary.
if(!packaged){
 function real(bad=false){
  let used=50;const logs=[],root=path.resolve(__dirname,'../../src/runtime'),rooms={};
  const makeStore=()=>{const amounts={energy:10000,H:50},o={...amounts};Object.defineProperties(o,{getUsedCapacity:{value(r){return r===undefined?10050:amounts[r]||0;}},getFreeCapacity:{value(){return 89950;}},getCapacity:{value(){return 100000;}}});return o;};
  for(const name of cfg.rooms)rooms[name]={name,controller:{my:true},storage:{id:'store-'+name,my:true,isActive:()=>true,store:makeStore()},terminal:{id:'term-'+name,my:true,isActive:()=>true,cooldown:0,store:makeStore()}};
  const tasks={};for(let i=0;i<5;i++)tasks[i]={id:'t'+i,status:'pending',resource:'energy',fromRoomName:cfg.rooms[0],toRoomName:cfg.rooms[1],amount:100,remainingAmount:70,origin:'manual',reason:'manual',createdAt:1,updatedAt:1,lastProgressAt:1};
  if(bad)tasks.bad={status:'pendng',resource:'energy',fromRoomName:'E3N59',toRoomName:'E4N58'};
  const Memory={cfg:{resourceControl:{capacityBalancing:{}}},data:{resourceControl:{tasks}},runtime:{resourceReservations:{r:{roomName:'E3N59',resource:'H',holderId:'task:synthetic',amount:60,expiresAt:1000}}}};
  const freeze=x=>{if(x&&typeof x==='object'){for(const v of Object.values(x))freeze(v);Object.freeze(x);}};freeze(Memory);
  const Game={time:100,shard:{name:'shard1'},rooms,cpu:{limit:100,tickLimit:500,bucket:6000,getUsed(){used+=.09;return used;}},getObjectById(){return null;}};
  const globals={Game,Memory,RESOURCES_ALL:['energy','H'],console:{log:x=>logs.push(JSON.parse(x))}},cache={};
  function load(name){if(name==='treasuryCompatConfig')return{TREASURY_COMPAT_CONFIG:cfg};if(cache[name])return cache[name];const code=ts.transpileModule(fs.readFileSync(path.join(root,name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText;const ctx=vm.createContext({...globals,exports:{},require:n=>load(n.replace(/^\.\//,''))});cache[name]=ctx.exports;new vm.Script(code,{filename:name}).runInContext(ctx);return ctx.exports;}
  const runtime=load('treasuryCompatRuntime');return{run(t){Game.time=t;used=50;runtime.runTreasuryCompatRead();},logs,Game,Memory};
 }
 test('FC1 REAL R1 preview completes 4 rows / 16 queries above 2 synthetic CPU with nonempty reservations',()=>{const s=real();for(const t of [100,200,300,400])s.run(t);const reports=s.logs.filter(x=>x.kind==='treasury-legacy-read-bridge'),costs=s.logs.filter(x=>x.kind==='treasury-full-cost-sample');assert.equal(reports.length,4);assert.equal(costs.length,4);for(const r of reports){assert.equal(r.status,'sampled');assert.ok(r.cpuBeforeSerializationAndEmit>2);assert.equal(r.commitments.rows.length,4);assert.equal(r.cpuProfile.attribution.work.projectionIndexQueries,16);assert.equal(r.cpuProfile.attribution.work.commitmentReservationRecords,1);assert.equal(r.localSafety,undefined);}assert.equal(costs[3].currentTailProfile.tick,400);assert.ok(costs.every(x=>x.elapsedThroughPreviewReturn>=x.currentTailProfile.elapsed));});
 test('FC1 REAL R1 keeps damaged-input fail-closed semantics',()=>{const s=real(true);s.run(100);const r=s.logs.find(x=>x.kind==='treasury-legacy-read-bridge');assert.equal(r.commitments.status,'read_incomplete');assert.equal(r.commitments.completeness.complete,false);assert.equal(r.authorizesActions,false);assert.equal(r.spendable,null);});
 test('FC1 REAL runtime native admission prevents reader work',()=>{const s=real();s.Game.cpu.limit=50;s.Game.cpu.tickLimit=90;s.run(100);assert.equal(s.logs.some(x=>x.kind==='treasury-legacy-read-bridge'),false);assert.equal(s.logs[0].reason,'INSUFFICIENT_NATIVE_HEADROOM');});
}
