'use strict';
const C=require('./common.cjs'),Prepare=require('./prepare.cjs'),M=require('./analyze.cjs'),S=require('./source.cjs'),{fs,path,P}=C;
async function run(o){C.verify();C.required(o,['compat','refactor','work']);C.check(!!o.execute!==!!o['offline-only'],'SELECT_EXACTLY_ONE_MODE');if(o.execute){if(P.newRoundAuthorization?.status!=='AUTHORIZED'||P.authorizationId===P.historicalAuthorizationId||P.runId===P.historicalRunId||P.newRoundAuthorization.authorizationId!==P.authorizationId||P.newRoundAuthorization.runId!==P.runId)C.fail('NEW_ROUND_AUTHORIZATION_REQUIRED');C.required(o,['secret']);C.check(o['exclusive-target']&&o['prior-workers-stopped'],'EXCLUSIVE_EXECUTION_FACTS_REQUIRED');}for(const n of ['compat','refactor','work','secret'])if(o[n])o[n]=path.resolve(o[n]);let phase='package-self-tests';
 try{
  for(const r of [o.compat,o.refactor,C.ROOT])C.outside(o.work,r);C.check(!fs.existsSync(o.work),'WORK_DIR_ALREADY_EXISTS');S.authorizationUnused(o.compat);
  C.command(C.ROOT,[path.join(C.ROOT,'tools/run-tests.cjs'),'--compat',o.compat,'--out',o.work+'.package-self-tests'],o.work+'.bootstrap-logs','self-tests');
  phase='prepare';const p=Prepare.prepare(o),executor=p.executor,logs=path.join(o.work,'commands');const cmd=(name,args,opt)=>C.command(executor,[path.join(executor,'tools',name+'.cjs'),...args],logs,name,opt);
  phase='executor-tools';cmd('run-tests',['--out',path.join(o.work,'tool-tests')]);
  phase='full-offline-gates';cmd('build',['--compat',o.compat,'--out',path.join(o.work,'offline-checks')]);
  const offline=C.json(path.join(o.work,'offline-checks/result.json'));C.check(offline.status==='FC1_OFFLINE_VERIFIED'&&offline.onlineAttempted===false&&offline.source.head===p.source.head&&offline.source.tree===p.source.tree&&offline.source.runtimeEmitterId===P.runtimeEmitterId&&offline.compiler===P.compilerVersion&&offline.repositoryNodeTests===P.repositoryNodeTests,'OFFLINE_PROOF_MISMATCH');
  phase='publish-default-off-source';C.baseline(o.refactor,P.refactorBranch,P.refactorBase);C.clean(o.compat);S.verifyFrozenReaders(o.compat);S.authorizationUnused(o.compat);C.check(C.head(o.compat)===p.source.head&&C.tree(o.compat)===p.source.tree&&C.remote(o.compat,P.compatBranch)===P.compatBase,'SOURCE_PUBLISH_BASE_CHANGED');C.git(o.compat,['push','origin','HEAD:refs/heads/'+P.compatBranch]);C.check(C.remote(o.compat,P.compatBranch)===p.source.head,'SOURCE_PUSH_UNCONFIRMED');C.durable(path.join(o.work,'source-published.json'),{source:p.source,defaultOff:true,at:new Date().toISOString()});
  if(o['offline-only']){const result={status:'FC1_OFFLINE_VERIFIED_SOURCE_PUBLISHED',source:p.source,onlineAttempted:false,networkWrites:0,costMeasured:false};C.durable(path.join(o.work,'RESULT.json'),result);return result;}
  phase='pre-online-reuse-check';cmd('apply',['--compat',o.compat,'--refactor',o.refactor,'--out',path.join(o.work,'source-reuse.json')]);
  phase='single-online-trial';const observation=cmd('observe',['--compat',o.compat,'--refactor',o.refactor,'--work',path.join(o.work,'live'),'--offline',path.join(o.work,'offline-checks'),'--tests',path.join(o.work,'tool-tests'),'--secret',o.secret,'--execute','--exclusive-target','--prior-workers-stopped'],{allowFailure:true,timeout:0});
  const dir=path.join(o.work,'live/run');C.check(fs.existsSync(dir),'OBSERVE_DID_NOT_CREATE_RUN');
  phase='independent-verification';cmd('verify',['--compat',o.compat,'--run',dir,'--out',path.join(o.work,'FINAL-VERIFICATION.json')]);const v=C.json(path.join(o.work,'FINAL-VERIFICATION.json'));C.check(!v.issues?.includes('RESIDUAL_PROCESS')&&!v.issues?.includes('RESIDUAL_LOCK'),'EXPERIMENT_STILL_RUNNING');
  if(v.closure!=='RESTORED_BYTES_AND_RUNTIME_VERIFIED'&&fs.existsSync(path.join(dir,'session.json'))){phase='read-only-reconciliation';cmd('reconcile',['--run',dir,'--secret',o.secret,'--out',path.join(dir,'FC1-READONLY-RECONCILIATION.json')],{allowFailure:true});}
  phase='cost-analysis';const analysis=M.fromRun(executor,dir,v);C.durable(path.join(dir,'FC1-COST-ANALYSIS.json'),analysis);
  const audit=path.join(dir,'fc1-preparation');fs.mkdirSync(audit);for(const n of ['prepare-start.json','source-preparation.json','prepared.json','source-published.json'])C.write(path.join(audit,n),C.read(path.join(o.work,n)));fs.cpSync(path.join(o.work,'source-checks'),path.join(audit,'source-checks'),{recursive:true,errorOnExist:true,force:false});fs.cpSync(o.work+'.package-self-tests',path.join(audit,'package-self-tests'),{recursive:true,errorOnExist:true,force:false});
  phase='archive-and-push';cmd('archive',['--compat',o.compat,'--refactor',o.refactor,'--work',o.work,'--secret',o.secret,'--push']);
  const result={status:'FC1_EVIDENCE_DELIVERED',milestone:analysis.milestone,source:p.source,compatHead:C.head(o.compat),refactorHead:C.head(o.refactor),correctAndCompleteSamples:analysis.correctAndCompleteSamples,recovery:analysis.recoveryStatus,costSummary:analysis.costSummary||null,observationExit:observation.status,performanceTargetCpu:null,evidencePath:P.evidencePath};C.durable(path.join(o.work,'RESULT.json'),result);return result;
 }catch(e){if(e&&typeof e==='object')e.phase=phase;if(fs.existsSync(o.work)&&!fs.existsSync(path.join(o.work,'STOP.json')))C.durable(path.join(o.work,'STOP.json'),{status:'STOP',phase,code:typeof e.code==='string'?e.code:'LOCAL_OPERATION_FAILED',at:new Date().toISOString(),automaticRetryAuthorized:false,instruction:'Preserve all raw files and source state. Do not patch tests, edit the package, clear authorization markers or rerun observe. If live execution began, inspect worker/collector and independent recovery before any other action.'});throw e;}
}
module.exports={run};if(require.main===module)C.cli(()=>run(C.args(['compat','refactor','work','secret'],['execute','offline-only','exclusive-target','prior-workers-stopped'])));
