'use strict';
const fs=require('node:fs'),path=require('node:path'),{performance}=require('node:perf_hooks');
const C=require('./common.cjs'),I=require('./identity.cjs'),P=C.POLICY,T=require('./time-budget.cjs');
const retryable=e=>['HTTP_DEADLINE','HTTP_TRANSPORT_ERROR','HTTP_BODY_ABORTED','HTTP_BODY_ERROR','HTTP_REQUEST_FAILED','HTTP_TRANSIENT_STATUS'].includes(C.code(e));
function budget(end){return requested=>{const n=Math.floor(end-performance.now());if(n<=0)C.fail('READ_DEADLINE');return Math.min(requested,n);};}
async function stable(api,dir,{expected,ms=P.recoveryReadMs,count=2,pause=C.pause}={}){const end=performance.now()+ms;let prior=null,n=0;
 while(performance.now()<end){try{const x=await I.current(api,budget(end));if(expected)expected(x);n=prior&&I.eq(prior.modules,x.modules)?n+1:1;prior=x;C.event(dir,'identity-read',{digest:x.digest,build:x.build,stableReads:n});if(n>=count)return x;await pause(Math.min(5000,Math.max(0,end-performance.now())));}catch(e){C.event(dir,'identity-read-failed',{error:C.code(e)});if(!retryable(e))throw e;n=0;prior=null;await pause(Math.min(5000,Math.max(0,end-performance.now())));}}C.fail('READ_DEADLINE');}
async function ready(api,dir,{ms=P.readinessMs,pause=C.pause}={}){const end=performance.now()+ms;let n=0,last=null,lastTick=-1;
 while(performance.now()<end){try{const b=budget(end),x=await I.current(api,b);I.canonical(x.modules);I.rooms(await api.overview(b(15000)));const t=(await T.readTime(api,dir,'readiness',b(15000))).tick;if(t<lastTick)C.fail('GAME_TICK_REGRESSED');lastTick=t;n=last&&I.eq(x.modules,last.modules)?n+1:1;last=x;C.event(dir,'readiness',{tick:t,stableReads:n,digest:x.digest});if(n===3){const r={status:'CANONICAL_LIVE_BASELINE_VERIFIED',stableReads:3,tick:t,digest:x.digest,atMs:Date.now()};C.durable(path.join(dir,'readiness.json'),r);return {...x,tick:t};}await pause(Math.min(15000,Math.max(0,end-performance.now())));}catch(e){C.event(dir,'readiness-failure',{error:C.code(e)});if(!retryable(e))throw e;n=0;last=null;await pause(Math.min(15000,Math.max(0,end-performance.now())));}}C.fail('READINESS_DEADLINE');}
async function uploadOnce(api,s,dir,canStart=()=>{},{clock=T.clock}={}){return C.lock(dir,'action',async()=>{
 if(C.optional(dir,'candidate-attempt.json')||C.optional(dir,'restore-attempt.json')||C.optional(dir,'closing.json'))C.fail('CANDIDATE_QUOTA_ALREADY_CONSUMED');
 const x=await stable(api,dir,{ms:180000,count:1});if(!I.eq(x.modules,s.backup))C.fail('BASELINE_CHANGED_BEFORE_UPLOAD');const end=performance.now()+30000;I.rooms(await api.overview(budget(end)(15000)));const timeRead=await T.readTime(api,dir,'upload-preflight',budget(end)(15000),clock),t=timeRead.tick;if(t>s.profile.startTick-100||t<s.observedTick)C.fail('PROFILE_EXPIRED');T.admit(dir,timeRead,s.profile,'upload');await canStart();T.ensureFresh(timeRead,clock);if(C.optional(dir,'closing.json'))C.fail('CLOSING_BEFORE_UPLOAD');
 const atMs=clock.wall();const m={runId:P.parentRunId,candidateHash:s.candidateDigest.hash,profileHead:s.profileHead,atMs,mayHaveBeenSent:true,wallBudgetMs:P.wallMs,wallDeadlineAtMs:atMs+P.wallMs,timingAdmissionSha256:C.sha(C.bytes(path.join(dir,'timing-upload.json')))};C.durable(path.join(dir,'candidate-attempt.json'),m);C.event(dir,'code-write-boundary',{action:'candidate'});
 let r;try{const response=await api.upload(s.candidate,s.profileHead,s.profileTree,P.writeMs);const after=await stable(api,dir,{ms:180000,count:1});if(!I.eq(after.modules,s.candidate))C.fail('UPLOAD_READBACK_MISMATCH');r={confirmed:true,accepted:response?.ok===1,digest:after.digest};}catch(e){r={confirmed:false,accepted:null,error:C.code(e)};}
 C.durable(path.join(dir,'upload-result.json'),{...r,atMs:Date.now()});return r;
 });}
async function restoreOnce(api,s,dir,{pause=C.pause}={}){return C.lock(dir,'action',async()=>{
 if(!C.optional(dir,'candidate-attempt.json'))return {status:'NOT_DEPLOYED',confirmed:true,requestAttempted:false};
 const x=await stable(api,dir,{expected:x=>I.state(x.modules,s),pause});if(I.state(x.modules,s)==='CURRENT_IS_BACKUP')return {status:'ALREADY_RESTORED',confirmed:true,requestAttempted:false,digest:x.digest,atMs:Date.now()};
 if(C.optional(dir,'restore-attempt.json'))return {status:'ONLINE_CLOSE_UNCONFIRMED',confirmed:false,requestAttempted:false,reason:'RESTORE_ALREADY_ATTEMPTED'};
 const y=await stable(api,dir,{expected:x=>I.state(x.modules,s),count:1,pause});if(I.state(y.modules,s)==='CURRENT_IS_BACKUP')return {status:'ALREADY_RESTORED',confirmed:true,requestAttempted:false,digest:y.digest,atMs:Date.now()};
 C.durable(path.join(dir,'restore-attempt.json'),{runId:P.parentRunId,candidateHash:s.candidateDigest.hash,backupHash:P.backupDigest.hash,atMs:Date.now(),mayHaveBeenSent:true});C.event(dir,'code-write-boundary',{action:'restore'});
 let accepted=null,error=null;try{accepted=(await api.restore(s.backup,P.writeMs))?.ok===1;}catch(e){error=C.code(e);}
 // Neither a failed nor a lost reply permits another POST. Readback only.
 let after;try{after=await stable(api,dir,{expected:x=>I.state(x.modules,s),pause});}catch(e){error=error||C.code(e);}
 const confirmed=!!after&&I.state(after.modules,s)==='CURRENT_IS_BACKUP';return {status:confirmed?'RESTORED_BYTES_CONFIRMED':'ONLINE_CLOSE_UNCONFIRMED',confirmed,requestAttempted:true,accepted,error,digest:after?.digest||null,atMs:Date.now()};
 });}
function loadSession(dir){const s=C.json(path.join(dir,'session.json'));if(s.runId!==P.parentRunId||s.packageFingerprint!==C.verifyPackage().fingerprint)C.fail('SESSION_IDENTITY_CHANGED');const R=require('../tools/repository.cjs');if(!Number.isSafeInteger(s.observedTick)||s.observedTick<0||!C.same(s.profile,R.profileFor(s.observedTick))||s.source?.base!==P.compatBase||s.source.head!==P.compatBase||s.source.tree!==R.manifest().expectedSourceTree||!C.same(s.backupDigest,P.backupDigest)||![s.source.head,s.profileHead,s.profileTree].every(x=>/^[a-f0-9]{40}$/.test(x||'')))C.fail('SESSION_PROFILE_OR_SOURCE_CHANGED');const selected=require('./window-selection.cjs').verifySelected(dir);if(selected.currentTick!==s.observedTick||C.sha(C.bytes(path.join(dir,'window-selection/result.json')))!==s.windowSelectionFileSha256)C.fail('SESSION_SELECTION_CHANGED');T.verifyPlan(dir,s.profile,'binding');if(C.sha(C.bytes(path.join(dir,'timing-measurement.json')))!==s.timingMeasurementFileSha256||C.sha(C.bytes(path.join(dir,'timing-binding.json')))!==s.timingBindingFileSha256)C.fail('SESSION_TIMING_CHANGED');for(const name of ['backup','candidate']){const b=C.bytes(path.join(dir,name+'.json'));if(C.sha(b)!==s[name+'FileSha256'])C.fail('PRIVATE_SNAPSHOT_CHANGED');s[name]=I.modules(JSON.parse(b));if(!C.same(I.digest(s[name]),name==='backup'?P.backupDigest:s.candidateDigest))C.fail('PRIVATE_SNAPSHOT_DIGEST_CHANGED');}I.canonical(s.backup);if(!C.same(I.candidate(s.candidate,s.profileHead,s.profileTree),s.build))C.fail('SESSION_BUILD_CHANGED');return s;}
module.exports={retryable,budget,stable,ready,uploadOnce,restoreOnce,loadSession};
