'use strict';
const fs=require('node:fs'),path=require('node:path'),{performance}=require('node:perf_hooks');
const C=require('./common.cjs'),A=require('./actions.cjs'),I=require('./identity.cjs'),O=require('./observer.cjs'),R=require('../tools/repository.cjs'),P=C.POLICY;
function collectorHealth(h,now){if(!h||h.runId!==P.parentRunId||!h.streaming||!C.alive(h.pid))return 'COLLECTOR_NOT_STREAMING';if(!Number.isSafeInteger(h.atMs)||h.atMs>now+1000||now-h.atMs>10000)return 'COLLECTOR_HEARTBEAT_STALE';if(!Number.isFinite(h.lastConsole)||!Number.isFinite(h.lastCpu)||now-h.lastConsole>45000||now-h.lastCpu>45000)return 'COLLECTOR_CHANNEL_STALE';if(h.issues?.length)return h.issues[0];if(h.safety)return 'LOCAL_SAFETY_STOP';if(h.accepted===4)return 'FOUR_REPORTS_CAPTURED';return null;}
async function close({dir,s,api,secret,repo,observer=O.observe,verifyObserver=O.verify,pause=C.pause}){const out=path.join(dir,'recovery');fs.mkdirSync(out,{recursive:true});let restoration=C.optional(out,'restore-result.json');if(!restoration){try{restoration=await A.restoreOnce(api,s,dir,{pause});}catch(e){restoration={status:'ONLINE_CLOSE_UNCONFIRMED',confirmed:false,error:C.code(e)};}C.durable(path.join(out,'restore-result.json'),restoration);}
 if(!C.optional(dir,'collector-stop.json'))C.durable(path.join(dir,'collector-stop.json'),{runId:P.parentRunId,atMs:Date.now()});
 let before=null,after=null,runtime=null,error=null;
 if(C.optional(dir,'candidate-attempt.json')){try{const x=await A.stable(api,dir,{expected:x=>I.state(x.modules,s),pause});before={state:I.state(x.modules,s),digest:x.digest,build:x.build,atMs:x.atMs};C.durable(path.join(out,'code-before-runtime.json'),before);if(before.state==='CURRENT_IS_BACKUP'){try{await observer({out,secret,invocationId:P.parentRunId});runtime=verifyObserver(out);}catch(e){error=C.code(e);}const y=await A.stable(api,dir,{expected:x=>I.state(x.modules,s),pause});after={state:I.state(y.modules,s),digest:y.digest,build:y.build,atMs:y.atMs};C.durable(path.join(out,'code-after-runtime.json'),after);}}catch(e){error=C.code(e);}}
 const bytesConfirmed=after?.state==='CURRENT_IS_BACKUP'||(!after&&before?.state==='CURRENT_IS_BACKUP');const uploadOutcomeResolved=!!(C.optional(dir,'upload-result.json')?.confirmed===true||C.optional(dir,'restore-attempt.json'));const runtimeConfirmed=uploadOutcomeResolved&&!!runtime&&before?.state==='CURRENT_IS_BACKUP'&&after?.state==='CURRENT_IS_BACKUP';
 const result={status:!C.optional(dir,'candidate-attempt.json')?'NOT_DEPLOYED':runtimeConfirmed?'RESTORED_BYTES_AND_RUNTIME_VERIFIED':bytesConfirmed?'RESTORED_BYTES_RUNTIME_UNCONFIRMED':'ONLINE_CLOSE_UNCONFIRMED',runtimeConfirmed,bytesConfirmed,uploadOutcomeResolved,error,restoration,runtime,atMs:Date.now()};C.durable(path.join(out,'result.json'),result);try{await R.closeSource(repo,dir);}catch(e){result.sourceCloseError=C.code(e);}return result;}
async function worker({dir,s,api,secret,repo,pause=C.pause,closer=close}){C.durable(path.join(dir,'worker-ready.json'),{runId:P.parentRunId,pid:process.pid,atMs:Date.now()});const begun=performance.now();let reason=null,lastTimeRead=0,lastTick=-1;
 while(!reason){try{const stop=C.optional(dir,'closing.json'),attempt=C.optional(dir,'candidate-attempt.json');if(stop){reason=stop.reason||'EXPLICIT_CLOSE';break;}if(attempt){const h=C.optional(dir,'collector-heartbeat.json');reason=collectorHealth(h,Date.now());if(reason)break;if(Date.now()-attempt.atMs>=P.wallMs||performance.now()-begun>=P.wallMs+300000){reason='WALL_DEADLINE';break;}if(performance.now()-lastTimeRead>15000){lastTimeRead=performance.now();try{const t=I.tick(await api.time(8000));if(t<lastTick)C.fail('GAME_TICK_REGRESSED');lastTick=t;if(t>s.profile.endTick+20)reason='TICK_WINDOW_ENDED';}catch(e){if(!A.retryable(e)){reason=C.code(e);break;}C.event(dir,'worker-time-read-failure',{error:C.code(e)});}}}
 else if(Date.now()-s.preparedAtMs>300000){reason='PREPARATION_EXPIRED';break;}
 const parent=C.optional(dir,'parent-process.json');if(parent&&!C.alive(parent.pid)){reason='PARENT_EXITED';break;}await pause(500);
 }catch(e){reason=C.code(e);}}
 C.event(dir,'close-trigger',{reason});if(!C.optional(dir,'closing.json'))C.durable(path.join(dir,'closing.json'),{runId:P.parentRunId,reason,atMs:Date.now()});let closure;try{closure=await closer({dir,s,api,secret,repo,pause});}catch(e){closure={status:'ONLINE_CLOSE_UNCONFIRMED',runtimeConfirmed:false,error:C.code(e)};try{await R.closeSource(repo,dir);}catch{}}
 const result={runId:P.parentRunId,reason,closure,atMs:Date.now()};C.durable(path.join(dir,'worker-result.json'),result);return result;}
module.exports={collectorHealth,close,worker};if(require.main===module)C.cli(async()=>{const o=C.options(['run','secret','compat']);C.requireArgs(o,['run','secret','compat']);const s=A.loadSession(o.run),secret=C.loadSecret(o.secret),api=require('./transport.cjs').client(secret);await worker({dir:o.run,s,secret,api,repo:o.compat});});
