'use strict';
const C=require('./common.cjs'),S=require('./source.cjs'),A=require('./adapt-executor.cjs'),{fs,path,ROOT,P}=C;
function extract(repo,out){const spec=P.refactorBase+':'+P.inheritedPrefix,raw=C.git(repo,['show',spec+'/INTEGRITY.json']);C.check(C.sha(raw)===P.inheritedIntegritySha256,'INHERITED_INTEGRITY_CHANGED');const m=JSON.parse(raw),names=Object.keys(m.files).sort();C.check(m.kind==='package-integrity/v1'&&names.length===66,'INHERITED_PAYLOAD_SET');
 const entries=C.git(repo,['ls-tree','-r','-z',spec]).toString('utf8').split('\0').filter(Boolean).map(line=>{const[k,n]=line.split('\t');const[mode,type,sha]=k.split(' ');return{mode,type,sha,name:n};});C.check(C.same(entries.map(x=>x.name).sort(),[...names,'INTEGRITY.json'].sort())&&entries.every(x=>x.mode==='100644'&&x.type==='blob'),'INHERITED_TREE_CHANGED');
 C.check(!fs.existsSync(out),'INHERITED_DIR_EXISTS');fs.mkdirSync(out);for(const n of names){C.safePath(n);const b=C.git(repo,['show',spec+'/'+n]),v=m.files[n];C.check(b.length===v.bytes&&C.sha(b)===v.sha256&&C.blob(b)===entries.find(x=>x.name===n).sha,'INHERITED_BYTES_CHANGED:'+n);C.write(path.join(out,n),b);}C.write(path.join(out,'INTEGRITY.json'),raw);C.verify(out);return{commit:P.refactorBase,prefix:P.inheritedPrefix,files:names.length,integritySha256:C.sha(raw)};}
function prior(repo){const f=C.git(repo,['show',P.refactorBase+':'+P.priorFinalPath]),r=C.git(repo,['show',P.refactorBase+':'+P.priorRecoveryPath]);C.check(C.blob(f)===P.priorFinalBlob&&C.blob(r)===P.priorRecoveryBlob,'PRIOR_EVIDENCE_CHANGED');const v=JSON.parse(f),re=JSON.parse(r);C.check(v.captureVerified&&v.sourceOff&&v.rawReports===4&&v.acceptedReports===4&&v.completeSamples===0&&v.writeBoundaries.candidate===1&&v.writeBoundaries.restore===1&&re.status==='RESTORED_BYTES_AND_RUNTIME_VERIFIED'&&re.runtimeConfirmed&&re.bytesConfirmed,'PRIOR_R1_NOT_CLOSED');return{finalBlob:C.blob(f),recoveryBlob:C.blob(r),unchangedHistoricalVerdict:'STRUCTURAL_REVIEW_REQUIRED'};}
function prepare(o){C.verify();C.required(o,['compat','refactor','work']);for(const n of ['compat','refactor','work'])o[n]=path.resolve(o[n]);for(const r of [o.compat,o.refactor,ROOT])C.outside(o.work,r);C.outside(ROOT,o.compat);C.outside(ROOT,o.refactor);C.check(!fs.existsSync(o.work),'WORK_DIR_ALREADY_EXISTS');C.baseline(o.refactor,P.refactorBranch,P.refactorBase);C.baseline(o.compat,P.compatBranch,P.compatBase);C.check(C.json(path.join(o.compat,'node_modules/typescript/package.json')).version===P.compilerVersion,'PINNED_TYPESCRIPT_REQUIRED');S.authorizationUnused(o.compat);
 const priorProof=prior(o.refactor);fs.mkdirSync(o.work);const receipt={package:C.verify(),prior:priorProof,protocol:'FC1',performanceTargetCpu:null,at:new Date().toISOString()};C.durable(path.join(o.work,'prepare-start.json'),receipt);
 const inherited=path.join(o.work,'inherited-executor'),inheritance=extract(o.refactor,inherited);
 const {source,manifest,runtimeArtifacts}=S.apply(o.compat,path.join(o.work,'source-checks'));C.durable(path.join(o.work,'source-preparation.json'),{source,manifest,inheritance,receipt});
 const executor=path.join(o.work,'executor'),info=A.resolve(inherited,executor,source,manifest,receipt,runtimeArtifacts);
 const result={status:'FC1_PREPARED',source,executor,executorFingerprint:info.fingerprint,inheritance,onlineAttempted:false};C.durable(path.join(o.work,'prepared.json'),result);return result;
}
module.exports={extract,prior,prepare};if(require.main===module)C.cli(()=>prepare(C.args(['compat','refactor','work'])));
