'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..'),P=require('../tools/source-patch.cjs'),D=require('../source/implementation/scripts/lib/treasury-compat-envelope.cjs');
const ts=require(process.env.CPU_DIAG_TS_MODULE);const read=n=>fs.readFileSync(path.join(ROOT,n),'utf8').replace(/\r\n/g,'\n');
function api(text){const js=ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText,ctx=vm.createContext({exports:{}});vm.runInContext(js,ctx,{timeout:5000});return ctx.exports;}
test('XII preview transform exactly maps XI to XII',()=>assert.equal(D.transform(read('source/implementation/test/treasury-compat/fixtures/reader-before-envelope-optimization-xii.ts.txt')),read('source/implementation/src/runtime/treasuryCompatRead.ts')));
test('XII preview transform exactly reverses',()=>assert.equal(D.restore(read('source/implementation/src/runtime/treasuryCompatRead.ts')),read('source/implementation/test/treasury-compat/fixtures/reader-before-envelope-optimization-xii.ts.txt')));
test('XII preview transform has eight fixed rules',()=>{assert.equal(D.rules.length,8);assert.ok(D.rules.every(x=>x.replacements===1));});
test('XII transform refuses shifted source',()=>assert.throws(()=>D.transform(read('source/implementation/test/treasury-compat/fixtures/reader-before-envelope-optimization-xii.ts.txt').replace('const memory = ports.memory();','const memory  = ports.memory();')),/ENVELOPE_XII_TRANSFORM_COUNT/));
test('XII CPU completion is tail-only',()=>{const c=api(read('source/implementation/src/runtime/treasuryCompatCpu.ts')).createCompatCpuAccounting(0,100,1);c.checkpoint(.4,'serializationAndSize');c.checkpoint(.6,'emit');c.checkpoint(.7,'retention');c.checkpoint(.75);const p=c.snapshot('afterRetention');assert.equal(p.completion,'tail_only');assert.deepEqual(Object.keys(p.phases).sort(),['emit','retention','serializationAndSize']);assert.equal(p.attribution,undefined);});
test('XII CPU prefix remains full',()=>{const c=api(read('source/implementation/src/runtime/treasuryCompatCpu.ts')).createCompatCpuAccounting(0,100,1);c.attributionWork({observationRooms:2});c.checkpoint(.4,'serializationAndSize');const p=c.snapshot('beforeSerialization');assert.equal(p.completion,undefined);assert.equal(p.attribution.work.observationRooms,2);assert.ok(Object.hasOwn(p.phases,'legacyInputs'));});
test('source patch fixes eleven paths',()=>{assert.equal(P.PATHS.length,11);assert.equal(new Set(P.PATHS).size,11);assert.equal(P.NEW.length,5);});
test('fixed implementation payload identities are internally stable',()=>{for(const[rel,x]of Object.entries(P.expectedFixed()))assert.deepEqual(P.identity(P.payload(rel)),x);});
test('current generator exports a composed IX-to-XII preview transform',()=>{const s=read('source/implementation/scripts/build-treasury-compat-loader.cjs');assert.match(s,/const P_XI = require\('\.\/lib\/treasury-compat-preview-hotpath\.cjs'\)/);assert.match(s,/transform\(text\) \{ return D\.transform\(P_XI\.transform\(text\)\); \}/);assert.match(s,/restore\(text\) \{ return P_XI\.restore\(D\.restore\(text\)\); \}/);assert.match(s,/P_XI, P, D/);});
test('repository envelope tests compare cross-realm call records by primitive serialization',()=>{const s=read('source/implementation/test/treasury-compat/envelope-optimization.spec.cjs');assert.match(s,/const realmNeutral = value => JSON\.stringify\(value\)/);for(const expr of ['p.calls','current.calls','tail.calls'])assert.doesNotMatch(s,new RegExp('deepEqual\\([^\\n]*'+expr.replace('.','\\.') ));});
