'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const H=require('./helpers.cjs'),Q=require('../runtime/readiness.cjs'),C=H.C;
const overview=(rooms=['E3N59','E4N58'])=>({ok:1,shards:{shard1:{rooms}}});
function clock(){let n=0;return()=>++n;}
test('transient deadline before three stable rounds is absorbed before binding authority exists',async()=>{let i=0,t=100,events=[];const r=await Q.establish({guard:H.guard,stableReads:3,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},record:x=>events.push(x),readIdentity:async()=>{if(i++===0)throw new C.Failure('HTTP_DEADLINE');return H.sample('same',H.digest(),H.build(),i);},readOverview:async()=>overview(),readTime:async()=>({ok:1,time:t++})});assert.equal(r.status,'ONLINE_READINESS_VERIFIED');assert.equal(r.attempts,4);assert.equal(r.authorization.canonicalBaselineAccepted,true);assert.equal(events.filter(x=>x.outcome==='transient_failure').length,1);});
test('module change resets the consecutive stability streak',async()=>{let i=0;const seq=['a','b','b','b'];const r=await Q.establish({guard:H.guard,stableReads:3,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},readIdentity:async()=>H.sample(seq[i++]||'b'),readOverview:async()=>overview(),readTime:async()=>({ok:1,time:100+i})});assert.equal(r.attempts,4);assert.equal(r.stableReads.length,3);});
test('stable observed digest drift becomes a terminal read-only block',async()=>{const d=H.digest(4494466,'eaa54506'+'0'.repeat(56),'1'.repeat(64));await assert.rejects(()=>Q.establish({guard:H.guard,stableReads:3,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},readIdentity:async()=>H.sample('same',d),readOverview:async()=>overview(),readTime:async()=>({ok:1,time:100})}),e=>{assert.equal(e.code,'LIVE_BASELINE_DRIFT_UNRESOLVED');assert.ok(e.readinessIdentity);assert.equal(e.readinessSamples.length,3);return true;});});
test('authentication rejection is terminal and not waited out',async()=>{let calls=0;await assert.rejects(()=>Q.establish({guard:H.guard,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},readIdentity:async()=>{calls++;throw new C.Failure('HTTP_AUTH_REJECTED');},readOverview:async()=>overview(),readTime:async()=>({ok:1,time:100})}),e=>e.code==='HTTP_AUTH_REJECTED');assert.equal(calls,1);});
test('missing target room is terminal before any baseline authorization',async()=>{await assert.rejects(()=>Q.establish({guard:H.guard,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},readIdentity:async()=>H.sample(),readOverview:async()=>overview(['E3N59']),readTime:async()=>({ok:1,time:100})}),e=>e.code==='OBSERVATION_ROOM_NOT_OWNED');});
test('unending transport failure reaches a bounded readiness deadline',async()=>{let n=0;await assert.rejects(()=>Q.establish({guard:H.guard,wallMs:6,intervalMs:1,mono:()=>++n,pause:async()=>{},readIdentity:async()=>{throw new C.Failure('HTTP_DEADLINE');},readOverview:async()=>overview(),readTime:async()=>({ok:1,time:100})}),e=>e.code==='ONLINE_READINESS_DEADLINE');});
test('readiness public sample never contains module bytes',()=>{const s=Q.safeSample(H.sample('secret-source'),100,['E3N59','E4N58'],1);assert.equal(Object.hasOwn(s,'modules'),false);assert.equal(Object.hasOwn(s,'digest'),true);});
test('readiness policy requires three stable samples and a 30-minute outer wall',()=>{const K=require('../runtime/policy.cjs');assert.equal(K.READINESS_STABLE_READS,3);assert.equal(K.READINESS_WALL_MS,1800000);assert.equal(K.READINESS_INTERVAL_MS,15000);});
test('unknown live drift is explicitly terminal in readiness policy',()=>assert.equal(Q.TERMINAL.has('LIVE_BASELINE_DRIFT_UNRESOLVED'),true));
test('game tick regression is terminal rather than retried into a later window',async()=>{let t=101;await assert.rejects(()=>Q.establish({guard:H.guard,stableReads:3,wallMs:1000,intervalMs:1,mono:clock(),pause:async()=>{},readIdentity:async()=>H.sample(),readOverview:async()=>overview(),readTime:async()=>({ok:1,time:t--})}),e=>e.code==='GAME_TICK_REGRESSED');});

test('each readiness callback receives the remaining outer-wall budget',async()=>{let n=0,budgets=[];await assert.rejects(()=>Q.establish({guard:H.guard,stableReads:3,wallMs:500,intervalMs:1,mono:()=>++n,pause:async()=>{},readIdentity:async(_a,b)=>{budgets.push(b);throw new C.Failure('HTTP_DEADLINE');},readOverview:async()=>overview(),readTime:async()=>({ok:1,time:100})}),e=>e.code==='ONLINE_READINESS_DEADLINE');assert.ok(budgets.length>0);assert.ok(budgets.every(b=>b<=500&&b>=100));});
