'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const C=require('../tools/common.cjs'),N=require('../tools/integration.cjs'),Prep=require('../tools/prepare.cjs'),M=require('../tools/milestone.cjs');
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'read-path-r1-test-'));
function goldenReport(tick=100,prefix=1.6){return {kind:'treasury-legacy-read-bridge',tick,shard:'shard1',scope:{rooms:['E3N59','E4N58'],resources:['energy','H'],isEmpireTotal:false},authorizesActions:false,facadeQueryRun:false,kernelLifecycleRun:false,spendable:null,storageMode:'heap_only',status:'sampled',cpuBeforeSerializationAndEmit:prefix,cpuProfile:{calls:{readerLoad:1,observationBuild:1,commitmentBuild:1},attribution:{work:{projectionRowsCompleted:4,projectionRowsPlanned:4,projectionIndexQueries:16,commitmentReservationRecords:0}}},requestedEndpointRows:4,collectedEndpointRows:4,endpoints:['E3N59','E4N58'].flatMap(room=>['storage','terminal'].map(location=>({room,location,directStatus:'ok',coreComparison:'match_selected_scope',coreMismatches:[]}))),commitments:{status:'read_complete',allTableScan:true,completeness:{complete:true,globalIncomplete:false,invalidRecords:0,incompleteScopeCount:0},rows:['E3N59','E4N58'].flatMap(room=>['energy','H'].map(resource=>({room,resource,scope:'room_not_endpoint',outgoing:70,incoming:20,productionReserved:1,completeness:'complete'})))},localSafety:{latched:false}};}
function verification(){return {status:'CPU_DIAGNOSTIC_CAPTURE_VERIFIED',captureVerified:true,closure:'RESTORED_BYTES_AND_RUNTIME_VERIFIED',sourceOff:true,uploadOutcomeResolved:true,rawReports:4,acceptedReports:4,completeSamples:4,duplicates:0,expectedTicks:[100,200,300,400],acceptedTicks:[100,200,300,400],writeBoundaries:{candidate:1,restore:1},issues:[],completedTailProfiles:[{tick:100,elapsed:2.2},{tick:200,elapsed:2.2},{tick:300,elapsed:2.2}]};}
function pair(prefix=1.6){return [verification(),[100,200,300,400].map(t=>goldenReport(t,prefix))];}
for(const s of ['../x','a/../b','/root','a\\b','C:/x','a:b','a//b','a/','a\0b','CON','a/NUL.txt','a/end.','a/end ','a?b'])test('unsafe inherited archive path rejects: '+JSON.stringify(s),()=>assert.throws(()=>C.safePath(s)));
test('regular nested archive path accepted',()=>assert.equal(C.safePath('runtime/worker.cjs'),'runtime/worker.cjs'));
test('package seal rejects mutation, missing and extra files',()=>{const d=temp();try{C.write(path.join(d,'one.txt'),'one\n');const v=C.seal(d);assert.equal(v.files,1);fs.appendFileSync(path.join(d,'one.txt'),'x');assert.throws(()=>C.verify(d),/PACKAGE_BYTES_CHANGED/);fs.writeFileSync(path.join(d,'one.txt'),'one\n');C.write(path.join(d,'extra.txt'),'extra');assert.throws(()=>C.verify(d),/PACKAGE_FILE_SET_CHANGED/);fs.unlinkSync(path.join(d,'extra.txt'));fs.unlinkSync(path.join(d,'one.txt'));assert.throws(()=>C.verify(d),/PACKAGE_FILE_SET_CHANGED/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('symbolic links are not an authorized payload',()=>{const d=temp();try{fs.mkdirSync(path.join(d,'plain'));C.write(path.join(d,'plain','file.txt'),'x');fs.symlinkSync(path.join(d,'plain'),path.join(d,'link'),process.platform==='win32'?'junction':'dir');assert.throws(()=>C.list(d),/SYMLINK/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('durable evidence refuses to overwrite an existing result',()=>{const d=temp();try{C.durable(path.join(d,'result.json'),{v:1});assert.throws(()=>C.durable(path.join(d,'result.json'),{v:2}));assert.equal(C.json(path.join(d,'result.json')).v,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('work directory isolation checks real paths and descendants',()=>{const d=temp();try{fs.mkdirSync(path.join(d,'repo'));assert.throws(()=>C.outside(path.join(d,'repo','work'),path.join(d,'repo')),/DIRECTORY_NOT_ISOLATED/);assert.doesNotThrow(()=>C.outside(path.join(d,'outside'),path.join(d,'repo')));}finally{fs.rmSync(d,{recursive:true,force:true});}});
for(const[file,p]of Object.entries(N.PATCHES))test('fixed integration anchors compose and reverse without deleting assertions: '+file,()=>{const source=p.changes.flatMap(r=>Array(r.count).fill(r.before)).join('\n/* boundary */\n');const after=N.rewrite(source,p.changes);assert.equal(N.rewrite(after,p.changes,true),source);assert.throws(()=>N.rewrite(source+source,p.changes),/INTEGRATION_ANCHOR_COUNT/);assert.throws(()=>N.patch(file,Buffer.from(source)),/INTEGRATION_BASE_CHANGED/);});
test('fixed current core identity and canonical inverse verified',()=>{N.verifyCurrentCore(C.read(path.join(C.ROOT,'fixtures/core-R1.expected.ts.txt')));assert.throws(()=>N.verifyCurrentCore(Buffer.from('arbitrary code')),/IDENTITY_CHANGED/);});
function fixtureManifest(){const files={},entries=[];for(let i=0;i<66;i++){const name=`file-${i}.txt`;files[name]={bytes:0,sha256:C.sha(Buffer.alloc(0))};entries.push({name,mode:'100644',type:'blob',sha:C.blob(Buffer.alloc(0))});}entries.push({name:'INTEGRITY.json',mode:'100644',type:'blob',sha:'a'.repeat(40)});return [{kind:'package-integrity/v1',files},entries];}
test('inherited manifest accepts only its entire fixed file set',()=>{const[m,e]=fixtureManifest();assert.equal(Prep.verifyArchiveEntries(m,e).length,66);assert.throws(()=>Prep.verifyArchiveEntries(m,e.slice(1)),/FILE_SET_CHANGED/);});
test('inherited git modes reject symlink and executable substitutions',()=>{for(const mode of ['120000','100755','160000']){const[m,e]=fixtureManifest();e[0].mode=mode;assert.throws(()=>Prep.verifyArchiveEntries(m,e),/MODE_CHANGED/);}});
test('inherited duplicate case names are rejected before writing',()=>{const[m,e]=fixtureManifest();delete m.files['file-1.txt'];m.files['FILE-0.txt']={bytes:0,sha256:C.sha(Buffer.alloc(0))};e[1].name='FILE-0.txt';assert.throws(()=>Prep.verifyArchiveEntries(m,e),/CASE_COLLISION/);});
test('inherited byte extraction really uses pinned Git objects',()=>{const d=temp(),saved={...C.P};try{const repo=path.join(d,'repo');fs.mkdirSync(repo);C.git(repo,['init']);C.git(repo,['config','user.name','Fixture']);C.git(repo,['config','user.email','fixture@example.invalid']);const[m]=fixtureManifest();for(const n of Object.keys(m.files))C.write(path.join(repo,'package',n),'');C.durable(path.join(repo,'package','INTEGRITY.json'),m);C.git(repo,['add','.']);C.git(repo,['commit','-m','fixture']);C.P.refactorBase=C.head(repo);C.P.inheritedPrefix='package';C.P.inheritedIntegritySha256=C.sha(C.read(path.join(repo,'package','INTEGRITY.json')));const out=path.join(d,'out');assert.equal(Prep.extractInherited(repo,out).files,66);assert.equal(C.verify(out).files,66);C.P.inheritedIntegritySha256='0'.repeat(64);assert.throws(()=>Prep.extractInherited(repo,path.join(d,'tampered')),/PACKAGE_IDENTITY_CHANGED/);}finally{Object.assign(C.P,saved);fs.rmSync(d,{recursive:true,force:true});}});
test('runtime policy binds a new one-shot authorization without loosening timing/recovery',()=>{const old={authorizationId:'compat-read-envelope-XV-online-I-retry-I-2026-09-23',compilerVersion:'5.9.3',wallMs:4500000,points:4,runtimeMs:75000,selection:{minimumSlackMs:180000,maxRounds:6},timing:{safetyFactor:1.5},backupDigest:{hash:'unchanged'},kind:'inherited/v1',priorAttemptPath:'historical'};const p=Prep.resolvedPolicy(old,{head:'a'.repeat(40),tree:'b'.repeat(40)});assert.notEqual(p.authorizationId,old.authorizationId);assert.equal(p.priorAttemptPath,'historical');assert.deepEqual(p.selection,old.selection);assert.deepEqual(p.timing,old.timing);assert.deepEqual(p.backupDigest,old.backupDigest);assert.equal(p.repositoryNodeTests,467);assert.equal(p.implementationBase,C.P.compatBase);assert.throws(()=>Prep.resolvedPolicy({...old,wallMs:9999999},{}),/POLICY_CHANGED/);});
test('new source allowlist cannot change config, preview, CPU probes, main, dependency locks or writer',()=>{assert.equal(C.P.sourcePaths.length,9);assert.equal(new Set(C.P.sourcePaths).size,9);for(const n of ['src/runtime/treasuryCompatConfig.ts','src/runtime/treasuryCompatRead.ts','src/runtime/treasuryCompatCpu.ts','src/main.ts','package-lock.json','src/runtime/resourceControl.ts'])assert.ok(!C.P.sourcePaths.includes(n));});
test('milestone requires the complete four-point business path and reports tails separately',()=>{const x=M.analyze(...pair());assert.equal(x.milestone,'FOUR_POINT_READ_PATH_COMPLETE_WITH_MARGIN');assert.equal(x.businessGatePassed,true);assert.equal(x.completedTails.length,3);assert.equal(x.finalSampleTailObserved,false);assert.equal(x.fullCompatibilityObserved,false);assert.equal(x.productionSwitchAuthorized,false);assert.equal(x.nonemptyReservationsOnlineCovered,false);});
for(const prefix of [1.8,1.800001,1.99,2,2.000001,NaN,Infinity,-1])test('unchanged CPU gate and explicit margin target: '+prefix,()=>{const x=M.analyze(...pair(prefix));if(prefix>=0&&prefix<=1.8)assert.equal(x.milestone,'FOUR_POINT_READ_PATH_COMPLETE_WITH_MARGIN');else if(prefix>1.8&&prefix<2)assert.equal(x.milestone,'COMPLETE_WITHOUT_CLEAR_MARGIN_REVIEW_REQUIRED');else assert.equal(x.milestone,'STRUCTURAL_REVIEW_REQUIRED');});
for(const [name,mutate]of Object.entries({noObservation:r=>r.cpuProfile.calls.observationBuild=0,noCommitment:r=>r.cpuProfile.calls.commitmentBuild=0,zeroRows:r=>r.commitments.rows=[],noProjection:r=>r.cpuProfile.attribution.work.projectionRowsCompleted=0,missingQueries:r=>r.cpuProfile.attribution.work.projectionIndexQueries=12,coreMismatch:r=>r.endpoints[0].coreComparison='mismatch',scope:r=>r.scope.isEmpireTotal=true,authorization:r=>r.authorizesActions=true,partial:r=>r.status='partial_cpu_budget',damagedIndex:r=>r.commitments.completeness.complete=false,safety:r=>r.localSafety.latched=true,duplicateEndpoint:r=>r.endpoints[0]=r.endpoints[1],invalidValue:r=>r.commitments.rows[0].outgoing=-1}))test('business gate rejects '+name,()=>{const[v,r]=pair();mutate(r[2]);assert.equal(M.analyze(v,r).milestone,'STRUCTURAL_REVIEW_REQUIRED');});
test('legacy projection mismatch stays separate from direct/Core parity',()=>{const[v,r]=pair();r[0].endpoints[0].legacyProjection={status:'mismatch',mismatches:['terminalEnergy']};const x=M.analyze(v,r);assert.equal(x.businessGatePassed,true);assert.equal(x.legacyProjectionMismatches.length,1);});
test('zero online reservations do not claim nonempty coverage',()=>{const[v,r]=pair();r[1].cpuProfile.attribution.work.commitmentReservationRecords=3;assert.equal(M.analyze(v,r).nonemptyReservationsOnlineCovered,true);});
test('partial, duplicated and shifted reports cannot be promoted',()=>{for(const alter of [(v,r)=>r.pop(),(v,r)=>r.push(r[0]),(v,r)=>r[0].tick=99,(v,r)=>v.acceptedTicks=[100,200,300,500],(v,r)=>v.expectedTicks=[100,200,300,500]]){const[v,r]=pair();alter(v,r);assert.notEqual(M.analyze(v,r).milestone,'FOUR_POINT_READ_PATH_COMPLETE_WITH_MARGIN');}});
test('capture issues and extra write boundaries remain inconclusive',()=>{for(const alter of [v=>v.issues.push('UNTRUSTED'),v=>v.captureVerified=false,v=>v.writeBoundaries.candidate=2,v=>v.duplicates=1]){const[v,r]=pair();alter(v);assert.equal(M.analyze(v,r).milestone,'EXPERIMENT_INCONCLUSIVE_REVIEW_REQUIRED');}});
test('successful business output cannot replace independent recovery',()=>{for(const closure of ['ONLINE_CLOSE_UNCONFIRMED','RESTORED_BYTES_RUNTIME_UNCONFIRMED']){const[v,r]=pair();v.closure=closure;assert.equal(M.analyze(v,r).milestone,'RECOVERY_NOT_CLOSED');}});
test('no-deployment is not a performance failure or budget success',()=>{const v={status:'NOT_DEPLOYED',closure:'NOT_DEPLOYED',sourceOff:true,writeBoundaries:{candidate:0,restore:0},issues:[]};const r=M.analyze(v);assert.equal(r.milestone,'NOT_DEPLOYED_NO_PERFORMANCE_CONCLUSION');assert.equal(r.businessGatePassed,undefined);v.writeBoundaries.candidate=1;assert.notEqual(M.analyze(v).milestone,'NOT_DEPLOYED_NO_PERFORMANCE_CONCLUSION');});
test('HTML escaped reports decode, wrong channels ignore, wrong run rejects',()=>{const run='a'.repeat(32),user='user-fixture';const report=goldenReport(),text=JSON.stringify(report).replaceAll('"','&#x22;');const e={kind:'ws-frame',runId:run,redacted:false,text:JSON.stringify([`user:${user}/console`,{shard:'shard1',messages:{log:[text]}}])};const line=JSON.stringify(e)+'\n';assert.deepEqual(M.reportsFromLog(line,run,user),[report]);assert.deepEqual(M.reportsFromLog(line,run,'other'),[]);assert.throws(()=>M.reportsFromLog(line,'b'.repeat(32),user),/IDENTITY/);assert.throws(()=>M.reportsFromLog(line.slice(0,-1),run,user),/TRUNCATED/);});
test('outer runner contains one observe call, no direct network uploader or write retry',()=>{const s=C.read(path.join(C.ROOT,'tools/run.cjs')).toString();assert.equal(s.split("cmd('observe'").length,2);assert.ok(!s.includes('api.upload(')&&!s.includes('api.restore(')&&!s.includes('fetch('));assert.ok(s.includes("cmd('reconcile'"));});
