'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),C=require('../runtime/common.cjs'),I=require('../runtime/identity.cjs'),A=require('../runtime/actions.cjs'),P=C.POLICY;
const {tmp,mk,scene}=require('./helpers.cjs');
test('candidate one-shot boundary exists before request and refuses repetition',async()=>{const d=tmp(),x=scene(d);try{const up=x.api.upload;x.api.upload=async(...args)=>{assert.ok(C.optional(d,'candidate-attempt.json'));return up(...args);};assert.equal((await A.uploadOnce(x.api,x.s,d,()=>{},{clock:x.clock})).confirmed,true);await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>{},{clock:x.clock}));assert.deepEqual(x.writes,[1,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('closing raised during preflight prevents candidate POST',async()=>{const d=tmp(),x=scene(d);try{await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>C.durable(path.join(d,'closing.json'),{}),{clock:x.clock}));assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('failed restore response is reconciled, never automatically retried',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(x.s.candidate);let posts=0;x.api.restore=async()=>{posts++;assert.ok(C.optional(d,'restore-attempt.json'));throw new C.Failure('HTTP_TRANSPORT_ERROR');};const a=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}}),b=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(a.confirmed,false);assert.equal(b.reason,'RESTORE_ALREADY_ATTEMPTED');assert.equal(posts,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('lost reply after accepted restore is confirmed using reads only',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(x.s.candidate);let posts=0;x.api.restore=async m=>{posts++;x.setCurrent(m);throw new C.Failure('HTTP_TRANSPORT_ERROR');};const a=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(a.confirmed,true);assert.equal(a.error,'HTTP_TRANSPORT_ERROR');assert.equal(posts,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('already backup consumes no restore marker and performs no POST',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});assert.equal((await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}})).confirmed,true);assert.equal(C.optional(d,'restore-attempt.json'),null);assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('third-party code is not overwritten',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(mk('d'.repeat(40)));await assert.rejects(A.restoreOnce(x.api,x.s,d,{pause:async()=>{}}),/CONFLICT_CURRENT/);assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('absence of candidate marker never causes a recovery write',async()=>{const d=tmp(),x=scene(d);try{const r=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(r.status,'NOT_DEPLOYED');assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('authorization and schema errors are not classified as network retries',()=>{for(const k of ['ACCOUNT_MISMATCH','LIVE_BASELINE_DRIFT_UNRESOLVED','GAME_TICK_REGRESSED','ACTIVE_BRANCH_CHANGED'])assert.equal(A.retryable(new C.Failure(k)),false);assert.equal(A.retryable(new C.Failure('HTTP_DEADLINE')),true);});
module.exports={mk,scene,tmp};

test('unchanged execution modules and canonical typed-module guard retain pinned bytes',()=>{for(const[n,x]of Object.entries(require('../references/inherited-modules.json'))){const b=fs.readFileSync(path.join(__dirname,'..',n));assert.equal(b.length,x.bytes);assert.equal(C.sha(b),x.sha256);}assert.equal(C.blob(fs.readFileSync(path.join(__dirname,'../vendor/deployGuard.cjs'))),P.guardBlob);});
