'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const C=require('../runtime/common.cjs'),T=require('../runtime/time-budget.cjs'),R=require('../tools/repository.cjs'),A=require('../runtime/actions.cjs'),W=require('../runtime/worker.cjs'),P=C.POLICY;
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'xiv-timing-'));
function fake(){return {id:'f'.repeat(32),now:0,offset:1700000000000,mono(){return this.now;},wall(){return this.offset+this.now;},async pause(ms){this.now+=ms;}};}
function rows({tickStep=5,stepMs=20000,latency=0,count=7}={}){return Array.from({length:count},(_,i)=>({runId:P.parentRunId,id:(i+1).toString(16).padStart(32,'0'),clockId:'f'.repeat(32),pid:process.pid,purpose:'rate-measurement',ok:true,tick:i*tickStep,sentMonoMs:i*stepMs,receivedMonoMs:i*stepMs+latency,sentAtMs:1700000000000+i*stepMs,receivedAtMs:1700000000000+i*stepMs+latency}));}
function current(m,tick=50,elapsed=10000,stage='binding'){const r=structuredClone(m.lastRead);r.id=crypto.randomBytes(16).toString('hex');r.tick=tick;r.purpose=stage==='binding'?'bind-preflight':'upload-preflight';for(const k of ['sentMonoMs','receivedMonoMs','sentAtMs','receivedAtMs'])r[k]+=elapsed;return r;}
function store(dir,rs=rows()){for(const r of rs)C.append(path.join(dir,'time-observations.jsonl'),r);const m=T.measurement(rs);C.durable(path.join(dir,'timing-measurement.json'),m);return m;}

test('seven successful reads spanning two minutes yield measured and padded rate',()=>{const m=T.measurement(rows());assert.equal(m.samples,7);assert.equal(m.spanMs,120000);assert.equal(m.tickAdvance,30);assert.equal(m.worstObservedMsPerTick,4000);assert.equal(m.conservativeMsPerTick,6000);});
test('latency is conservatively included instead of pretending responses mark server instants',()=>{assert.equal(T.measurement(rows({latency:1000})).worstObservedMsPerTick,4200);});
test('fast observed ticks retain a five-second conservative floor',()=>{assert.equal(T.measurement(rows({tickStep:20})).conservativeMsPerTick,5000);});
test('insufficient sample count is rejected',()=>{assert.throws(()=>T.measurement(rows({count:6})),/INSUFFICIENT/);});
test('insufficient elapsed span is rejected even with enough ticks',()=>{assert.throws(()=>T.measurement(rows({stepMs:10000})),/INSUFFICIENT/);});
test('insufficient tick progress is rejected even with long wall time',()=>{assert.throws(()=>T.measurement(rows({tickStep:1})),/INSUFFICIENT/);});
test('a tick regression fails closed',()=>{const r=rows();r[4].tick=2;assert.throws(()=>T.measurement(r),/REGRESSED/);});
test('mixing monotonic timestamps from different processes is rejected',()=>{const r=rows();r[4].clockId='e'.repeat(32);assert.throws(()=>T.measurement(r),/CLOCK_OR_ORDER/);});
test('clock offset discontinuity across reads is rejected',()=>{const r=rows();r[4].sentAtMs-=10000;r[4].receivedAtMs-=10000;assert.throws(()=>T.measurement(r),/CLOCK_DISCONTINUITY/);});
test('duplicate read IDs cannot inflate measurement count',()=>{const r=rows();r[6].id=r[5].id;assert.throws(()=>T.measurement(r),/READ_SET/);});
test('stalled reads remain in the time denominator when advancement resumes',()=>{const r=rows();r[2].tick=r[1].tick;const m=T.measurement(r);assert.equal(m.samples,7);assert.ok(m.worstObservedMsPerTick>=4000);});
test('read-only calibration uses an injected clock and stores every successful read',async()=>{const d=tmp(),c=fake();try{const m=await T.calibrate({time:async()=>({ok:1,time:Math.floor(c.now/4000)})},d,{c,pause:ms=>c.pause(ms)});assert.equal(m.samples,7);assert.equal(T.loadMeasurement(d).conservativeMsPerTick,6000);assert.equal(C.jsonl(path.join(d,'time-observations.jsonl')).length,7);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('transient calibration GET failure is logged and bounded, not erased',async()=>{const d=tmp(),c=fake();let calls=0;try{const m=await T.calibrate({time:async()=>{if(++calls===3)throw new C.Failure('HTTP_TRANSPORT_ERROR');return {ok:1,time:Math.floor(c.now/4000)};}},d,{c,pause:ms=>c.pause(ms)});assert.ok(m.samples>=7);assert.equal(C.jsonl(path.join(d,'time-observations.jsonl')).filter(x=>!x.ok).length,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('a halted shard reaches finite calibration deadline and writes no candidate marker',async()=>{const d=tmp(),c=fake();try{await assert.rejects(T.calibrate({time:async()=>({ok:1,time:0})},d,{c,pause:ms=>c.pause(ms)}),/MEASUREMENT_INCONCLUSIVE/);assert.equal(c.now,P.timing.measurementMaxMs);assert.equal(C.optional(d,'candidate-attempt.json'),null);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('invalid game-time response is not retried',async()=>{const d=tmp(),c=fake();let calls=0;try{await assert.rejects(T.calibrate({time:async()=>{calls++;return {ok:1,time:-1};}},d,{c,pause:ms=>c.pause(ms)}),/GAME_TICK_INVALID/);assert.equal(calls,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('a single read cannot silently outlive its supplied outer budget',async()=>{const d=tmp(),c=fake();try{await assert.rejects(T.readTime({time:async()=>{c.now+=101;return {ok:1,time:1};}},d,'worker-progress',100,c),/TIME_READ_DEADLINE/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('reported XIV timeline demonstrates old 30-minute cap is insufficient',()=>{const elapsedFirst=1790008192117-1790006983637,spacing=1790008596091-1790008192117;assert.equal(elapsedFirst,1208480);assert.equal(spacing,403974);assert.equal(elapsedFirst+3*spacing,2420402);assert.ok(elapsedFirst+3*spacing>1800000);});
test('same conservative four-point plan fits fixed 75 minutes but not old 30',()=>{const m=T.measurement(rows()),read=current(m,51),p=R.profileFor(51),r=T.plan(m,read,p,'binding');assert.equal(r.remainingTicks,549);assert.equal(r.requiredMs,3534000);assert.equal(r.status,'TIME_BUDGET_ADMITTED');assert.ok(r.requiredMs>1800000&&r.requiredMs<P.wallMs);});
test('slow sampled shard is declined rather than stretching the fixed cap',()=>{const m=T.measurement(rows({stepMs:40000})),read=current(m,51),r=T.plan(m,read,R.profileFor(51),'binding');assert.equal(r.status,'TIME_BUDGET_INSUFFICIENT');assert.equal(r.exposureLimitMs,4500000);});
test('time budget includes the final report delivery allowance',()=>{const m=T.measurement(rows()),r=T.plan(m,current(m),R.profileFor(50),'binding');assert.equal(r.requiredMs,r.estimatedRemainingMs+240000);});
test('newly observed slowdown before upload increases the conservative rate',()=>{const m=T.measurement(rows()),r=T.plan(m,current(m,31,240000,'upload'),R.profileFor(50),'upload');assert.equal(r.status,'TIME_BUDGET_INSUFFICIENT');assert.ok(r.conservativeMsPerTick>m.conservativeMsPerTick);});
test('calibration age cannot be refreshed by copying its JSON into another directory',()=>{const m=T.measurement(rows());assert.throws(()=>T.plan(m,current(m,100,600001,'upload'),R.profileFor(50),'upload'),/EVIDENCE_STALE/);});
test('no tick progress after a full polling interval prevents upload',()=>{const m=T.measurement(rows());assert.throws(()=>T.plan(m,current(m,30,20000,'upload'),R.profileFor(50),'upload'),/PROGRESS_STALLED/);});
test('pre-upload check requires at least 100 ticks before first point',()=>{const m=T.measurement(rows());assert.throws(()=>T.plan(m,current(m,101,10000,'upload'),R.profileFor(50),'upload'),/PROFILE_EXPIRED/);});
test('modified CPU, interval, scope or fifth point cannot pass time admission',()=>{const m=T.measurement(rows()),r=current(m);for(const delta of [{maxSampleCpu:3},{reserveCpu:1},{endTick:600},{intervalTicks:50},{rooms:['E3N59']}])assert.throws(()=>T.plan(m,r,{...R.profileFor(50),...delta},'binding'),/PROFILE_INVALID/);});
test('independent recalculation rejects a forged rate estimate',()=>{const d=tmp();try{store(d);const f=path.join(d,'timing-measurement.json'),m=C.json(f);m.conservativeMsPerTick=1;fs.writeFileSync(f,JSON.stringify(m));assert.throws(()=>T.loadMeasurement(d),/MEASUREMENT_CHANGED/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('independent recalculation rejects altered admission slack',()=>{const d=tmp();try{const m=store(d),r=current(m);C.append(path.join(d,'time-observations.jsonl'),r);T.admit(d,r,R.profileFor(50),'binding');const f=path.join(d,'timing-binding.json'),p=C.json(f);p.slackMs++;fs.writeFileSync(f,JSON.stringify(p));assert.throws(()=>T.verifyPlan(d,R.profileFor(50),'binding'),/ADMISSION_INVALID/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('stale final read is rejected immediately before any write boundary',()=>{const m=T.measurement(rows()),r=current(m),c=fake();c.now=r.receivedMonoMs+5001;assert.throws(()=>T.ensureFresh(r,c),/FINAL_READ_STALE/);});
test('wall-clock jump between admission and marker is rejected',()=>{const m=T.measurement(rows()),r=current(m),c=fake();c.now=r.receivedMonoMs;c.offset+=3000;assert.throws(()=>T.ensureFresh(r,c),/CLOCK_DISCONTINUITY/);});
test('slowdown in production upload path leaves zero POST and no quota marker',async()=>{const d=tmp(),x=require('./helpers.cjs').scene(d);try{x.clock.now=550000;x.api.time=async()=>({ok:1,time:50});await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>{},{clock:x.clock}),/TIME_BUDGET_INSUFFICIENT/);assert.deepEqual(x.writes,[0,0]);assert.equal(C.optional(d,'candidate-attempt.json'),null);assert.equal(C.json(path.join(d,'timing-upload.json')).status,'TIME_BUDGET_INSUFFICIENT');}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('read age cannot grow during canStart and still send POST',async()=>{const d=tmp(),x=require('./helpers.cjs').scene(d);try{await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>{x.clock.now+=5001;},{clock:x.clock}),/FINAL_READ_STALE/);assert.deepEqual(x.writes,[0,0]);assert.equal(C.optional(d,'candidate-attempt.json'),null);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('successful upload persists an immutable finite deadline and timing proof',async()=>{const d=tmp(),x=require('./helpers.cjs').scene(d);try{assert.equal((await A.uploadOnce(x.api,x.s,d,()=>{},{clock:x.clock})).confirmed,true);const a=C.json(path.join(d,'candidate-attempt.json'));assert.equal(a.wallDeadlineAtMs-a.atMs,4500000);assert.equal(a.timingAdmissionSha256,C.sha(C.bytes(path.join(d,'timing-upload.json'))));}finally{fs.rmSync(d,{recursive:true,force:true});}});
function marker(c){return {runId:P.parentRunId,atMs:c.wall(),wallBudgetMs:P.wallMs,wallDeadlineAtMs:c.wall()+P.wallMs};}
test('monotonic exposure guard reaches exactly the fixed deadline, never renews',()=>{const c=fake(),g=T.exposureGuard(marker(c),c);c.now=P.wallMs-1;assert.equal(g(),null);c.now++;assert.equal(g(),'WALL_DEADLINE');c.now+=10000;assert.equal(g(),'WALL_DEADLINE');});
test('starting a later worker retains remaining time, not a fresh full budget',()=>{const c=fake(),m=marker(c);c.now=100000;const g=T.exposureGuard(m,c);c.now=P.wallMs;assert.equal(g(),'WALL_DEADLINE');});
test('wall-clock rollback and forward jump both trigger close rather than extending exposure',()=>{for(const shift of [-5000,5000]){const c=fake(),g=T.exposureGuard(marker(c),c);c.offset+=shift;assert.equal(g(),'CLOCK_DISCONTINUITY');}});
test('malformed or expanded deadline marker is rejected',()=>{const c=fake(),m=marker(c);m.wallDeadlineAtMs++;assert.throws(()=>T.exposureGuard(m,c),/MARKER_INVALID/);});
test('worker honors an expired marker and calls closer once without new POST loops',async()=>{const d=tmp(),now=Date.now();let closes=0;try{C.durable(path.join(d,'candidate-attempt.json'),{runId:P.parentRunId,atMs:now-P.wallMs-1,wallBudgetMs:P.wallMs,wallDeadlineAtMs:now-1});C.durable(path.join(d,'collector-heartbeat.json'),{runId:P.parentRunId,pid:process.pid,streaming:true,atMs:now,lastConsole:now,lastCpu:now,issues:[],accepted:0});const result=await W.worker({dir:d,s:{profile:{endTick:500}},api:{},secret:{},repo:'unused',pause:async()=>{},closer:async()=>{closes++;return {status:'NOT_DEPLOYED'};}});assert.equal(result.reason,'WALL_DEADLINE');assert.equal(closes,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('tick regression between readiness and calibration is also rejected',async()=>{const d=tmp(),c=fake();try{await T.readTime({time:async()=>({ok:1,time:100})},d,'readiness',100,c);c.now+=1;await assert.rejects(T.readTime({time:async()=>({ok:1,time:99})},d,'rate-measurement',100,c),/GAME_TICK_REGRESSED/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('worker progress reads preserve the successful game-time values as evidence',async()=>{const d=tmp(),c=fake();try{await T.readTime({time:async()=>({ok:1,time:123})},d,'worker-progress',100,c);const log=C.jsonl(path.join(d,'time-observations.jsonl'));assert.equal(log.length,1);assert.equal(log[0].tick,123);assert.equal(log[0].purpose,'worker-progress');assert.equal(log[0].clockId,c.id);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('a missing timing measurement cannot authorize upload',async()=>{const d=tmp(),x=require('./helpers.cjs').scene(d);try{fs.unlinkSync(path.join(d,'timing-measurement.json'));await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>{},{clock:x.clock}));assert.deepEqual(x.writes,[0,0]);assert.equal(C.optional(d,'candidate-attempt.json'),null);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('proof from an admitted binding stage cannot substitute for upload-stage evidence',()=>{const d=tmp();try{const seed=require('./time-helper.cjs').seed(d);fs.copyFileSync(path.join(d,'timing-binding.json'),path.join(d,'timing-upload.json'));assert.throws(()=>T.verifyPlan(d,seed.profile,'upload'),/PURPOSE_CHANGED|ADMISSION_INVALID/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('in-flight time read respects outer calibration deadline rather than a new full timeout',async()=>{const d=tmp(),c=fake();let budget;try{await assert.rejects(T.readTime({time:async ms=>{budget=ms;throw new C.Failure('HTTP_DEADLINE');}},d,'rate-measurement',37,c),/HTTP_DEADLINE/);assert.equal(budget,37);const e=C.jsonl(path.join(d,'time-observations.jsonl'))[0];assert.equal(e.ok,false);assert.equal(e.error,'HTTP_DEADLINE');}finally{fs.rmSync(d,{recursive:true,force:true});}});

test('worker request and polling budgets shrink to the remaining exposure time',()=>{const c=fake(),g=T.exposureGuard(marker(c),c);c.now=P.wallMs-37;assert.equal(g.remaining(),37);c.now+=37;assert.equal(g.remaining(),0);assert.equal(g(),'WALL_DEADLINE');});
