'use strict';
const fs=require('node:fs'),path=require('node:path'),C=require('../runtime/common.cjs'),R=require('./repository.cjs'),P=C.POLICY;
function copyFiles(from,to,filter=()=>true){
 function walk(dir,rel=''){for(const n of fs.readdirSync(dir).sort()){const r=rel?rel+'/'+n:n;if(!filter(r))continue;const src=path.join(dir,n),st=fs.lstatSync(src);if(st.isSymbolicLink())C.fail('ARCHIVE_SYMLINK');if(st.isDirectory())walk(src,r);else if(st.isFile()){const dst=path.join(to,r);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst);}else C.fail('ARCHIVE_SPECIAL_FILE');}}walk(from);
}
function secretForms(token){return [...new Set([token,encodeURIComponent(token),token.slice(0,8),token.slice(0,16),Buffer.from(token).toString('base64')])].filter(x=>x.length>=8);}
function scan(text,token){if(secretForms(token).some(x=>text.includes(x)))C.fail('SECRET_SCAN_FAILED');}

function archive(o){C.verifyPackage();const refactor=path.resolve(o.refactor),compat=path.resolve(o.compat),work=path.resolve(o.work),out=path.join(refactor,P.evidencePath),h=R.head(refactor),exists=fs.existsSync(out);R.branch(refactor,P.refactorBranch);R.clean(refactor);R.clean(compat);const manifest=R.manifest();if(R.tree(compat)!==manifest.expectedSourceTree)C.fail('DEFAULT_OFF_REQUIRED');const remoteCompat=R.remote(compat,P.compatBranch),remoteRef=R.remote(refactor,P.refactorBranch);if(![P.compatBase,R.head(compat)].includes(remoteCompat)||![P.refactorBase,h].includes(remoteRef))C.fail('REMOTE_CHANGED');
 if(exists){if(R.text(refactor,['show','-s','--format=%P',h])!==P.refactorBase||R.text(refactor,['show','-s','--format=%s',h])!==P.evidenceMessage||R.paths(refactor,P.refactorBase,h).some(n=>!n.startsWith(P.evidencePath+'/')))C.fail('EXISTING_ARCHIVE_NOT_THIS_ROUND');const am=C.json(path.join(out,'ARCHIVE-MANIFEST.json'));if(!C.same(C.list(out).filter(n=>n!=='ARCHIVE-MANIFEST.json').sort(),Object.keys(am.files).sort()))C.fail('ARCHIVE_FILE_SET_CHANGED');for(const[n,x]of Object.entries(am.files)){const b=C.bytes(path.join(out,n));if(b.length!==x.bytes||C.sha(b)!==x.sha256)C.fail('ARCHIVE_CHANGED');}}
 else{if(h!==P.refactorBase)C.fail('REFACTOR_HEAD_CHANGED');const verification=require('./verify.cjs').verify(path.join(work,'live/run'),compat);fs.mkdirSync(out,{recursive:true});copyFiles(R.ROOT,path.join(out,'task-package'));for(const name of ['offline-checks','tool-tests'])copyFiles(path.join(work,name),path.join(out,name),n=>n!=='build'&&!n.startsWith('build/'));copyFiles(path.join(work,'live/run'),path.join(out,'run'),n=>!['backup.json','candidate.json'].includes(n));C.durable(path.join(out,'FINAL-VERIFICATION.json'),verification);C.durable(path.join(out,'BOUNDARY-ANALYSIS.json'),require('./analyze.cjs').analyze(verification));C.durable(path.join(out,'SOURCE-STATE.json'),{compatHead:R.head(compat),sourceTree:R.tree(compat),base:P.compatBase,refactorBase:P.refactorBase});
 const report=`# Boundary Attribution XIII\n\nCapture: ${verification.status}\nRecovery: ${verification.closure}\nRaw: ${verification.rawReports}; accepted: ${verification.acceptedReports}; complete: ${verification.completeSamples}\n\nMeasurements are inclusive intervals; new probes are not subtracted. Raw safety-stop evidence is not an accepted sample. No 12-point or production-readiness conclusion is authorized.\n`;
 fs.writeFileSync(path.join(out,'EXECUTION-REPORT.md'),report);const secret=C.loadSecret(o.secret),files={};for(const n of C.list(out)){const b=C.bytes(path.join(out,n),64*1048576);scan(b.toString('utf8'),secret.token);files[n]={bytes:b.length,sha256:C.sha(b)};}C.durable(path.join(out,'ARCHIVE-MANIFEST.json'),{kind:'boundary-XIII-archive/v1',sourceTree:manifest.expectedSourceTree,compatHead:R.head(compat),refactorBase:P.refactorBase,packageFingerprint:C.verifyPackage().fingerprint,secretScanHits:0,files});R.git(refactor,['add','--',P.evidencePath]);R.git(refactor,['diff','--cached','--check']);const staged=R.git(refactor,['diff','--cached','--name-only','-z']).toString('utf8').split('\0').filter(Boolean);if(staged.some(n=>!n.startsWith(P.evidencePath+'/')))C.fail('EVIDENCE_SCOPE_CHANGED');R.git(refactor,['commit','-m',P.evidenceMessage]);R.clean(refactor);}
 if(o.push){R.git(compat,['push','origin',`HEAD:refs/heads/${P.compatBranch}`]);R.git(refactor,['push','origin',`HEAD:refs/heads/${P.refactorBranch}`]);if(R.remote(compat,P.compatBranch)!==R.head(compat)||R.remote(refactor,P.refactorBranch)!==R.head(refactor))C.fail('PUSH_READBACK_FAILED');}
 return {status:o.push?'BOUNDARY_XIII_EVIDENCE_PUSHED':'BOUNDARY_XIII_EVIDENCE_COMMITTED',compatHead:R.head(compat),refactorHead:R.head(refactor)};}
module.exports={archive,copyFiles,scan};if(require.main===module)C.cli(async()=>{const o=C.options(['compat','refactor','work','secret'],['push']);C.requireArgs(o,['compat','refactor','work','secret']);console.log(JSON.stringify(archive(o)));});
