'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),{performance}=require('node:perf_hooks');
const C=require('../runtime/common.cjs'),A=require('../runtime/actions.cjs'),I=require('../runtime/identity.cjs'),R=require('./repository.cjs'),P=C.POLICY;
function authorization(repo,work){let common=R.text(repo,['rev-parse','--git-common-dir']);common=path.resolve(repo,common);const d=path.join(common,'treasury-experiments');fs.mkdirSync(d,{recursive:true});const p=path.join(d,P.authorizationId+'.json');C.durable(p,{authorizationId:P.authorizationId,runId:P.parentRunId,work:fs.realpathSync(work),packageFingerprint:C.verifyPackage().fingerprint,atMs:Date.now()});return p;}
function spawn(file,args,dir,name){const stdout=fs.openSync(path.join(dir,name+'.stdout'),'wx'),stderr=fs.openSync(path.join(dir,name+'.stderr'),'wx');let child;try{child=cp.spawn(process.execPath,[path.join(R.ROOT,'runtime',file),...args],{cwd:R.ROOT,detached:true,windowsHide:true,stdio:['ignore',stdout,stderr]});}finally{fs.closeSync(stdout);fs.closeSync(stderr);}if(!child.pid)C.fail('CHILD_START_FAILED');C.durable(path.join(dir,name+'-process.json'),{runId:P.parentRunId,pid:child.pid,atMs:Date.now()});child.once('error',()=>{if(!C.optional(dir,name+'-exit.json'))C.durable(path.join(dir,name+'-exit.json'),{runId:P.parentRunId,pid:child.pid,code:null,error:'SPAWN_ERROR',atMs:Date.now()});});child.once('exit',(code,signal)=>{if(!C.optional(dir,name+'-exit.json'))C.durable(path.join(dir,name+'-exit.json'),{runId:P.parentRunId,pid:child.pid,code,signal,atMs:Date.now()});});return child;}
async function waitFor(dir,predicate,ms){const end=performance.now()+ms;while(performance.now()<end){const r=predicate();if(r)return r;await C.pause(200);}C.fail('PROCESS_WAIT_DEADLINE');}
async function observe(o){const compat=path.resolve(o.compat),refactor=path.resolve(o.refactor),work=path.resolve(o.work),secretPath=path.resolve(o.secret);if(!o.execute||!o['exclusive-target']||!o['prior-workers-stopped'])C.fail('EXPLICIT_EXECUTION_REQUIRED');C.verifyPackage();R.baseline(refactor,compat);const source=R.source(compat),fp=C.verifyPackage().fingerprint,tests=C.json(path.join(o.tests,'result.json')),offline=C.json(path.join(o.offline,'result.json'));if(tests.status!=='BOUNDARY_XIII_PACKAGE_TESTS_VERIFIED'||tests.packageFingerprint!==fp||tests.passed!==require('../references/test-contract.json').count||tests.failed!==0||offline.status!=='BOUNDARY_XIII_OFFLINE_VERIFIED'||offline.packageFingerprint!==fp||offline.source.head!==source.head||offline.source.tree!==source.tree)C.fail('OFFLINE_GATES_MISSING');R.outside(work,compat);R.outside(work,refactor);R.outside(R.ROOT,compat);R.outside(R.ROOT,refactor);fs.mkdirSync(work);authorization(compat,work);const dir=path.join(work,'run');fs.mkdirSync(dir);C.durable(path.join(dir,'parent-process.json'),{runId:P.parentRunId,pid:process.pid,atMs:Date.now()});const secret=C.loadSecret(secretPath),api=require('../runtime/transport.cjs').client(secret);let children=[],session=null;
 try{await A.ready(api,dir);const observedTick=I.tick(await api.time(15000));const b=R.bind(compat,dir,observedTick),bundle=R.detachedBuild(compat,b.profileHead,work),build=I.candidate(bundle.modules,b.profileHead,b.profileTree);const current=await A.stable(api,dir,{expected:x=>I.canonical(x.modules),ms:180000,count:2});const fresh=I.tick(await api.time(15000));if(fresh<observedTick||fresh>b.profile.startTick-100)C.fail('PROFILE_EXPIRED');
 C.durable(path.join(dir,'backup.json'),current.modules);C.durable(path.join(dir,'candidate.json'),bundle.modules);session={runId:P.parentRunId,packageFingerprint:fp,source,profileHead:b.profileHead,profileTree:b.profileTree,profile:b.profile,observedTick,preparedAtMs:Date.now(),build,candidateDigest:I.digest(bundle.modules),backupDigest:P.backupDigest,backupFileSha256:C.sha(C.bytes(path.join(dir,'backup.json'))),candidateFileSha256:C.sha(C.bytes(path.join(dir,'candidate.json')))};C.durable(path.join(dir,'session.json'),session);const s=A.loadSession(dir);
 children.push(spawn('collector.cjs',['--run',dir,'--secret',secretPath],dir,'collector'));await waitFor(dir,()=>{if(C.optional(dir,'collector-result.json'))C.fail('COLLECTOR_EARLY_EXIT');const h=C.optional(dir,'collector-heartbeat.json');return h&&h.streaming&&h.lastConsole!==null&&h.lastCpu!==null&&!h.issues.length;},90000);
 children.push(spawn('worker.cjs',['--run',dir,'--secret',secretPath,'--compat',compat],dir,'worker'));await waitFor(dir,()=>C.optional(dir,'worker-ready.json'),15000);const result=await A.uploadOnce(api,s,dir,()=>{const h=C.optional(dir,'collector-heartbeat.json');if(require('../runtime/worker.cjs').collectorHealth(h,Date.now()))C.fail('COLLECTOR_NOT_READY');const w=C.optional(dir,'worker-ready.json');if(!w||!C.alive(w.pid)||C.optional(dir,'worker-result.json'))C.fail('RECOVERY_WORKER_NOT_READY');});if(!result.confirmed&&!C.optional(dir,'closing.json'))C.durable(path.join(dir,'closing.json'),{runId:P.parentRunId,reason:'UPLOAD_UNCONFIRMED',atMs:Date.now()});
 await waitFor(dir,()=>{const r=C.optional(dir,'worker-result.json');if(r)return r;if(C.optional(dir,'worker-exit.json'))C.fail('WORKER_EXITED_WITHOUT_RESULT');return null;},P.wallMs+2*P.recoveryReadMs+300000);
 }catch(e){C.durable(path.join(dir,'execution-failure.json'),{runId:P.parentRunId,error:C.code(e),noUpload:!C.optional(dir,'candidate-attempt.json'),atMs:Date.now()});if(!C.optional(dir,'closing.json'))C.durable(path.join(dir,'closing.json'),{runId:P.parentRunId,reason:C.code(e),atMs:Date.now()});
 if(session&&!C.optional(dir,'worker-result.json')){const w=C.optional(dir,'worker-process.json');if(w&&C.alive(w.pid)){try{await waitFor(dir,()=>C.optional(dir,'worker-result.json'),2*P.recoveryReadMs+300000);}catch{}}else if(!w){try{await require('../runtime/worker.cjs').close({dir,s:A.loadSession(dir),api,secret,repo:compat});}catch{}}}
 }finally{try{await R.closeSource(compat,dir);}catch(e){if(!C.optional(dir,'source-close-failure.json'))C.durable(path.join(dir,'source-close-failure.json'),{error:C.code(e)});}if(!C.optional(dir,'collector-stop.json'))C.durable(path.join(dir,'collector-stop.json'),{runId:P.parentRunId,atMs:Date.now()});for(const name of ['collector','worker']){const p=C.optional(dir,name+'-process.json');if(p){try{await waitFor(dir,()=>!C.alive(p.pid),15000);}catch{}}}for(const c of children)c.unref();}
 return require('./verify.cjs').verify(dir,compat);
}
module.exports={authorization,spawn,waitFor,observe};if(require.main===module)C.cli(async()=>{const o=C.options(['compat','refactor','work','secret','offline','tests'],['execute','exclusive-target','prior-workers-stopped']);C.requireArgs(o,['compat','refactor','work','secret','offline','tests']);const result=await observe(o);console.log(JSON.stringify(result));if(!result.captureVerified)process.exitCode=2;});
