'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),C=require('../runtime/common.cjs'),I=require('../runtime/identity.cjs'),A=require('../runtime/actions.cjs'),P=C.POLICY;
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'xiii-action-'));const mk=(id)=>{const text=`const BUILD_COMMIT = "${id}";\nconst BUILD_TREE = "${'a'.repeat(40)}";\nconst BUILD_DEPLOY_BRANCH = "default";\nconst BUILD_TAG = "test-tag";\n`;return {main:text+`\n;globalThis.__DEPLOY_BUNDLE_HASH__="${C.sha(text)}";\n`};};
function scene(dir){const backup=mk('b'.repeat(40)),candidate=mk('c'.repeat(40)),s={backup,candidate,candidateDigest:I.digest(candidate),profileHead:'c'.repeat(40),profileTree:'a'.repeat(40),observedTick:0,profile:{startTick:200}};let current=backup,up=0,re=0;return {s,get writes(){return [up,re];},setCurrent:v=>{current=v;},api:{me:async()=>({ok:1,_id:P.expected.userId,username:P.expected.username}),branches:async()=>({ok:1,list:[{branch:'default',activeWorld:true}]}),code:async()=>({ok:1,modules:current}),overview:async()=>({ok:1,shards:{shard1:{rooms:P.rooms}}}),time:async()=>({ok:1,time:0}),upload:async m=>{up++;current=m;return {ok:1};},restore:async m=>{re++;current=m;return {ok:1};}}};}
test('candidate one-shot boundary exists before request and refuses repetition',async()=>{const d=tmp(),x=scene(d);try{const up=x.api.upload;x.api.upload=async(...args)=>{assert.ok(C.optional(d,'candidate-attempt.json'));return up(...args);};assert.equal((await A.uploadOnce(x.api,x.s,d)).confirmed,true);await assert.rejects(A.uploadOnce(x.api,x.s,d));assert.deepEqual(x.writes,[1,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('closing raised during preflight prevents candidate POST',async()=>{const d=tmp(),x=scene(d);try{await assert.rejects(A.uploadOnce(x.api,x.s,d,()=>C.durable(path.join(d,'closing.json'),{})));assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('failed restore response is reconciled, never automatically retried',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(x.s.candidate);let posts=0;x.api.restore=async()=>{posts++;assert.ok(C.optional(d,'restore-attempt.json'));throw new C.Failure('HTTP_TRANSPORT_ERROR');};const a=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}}),b=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(a.confirmed,false);assert.equal(b.reason,'RESTORE_ALREADY_ATTEMPTED');assert.equal(posts,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('lost reply after accepted restore is confirmed using reads only',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(x.s.candidate);let posts=0;x.api.restore=async m=>{posts++;x.setCurrent(m);throw new C.Failure('HTTP_TRANSPORT_ERROR');};const a=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(a.confirmed,true);assert.equal(a.error,'HTTP_TRANSPORT_ERROR');assert.equal(posts,1);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('already backup consumes no restore marker and performs no POST',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});assert.equal((await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}})).confirmed,true);assert.equal(C.optional(d,'restore-attempt.json'),null);assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('third-party code is not overwritten',async()=>{const d=tmp(),x=scene(d);try{C.durable(path.join(d,'candidate-attempt.json'),{});x.setCurrent(mk('d'.repeat(40)));await assert.rejects(A.restoreOnce(x.api,x.s,d,{pause:async()=>{}}),/CONFLICT_CURRENT/);assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('absence of candidate marker never causes a recovery write',async()=>{const d=tmp(),x=scene(d);try{const r=await A.restoreOnce(x.api,x.s,d,{pause:async()=>{}});assert.equal(r.status,'NOT_DEPLOYED');assert.deepEqual(x.writes,[0,0]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('authorization and schema errors are not classified as network retries',()=>{for(const k of ['ACCOUNT_MISMATCH','LIVE_BASELINE_DRIFT_UNRESOLVED','GAME_TICK_REGRESSED','ACTIVE_BRANCH_CHANGED'])assert.equal(A.retryable(new C.Failure(k)),false);assert.equal(A.retryable(new C.Failure('HTTP_DEADLINE')),true);});
module.exports={mk,scene,tmp};

test('inherited observer and canonical typed-module guard retain pinned bytes',()=>{for(const[n,x]of Object.entries(require('../references/inherited-modules.json'))){const b=fs.readFileSync(path.join(__dirname,'..',n));assert.equal(b.length,x.bytes);assert.equal(C.sha(b),x.sha256);}assert.equal(C.blob(fs.readFileSync(path.join(__dirname,'../vendor/deployGuard.cjs'))),P.guardBlob);});
