'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../runtime/common.cjs'),W=require('../runtime/samples.cjs'),R=require('../tools/repository.cjs');const reports=require('../references/synthetic-four-reports.json').reports;const clone=x=>JSON.parse(JSON.stringify(x)),s={profile:R.profileFor(0),build:{tag:'candidate-fixture'}};
test('real XIII source-generated synthetic four-report protocol validates',()=>{for(let i=0;i<4;i++){const v=W.validate(reports[i],s,i,reports[i-1],i?JSON.stringify(reports[i-1]):null);assert.equal(v.complete,true);assert.equal(v.trace.status,'complete');}});
test('two actual-call probes are represented without adding them to measured body',()=>{const x=W.trace(reports[0].cpuProfile);assert.ok(x.outsideMeasuredBody>=0);assert.ok(W.near(Object.values(x.segments).reduce((a,b)=>a+b),x.parentInterval));});
for(const kind of ['missing','duplicate','negative','nan','reversed','parent-sum','body-sum'])test('trace rejects '+kind,()=>{const p=clone(reports[0].cpuProfile),m=p.commitmentEnvelope.marks;if(kind==='missing')delete m.callStart;if(kind==='duplicate')m.unknown=0;if(kind==='negative')m.callStart=-1;if(kind==='nan')m.callStart=NaN;if(kind==='reversed')m.callStart=m.bodyStart+1;if(kind==='parent-sum')p.phases.commitmentBuild+=1;if(kind==='body-sum')p.attribution.intervals.commitmentTasks+=1;assert.throws(()=>W.trace(p));});
test('not-called is not represented as a measured zero-cost call',()=>{const p={elapsed:.3,calls:{commitmentBuild:0},phases:{commitmentBuild:.028},commitmentEnvelope:{version:1,status:'not_called',marks:{parentStart:.1,parentEnd:.128}}};const r=W.trace(p);assert.equal(r.actualCallCost,null);assert.equal(r.status,'not_called');});
test('tail reconstruction retains cost and rejects a changed sum',()=>{const t=W.completion(reports[0].cpuProfile,reports[1].previousCpuProfile);assert.ok(t.elapsed>=reports[0].cpuProfile.elapsed);const x=clone(reports[1].previousCpuProfile);x.phases.emit+=1;assert.throws(()=>W.completion(reports[0].cpuProfile,x));});
for(const field of ['scope','call','cpu','authority','endpoint','freshness','source','local-stop','output'])test('report rejects corrupted '+field,()=>{const r=clone(reports[0]);if(field==='scope')r.scope.rooms=['E1N1'];if(field==='call')r.cpuProfile.calls.readerLoad=2;if(field==='cpu')r.cpuProfile.elapsed+=1;if(field==='authority')r.authorizesActions=true;if(field==='endpoint')r.endpoints[1]=r.endpoints[0];if(field==='freshness')r.previousRun={};if(field==='source')r.diagnosticRevision='XII';if(field==='local-stop')r.localSafety.latched=true;if(field==='output')r.padding='x'.repeat(17000);assert.throws(()=>W.validate(r,s,0));});
test('incomplete projection remains diagnostic but not a complete business sample',()=>{const r=clone(reports[0]);r.status='partial_cpu_budget';r.commitments.rows=[];assert.equal(W.validate(r,s,0).complete,false);});
test('single HTML transport layer is decoded, not recursively expanded',()=>{const line=JSON.stringify(reports[0]);const p=W.parse(line.replace(/"/g,'&#x22;'));assert.deepEqual(p.obj,reports[0]);assert.equal(W.decode('&amp;quot;'),'&quot;');});
test('unsafe raw report is retained and never promoted to an accepted sample',()=>{const w=W.watch(s),r=clone(reports[0]);r.localSafety.latched=true;w.frame(JSON.stringify([`user:${C.POLICY.expected.userId}/console`,{shard:'shard1',messages:{log:[JSON.stringify(r)],results:[]}}]),100);assert.equal(w.raw.length,1);assert.equal(w.accepted.length,0);assert.ok(w.issues.includes('CPU_OBSERVED_SAFETY_STOP'));});
test('safety control message is not a fifth sample',()=>{const w=W.watch(s);w.frame(JSON.stringify([`user:${C.POLICY.expected.userId}/console`,{shard:'shard1',messages:{log:[JSON.stringify({kind:'treasury-compat-safety-stop',thresholdCpu:5})],results:[]}}]),100);assert.equal(w.raw.length,0);assert.equal(w.state().safety,true);});

test('analysis keeps rejected raw evidence separate and never creates a zero-cost build',()=>{const A=require('../tools/analyze.cjs');const r=A.analyze({status:'INCONCLUSIVE',rawSummary:[{accepted:true,trace:{status:'not_called'}},{accepted:false,trace:{status:'complete',segments:Object.fromEntries(W.SEGMENTS.map(k=>[k,1]))}}]});assert.equal(r.accepted.actualCallsWithClosedTrace,0);assert.equal(r.accepted.segments.measuredBody.median,null);assert.equal(r.rejectedForensicOnly.actualCallsWithClosedTrace,1);assert.equal(r.rootCauseAssigned,false);});
test('analysis without any session or reports stays empty and inconclusive',()=>{const r=require('../tools/analyze.cjs').analyze({status:'NOT_DEPLOYED'});assert.equal(r.accepted.rawRows,0);assert.equal(r.rejectedForensicOnly.rawRows,0);assert.equal(r.engineCpuGapRepaired,false);});
